---
title: "Linux服务器管理研讨活动"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“Linux”](../Linux.qmd)

### Linux服务器管理讲座与研讨活动

* **主题**：Linux服务器的管理
* **目标听众**：有一定服务器管理经验的管理员，也欢迎其他对Linux有兴趣的人士旁听学习
* **目的**：增强对Linux服务器平台的认识，提高管理员服务器管理水平，促进管理员之间的交流
* **地点**：温州大学南校区5号楼B座410室（从温州市区出发，公交车17路、38路、40路、52路、53路、54路、203路到**温州大学站**(睦州垟站的下一站)下车即到，所需时间视距离从30分钟到1小时不等。从瑞安出发搭乘“瑞安-茶山”的交通车，在瑞安客运中心上车，沿途经过104国道线，在温州大学站下车。下车后横过马路进对面的小校门，左侧就是5号楼。）
* **主办/协办机构**：[温州瑞安计算机协会](http://www.rait.org.cn/)、温州Linux QQ群（1350302）
* **时间**：2008年6月29日全天（暂定）
* **日程安排**：(以下时间为估计时间，实际时间可能随着实际的讲解和讨论略有变化)

| **时间** | **形式** | **内容** | **主讲** |
| --- | --- | --- | --- |
| 8:00 | 开场白 |  | 黄长城 |
| 8:30 | 讲座 | Linux操作系统的安装与存储管理<br> （Debian Linux的安装，RAID5和LVM的安装与配置） | 陈忠克 |
| 9:30 | 讲座 | Linux服务器的远程控制 （ssh、vnc） | 陈忠克 |
| 10:00 | 讲座 | 文件服务器和网络存储服务器的安装与配置<br> （Samba、FTP、SFTP、NFS、iSCSI、SVN等） |
| 11:30 | 讨论 | 午饭、休息、讨论交流 |  |
| 13:30 | 讲座 | 数据库服务器的安装 （mysql、postgresql、sqlite、oracle） | 黄长城 |
| 14:00 | 讲座 | Web服务器和Web应用程序的安装与配置<br> （Apache、phpbb3、mediawiki、moinmoin、drupal、wordpress等） |  |
| 15:30 | 讲座 | 网络基础服务<br> （dns、dhcp、proxy、socks5、wins、vpn、iptables、iproute2等） |
| 16:30 | 讨论 | 服务器安全等 |
| 取消 | 讲座 | 流媒体服务器（real server） |
| 取消 | 讲座 | 邮件服务器的安装与配置（exim4） |

* **内容**：参见[Linux服务器管理](<Linux服务器管理.qmd>)
* **注意**：如希望与主持人互动，可自带笔记本电脑，并准备至少5G的未分区的磁盘空间。（即在磁盘分区工具当中显示有5G空间未分区，此空间最好位于磁盘的末尾，以免影响笔记本原有系统的使用。可通过删除磁盘上最后一个分区或者用PQmagic之类的工具缩小最后一个分区的大小得到。）现场也有一些台式机可供使用，但是系统受限，只能使用虚拟机，可能会影响学习效果。

[Linux服务器管理研讨活动报名](<Linux服务器管理研讨活动报名.qmd>)

### 留言

> **czk** · 2008-06-15 12:29:13
>
> 对研讨会有什么意见和建议，欢迎留言

> **221** · 2008-06-15 13:34:25
>
> 不知道到时候能不能提供现场的视频等的下载 流口水ING～

> **89** · 2008-06-18 15:17:27
>
> 是否免费 ，地点在哪里举行！

> **248** · 2008-06-28 14:28:27
>
> 哈哈  有好东东吃 啦
