---
title: "什么是Linux"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“Linux”](../Linux.qmd)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000002 在备份中缺失；以下内容来自最新可读取版本 00000001。
:::

<div dir="ltr" style="text-align: left;">出处：<a href="http://www.linux.org/info/index.html">http://www.linux.org/info/index.html</a><br><br><br><br>Linux是一个操作系统，最初由芬兰赫尔辛基大学的一名学生Linus Torvalds作为业余爱好创建的。当时Linus对一个小的UNIX系统Minix有兴趣，并决定开发一个系统能够超越Minix。他在1991年开始他的工作并发布了0.02版，之后经过不懈的努力终于到1994年发布了1.0版Linux内核。作为所有Linux系统的核心的Linux内核，它的开发和发布都是基于<a href="http://www.linux.org/info/gnu.html">GNU通用公共许可证</a>的，它的源代码任何人都可以自由获得。这个内核构成Linux操作系统的基础，整个Linux系统都是围绕这个内核来开发的。现在有数以百计的公司和组织，以及相当数量的个人发布了他们自己的基于Linux内核的操作系统版本。更多的关于内核的信息可以在我们的兄弟站点<a href="http://www.linuxhq.com/">LinuxHQ</a>，和官方站点<a href="http://www.kernel.org/">Linux Kernel Archives</a>找到。现在，一个功能全面的内核的最新版本是2.6（2003年12月发布），并且仍在不停的开发中。<br><br>除了能够自由的传播以外，Linux的功能性、适应性、健壮性方面的特点已经使它变成专有的Unix和微软操作系统的主要替代品。IBM、惠普等计算机界的巨头已经接受Linux并积极支持它的开发。在Linux第一次发布的10年后，Linux主要被作为服务器平台在世界范围内采用。作为家庭和办公用的桌面操作系统而使用的Linux也在逐渐增加。Linux也能够和芯片直接结合在一起，这被称作“嵌入”。使用这样的Linux的装置和设备也在逐渐增加。<br><br>在90年代的大部分时间里，大部分技术专家并没有意识到Linux的潜力，而把它仅仅当作计算机爱好者的一个工程，认为它不适合普通公众对计算机的需求。通过开发人员的努力，比如桌面管理系统KDE和GNOME，办公套件工程OpenOffice.org，网页浏览器工程Mozilla，现在已经有了一大批Linux上可以运行的且任何人都可以使用的应用程序，而不要求使用者有很多计算机的知识。那些对Linux的能力感到好奇的人，可以下载一个叫做<a href="http://www.knoppix.org/">Knoppix</a>的live CD版的Linux。它包括了所有你在日常使用计算机中可能需要的东西，并且不需要安装。他可以在一台支持光盘启动的计算机上运行。试用后要选择继续使用Linux的人，可以从众多的发布版本中选择一个容易安装、配置和使用的版本。关于这些产品的信息可以在我们的<a href="http://www.linux.org/dist/index.html">发布页</a>中选择<i>mainstream/general public</i>分类找到。<br><br>如果你对学习Linux感兴趣，需要某些使用方面的帮助，或者你对Linux充满热情，要帮助Linux的普及，这时你可能需要联系我们的<a href="http://www.linux.org/groups/index.html">Linux讨论组</a>。几乎世界上每一个国家、地区和城市都有讨论组，所以很可能在你的附近就可以找到一个人（可以求助或者需要你的帮助）。<br><br>Linux有一个官方的吉祥物：<a href="http://www.linux.org/info/logos.html">Tux</a>，一只Linux企鹅。它是由Linus Torvalds亲自<a href="http://www.linux.org/info/penguin.html">选择</a>的代表这个操作系统的图片。Tux由Larry Ewing和Larry创建并无私的送给社区自由使用以更好的宣传Linux。关于使用这幅图像的更多信息可以在<a href="http://www.isc.tamu.edu/~lewing/linux/">他的主页</a>中找到。其他的图像和标志可以在我们的<a href="http://www.linux.org/info/logos.html">标志页</a>找到。<br><br>很多人不知道<i>Linux</i>这个词的确切发音。由于受本土语言的影响，Linux存在很多不同的发音，但是通常发短音"i"，并且第一个音节重音，像<i><b>LIH</b>-nucks</i>一样。你可以听到Linux的创始人Linus Torvalds用<a href="http://www.linux.org/info/sounds/swedish.au">瑞典语</a>和<a href="http://www.linux.org/info/sounds/english.au">英语</a>分别怎么发音。<br><br>更多关于Linus Torvalds的信息，可以在<a href="http://www.linux.org/info/linus.html">Linus简短传记</a>中找到。<br><br><br><br><br><br></div>
