---
title: "64位CPU"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000003 在备份中缺失；以下内容来自最新可读取版本 00000002。
:::

从386、486直到奔腾系列的CPU都是32位，大多数情况32位计算已经能满足现阶段人们的需要。然而随着互联网等技术的发展，对内存的需求越来越大，比如大型服务器，每秒钟处理的数据量就超过2G，32位就难以满足需求了。

按照以前的习惯，我们把基于80x86的CPU架构称作x86结构，这时Intel公司在1978年发其第一块16位的CPU(5MHz 8086)而开发的，1981年IBM推出的第一台PC中使用的也是x86指令，同时电脑中为提高浮点数据处理能力而加的x87芯片系列数学协处理器则使用x87指令，后来将x86指令集和x87指令集统称为x86指令集。为了保证计算机能够继续运行以往开发的各类应用程序以保护和继续软件资源，后续的 CPU(包括大多数第三方处理器厂商)继续使用x86指令集，采用这种指令集的CPU系统被称作x86架构。这种架构有时叫作IA-32(Intel Architecture 英特尔体系结构的32位系统)。

64位数据寻址对于CPU来说并不是最近才有的新技术，比如，Intel 公司和HP公司在2001年共同开发的64位处理器Itanium(安腾)处理器以及后来的Itanium2(安腾2)处理器，Sun公司的 UltraSparcIII处理器，IBM公司的Power5，Apple公司的G5处理器，Compaq公司的Alpha处理器等。安腾系列处理器采用了全新的架构，放弃了以前的x86架构，以前32位应用程序必须通过一种转换工具把x86指令转为IA64指令才可以执行。而其他基于RISC架构的处理器由于标准没有完全统一，发展较慢。

2003年4月AMD公司推出首款用于PC机的64位处理器，这是一款采用x86兼容架构的64位CPU，它最大的特点就是在支持64位数据寻址的同时，向下兼容32位数据寻址，妥善解决了CPU从32位到64位的过渡和兼容问题，从而掀起了桌面处理器从32位向64位过渡的技术革命。2004年3月，Intel也发布了其首款64位Xeon处理器，它采用EM64T(Intel Extended Memory 64 Technology)技术，同时支持32位和64位运算，在运行64位程序时采用64位工作方式，而在处理32位运算时依然是IA32(即x86)工作结构，这实际上也一起被称为x86-64架构。

和Intel公司相配合，Microsoft公司在IA平台上推出了Windows XP IA64版本。随着x86-64位CPU技术的成熟，2003年 Microsoft 公司推出了一个x86-64位(以下简称x64位)Windows操作系统的测试版本，2005年4月25日在西雅图正式发布了x64位的 Windows，这个系统将同时支持Intel和AMD的x86-64位处理，普通用户可以选择Windows XP Professional x64版，服务器则可以选用 Windows Server 2003 x64位。据称，x64位Windows不会出现在零售市场，购买64位芯片的台式机和服务器用户才会获得x64位Windows操作系统，而已经拥有 64位机器的用户将可以用32位Windows系统免费升级到x64位。
