---
title: "CPU简史"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

### (1) 集成电路

1947年，贝尔实验室的三位科学家发明了晶体管，晶体管迅速替代了电子管占领了世界电子领域。随后，晶体管电路不断向微型华的方向发展。1957年，美国科学家达默提出了“将电子设备制作在一个没有引线的的固体半导体板块中”的大胆思想。
1958年，美国德克萨斯州仪器公司的工程师基尔比在一块半导体硅晶片上将电阻、电容等分立元件集成在里面，制成世界上第一片集成电路。也正因为如此， 2000年的诺贝尔物理学奖颁发给了已退休的基尔比。1959年，美国仙童公司的诺伊斯用一面工艺制成半导体集成电路，从此开启了集成电路时代,为CPU 的诞生创造了条件。

### （2）第一块微处理器Intel4004

大规模集成电路开始应用后不久，在个人电脑CPU发展史上有着最重要地位的两个公司INTEL的AMD相继诞生了。INTEL公司最初是生产存储芯片的，而AMD公司则主要为其他公司设计、制造产品的。INTEL公司的一名研究员霍夫提出了新的构想——能否将计算机上的所有逻辑单元集成到一个芯片上并在上面编制简单通用的程序，在外部软件的辅助下以简单通用的程序，在外部软件的辅助下以简单的指令控制集成电路进行复杂的工作，即是使用通用的硬件设计加上不同的外部软件支持来完成不同的应用，这就是今天所有微处理器的原理。在同事的帮助及公司的支持下，霍夫把中央处理器的全部功能集成在一块芯片上，并加上存储器。他们在1971年制造出了第一块CPU命名为4004。

4004芯片其实是为Busicom calculator专门设计制造的，4004拥有46条指令，采用16针直插封装。集成了2300只晶体管，四位字长，数据内存和程序内存分开，1K数据内存，4K程序内存。运行时时钟频率预计为1M，最终实现达到了740KHZ，能进行二进制编码的十进制数字运算。这款CPU很快就得到了整个业界的承认，蓝色巨人IBM还将4004装备在IBM1620机器上。Intel4004芯片拉开了微处理器发展的序幕。

### (3) Intel 8008

1972年,Intel继4004后又研制出8008,集成了3500只晶体管，字长也增加到了八位。当时人们把它应用在不太灵活、被称为“TV打字机” 的终端设备上。8008的运算能力比4004强劲2倍。1974年一本无线电杂志刊登了一种使用8008作为处理器的机器，叫做“MARK-8”（马克8 号），这也是目前已知最早的家用电脑了。

虽然从今天的角度看来，“MARK-8”非常难以使用、控制、编程及维护，但是这在当时却是一个伟大的发明。8008一举成名，而AMD也代替Intel生产了部分8008芯片。

### （4）Intel 8080

1974年，Intel研制出8080处理器，集成6000只晶体管，每秒运算29万次，拥有16位地址总线和八位数据总线，包含7个八位寄存器，支持 16位内存，同时它也包含一些输入输出端口，这也是一个相当成功的设计，有效解决了外部设备在内存寻址能力不足的问题。

开始8008主要应用于控制交通信号灯，很快EdRoberts宣布AItair8800(牵牛星，这个名字来源于当时电视节目里一个流行的科幻剧）个人电脑的诞生，它的核心是8080芯片，有256K存储器，没有键盘、鼠标、显示器、数据存储设备，也没有软件，输入数据是通过触发器的开关来记录代码的，输入是用闪烁的红灯给出二进制代码的答案。这是有史以来第一个广为人知的个人电脑。

在此以后，Intel、Motorola 、Zilog又相继推出INTEL8085、MC6800、Z80等字长为8位的微处理器。这些微处理器集成约9000多只晶体管，开始替代电子逻辑元件，被应用于各种应用电路和设备之中。

### (5) Intel 8086

1978 年,Intel推出了首枚基于X86架构的16位微处理器8086,集成2.9万个晶体管,时钟频率为4.77MHZ，内部数据总线（CPU内部数据传输总线）与外部数据传输总线（CPU外部传输数据的总线）均为16位，地址总线为20位，可寻址1MB内存。同时生产出与之配合的协处理器8087.

数字协处理器是协同CPU进行对数指数和三角函数等数字运算（俗称浮点运算）的附加处理器,CPU的浮点运算能力主要取决于协处理器，而浮点运算对于电脑在处理3D数据时至关重要。在8088、80286和80386时代，CPU和协处理器是分别安装在主板上的。在80486时代，凡型号上标有DX的 CPU均已内置协处理器。

### (6) Intel 8088

1979年，Intel公司推出了16位微处理器8088，Intel8088双列直插DIP封装，插在主板DIP插座上使用。8088的性能与8086 完全相同，只是将外部数据总线改为了8位，目的是使其能够直接使用和控制当时的大量外设。正是由于这一改进，造就了Intel公司CPU产品的主流地位。

### (7) Intel 286

1982年,INTEL在8086的基础上，推出了80286芯片(16位字长,集成了14.3万只晶体管).时钟频率由最初的6MHZ逐步提高到 20MHZ.其内部和外部数据总线皆为16位,地址总线24位.与8086相比，80286能支持更大的内存（16MB），可以使用外存储设备模拟大量储存空间，从而大大扩展了80286的工作范围，还能通过多任务硬件机构使处理器在各种任务间来回快速切换，以同时运行多个任务，其速度比8086提高了5 倍甚至更多。

在发布后的六年中，全球一共交付了一千五百万台基于286的个人电脑。生产兼容IBMPC的康柏公司抢在IBM前面推出了286的PC，一举打败了IBM 成为了PC市场上的新霸主。尽管INTEL的8088/8086/80286这些芯片非常成功，但同时期Zilong公司的Z8000、Motorola 公司的68000等处理器均有不错的性能，IBM、AMD公司也在自行研制CPU，呈现出百家争鸣的局面。

### （8）Intel 386

1985年，INTEL再度发力推出了80386处理器。386集成了27.5万只晶体管，超过了4004的一百倍！并且386还是INTEL第一种32 位处理器，时钟频率由最初的12.5MHZ逐步提高到40MHZ，其内部和外部数据总线均为32位，地址总线也是32位。同时也是第一种具有“多任务”功能的处理器，这对微软的操作系统发展有着重要影响，所谓“多任务”就是说处理器可以同时处理几个程序的指令。80386比80286提供有更多的指令，频率为12.5MHZ的80386每秒可执行600万条指令，比频率为16MHZ的80286快2.2倍.

INTEL386也有不少竞争者,其中Motorola的68020、IBM的386SLC、AMD的Am386SX/DX均是相当不错的32位CPU。 68020是Motorola公司于1984年推出的32位CPU，性能超群，被Apple公司选为PC-MAC个人电脑中的处理芯片。IBM 386SLC是由IBM在研究80386的基础上设计的80386兼容CPU，内置CACHE，由INTEL制造，与INTEL80386CPU在管脚上完全兼容。IBM宣称386SLC用于某些应用程序时，性能上要比INTEL80386提高88%。AMD386SX/DX是AMD公司推出的32位兼容微处理器，性能上和Intel的80386相差无几，是当时的主流产品之一。

### （9）Intel 486

1989年，INTEL发布了486处理器。很多厂商看清了Intel的发展规律，因此很快就随着INTEL的营销战而转型成功。80486处理器集成125万个晶体管，时钟频率由25MHZ逐步提升至33MHZ、40MHZ、50MHZ及后来的100MHZ。

80486是INTEL第一个内部包含数字协处理器的CPU，并在X86系列中首次采用了RISC（精简指令集）技术，从而提升每时钟周期执行指令的速度；386仅支持8位或16位的ISA总线，而486CPU支持的VESA和PCI局部总线比ISA总线要快得多；内置了8K超高速缓冲储存器，大大缩短了处理器和与慢DRAM（动态随机存取存储器）之间交换数据的等待时间。由于这些改进，80486的性能比带有80387数字协处理器的80386要快了 4倍有余。

此外，美国德州仪器、Cyrix公司、AMD公司、IBM公司也均生产出了486级的处理器与INTEL竞争，为此INTEL将486分为有数字协处理器的486DX与无数字协处理器的486SX两种以不同的性能和价格来争夺市场。INTEL公司后期推出的80486（80486DX2、 80486DX4）采用了时钟倍频技术以避免因内外部设备工作频率限制CPU主频进一步提高。以80486DX2为例，其涵义是CPU内部工作频率为外频的两倍，这样缓解处理器内部高速与外部总线的慢速的矛盾。（来自：http://bbs.zol.com.cn/index20060208/index_86_108161.html）
