---
title: "nds非官方FAQ"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

## 关于nds

Q: 什么是NDS?
A: NDS游戏机
任天堂于E3正式发表，预定于今年底正式上市，开发代号“Nintendo DS（简称NDS）”的新掌上游戏机，任天堂7月28日正式发表将以此代号为主机正式名称，并公布主机的最终造型，其官方网站也同时开张。
NDS是任天堂预定于年底投入市场的新掌上游戏机，是一款不同于以往设计风格的掌上游戏机，配备了两个3吋背光TFT液晶屏幕，其中一个屏幕具备触控手写功能；内建麦克风，可支持语音输入；内建无线网络功能，并可支持802.1b Wi-Fi标准；具备比N64更强大的3D画面，并同时具备GBA卡匣插槽与NDS专属游戏芯片卡插槽，可兼容GBA游戏.
由于双屏幕、触控板、语音输入与无线网络的结合，提供了独特的游戏方式，包括任天堂在内的各支持游戏厂商都投入了各种新型态的游戏创作，目前全球已有120款NDS游戏在进行开发，任天堂本身就投入了20款，加盟厂商超过了100家。
本次所公布的NDS最终定案造型，与5月E3展所公布的样机有所不同，设计更加简练，质感也更为高级，电源钮与选择、开始等按钮的尺寸变大，位置左右对调，其余配置大致上维持原本的设计。任天堂并预告将于近日内正式公布上市日期与游戏软件阵容等，官方网站目前也已开张，有兴趣的玩家不妨密切注意后续消息的公布，以及官方网站后续的更新。

Q: nds有何特点？
A:

* 革命性双屏设计

	双屏——创造前所未想的游戏乐趣，开创随身游戏新时代

* 手写笔 触摸屏

	触碰、滑动，全新的操控方式，不一样的游戏感觉

* 无线网络传输

	支持多人无线联机游戏，将快乐与朋友共分享

* 涂鸦聊天

	无线网络传输，畅快聊天更自由；手写输入，随意涂抹无拘束

* 兼容上千款游戏

    兼容上千款Game Boy Advance游戏。\*
* 高灵敏麦克风

	内置高灵敏度抗噪麦克风，让声控游戏、语音聊天成为可能

* 立体声扬声器

	逼真的环绕立体声效果，制造身临其境的游戏感受

* 配备充电锂电池: 可反复充电，无需频繁更换电池，一次充电可连续使用6－10小时

Q: nds的硬件配置如何？
A:
尺寸
·纵84.7mm/横148.7mm/厚28.9mm/重275g（包括内置充电电池，手写笔）

插口/插槽
·DS游戏带插槽
·GBA游戏带插槽
·立体声耳机/麦克风插口

无线通信机能
·对应IEEE802.11和任天堂独有通信频率这2种方式
·电波接收距离：10M-30M（根据周围环境而定）
·根据游戏的设置可以让复数的玩家就使用1盘游戏带来进行游戏

声音
·内置立体声扬声器（根据游戏设置可实现虚拟环绕效果）

其他机能
·内置时钟（表示日期·时间/闹钟机能）
·触摸屏系统
·内置“Pict Chat”，可实现最大16人的文字或图画的无线交流

自定义设置
·启动模式的切换
·使用语种：日语，英语，德语，法语，西班牙语，意大利语
·在显示GBA游戏时可以进行上下屏幕的切换
·用户情报

电池/电源
·内置充电锂电池
·电池持续时间：约6-10小时（根据软件不同而变化）
·全充电时间：4小时
·有睡眠模式等省电机能
·附带直流电源

## 关于Supercard

### 关于Supercard卡本身

Q: 什么是Supercard？
A: Super Card简称SC，是GBA/GBASP/GBM/NDS游戏机的辅助设备，利用这套系统可以在GBA上玩游戏，看电影、电子书、漫画书、图片查看、音乐播放等以达到娱乐及学习、开发等用途。SuperCard根据存储介质的不同，分为SD和CF两个版本。其基本原理是利用SD/CF卡的超大容量（SD/CF卡128M就相当于一般烧录卡的1G容量），GBA/GBASP/NDS可以很方便地运行SD/CF卡上的GBA/NDS游戏。SD/CF卡上的内容是从电脑上通过SD/CF读卡器拷贝到SD/CF卡上的

Q: SC卡有什么样的特色？
A:

* 即时存档（仅限GBA）：即时存档也有叫实时存档，英文名叫：Real Time Save。这功功能可在游戏中任意时刻将当前游戏状态保存下来，一但游戏失败，或关机后想在下次同一地方开始，只需要读出上次存的即时存档就可以马上复活或恢复继续游戏了
* 容量巨大、支持压缩：由于使用的是SD/CF卡做为游戏的存贮空间，想要多大的空间就看SD/CF卡有多大了，而且SD/CF卡按容量计算是一般烧录卡的8倍，比如一片128M的SD/CF卡是相当于1G烧录卡的容量。市面上最大SD卡容量达32Gbit(4GByte)
* 边玩游戏、边看攻略（仅限GBA）：可以在用转换软件转换游戏的时候，可以在游戏中附加一个文本文件，这个文本文件当然可以是游戏攻略啦。在玩游戏的时候，只需要按L+R+B+START四个键，就能马上切换到文本画面，看了攻略后，按一下Ｂ链，马上又切换回游戏继续玩啦。
* 快速烧录：通过SD卡和SD读卡器，只需将转换好的游戏拷贝到SD/CF卡上就行了，速度当然快啦。
* 价格低廉
* 超强金手指（仅限GBA）：玩游戏时任意时刻都可进入金手指设置
* 存档的兼容性：支持所有的存档方式，存档兼容性好。
* 支持四键复位回选ROM菜单功能，支持四键复位回游戏开始功能

Q: ＳＣ卡耗电量如何？
A: 因为ＳＣ卡还需要带动CF/SD卡，如何频繁换游戏，会耗电在一些，一般SP的标准原装电池开灯，声音开到最大能支持5-6小时．一下根据dimisong的电力报告：

1. nds满电+超执刀+passme+wariotouch(引导)+声音全开=3小时14分红灯
2. nds满电+超执刀+passme+nintendog(引导)+声音全开=3小时16分红灯
3. nds满电+逆转裁判ds（美版）+passme+nintendog(引导)+声音全开=3小时44分红灯
4. nds满电+动武之森（美版）+passme+nintendog(引导)+声音全开=2小时52分红灯

在flashmev5,without wifi条件下：

1. nds满电+超执刀+声音全开=5小时31分红灯
2. nds满电+nintendog(美版)+声音全开=5小时11分红灯
3. nds满电+逆转裁判ds（美版）+声音全开=6小时04分红灯 
4. nds满电+动武之森（美版）+声音全开=4小时59分红灯
5. nds满电+mariokartDS+声音全开=4小时44分红灯
6. nds满电+moonshell+mp3+px100(森海塞尔耳机)=7小时01分红灯

Q: 能用40X的高速CF卡吗？
A: 能用，ＳＣ卡可支持各种速度的ＣＦ卡

Q: ＳＣ支持ＣＦＩＩ型卡吗，就是那种厚的？
A: 不支持，ＳＣ卡只支持ＣＦＩ型

Q: 如何查看SC的内核办版本？
A: 在开机的时候按Ｌ＋Ｒ，进入测试画面，在测试画面中按Ａ可进入下一项，在最后一项就可看到内核版本．

Q: 如何升级内核？
A: 下载解压最新内核放到CF/SD卡根目录, 开机后会自动升级．

Q: 如何进入测试SC卡功能？
A: 在开机的时候按Ｌ＋Ｒ，进入测试画面，在测试画面中按Ａ可进入下一项，按Ｂ可开始进入正常游戏画面．

Q: SC对ＣＦ卡的兼容性如何？
A: 请看ＳＣ的兼容性测试报告．
http://www.romman.net/forum/dispbbs.asp?boardID=37&ID=18920&page=1

Q: SC支持长文件名吗？如何支持?
A: SC目前支持长文件名. 只要将安装好软件后的目录中一个scfont.fon个的文件复制到CF卡根目录就行了.

Q: 为什么需要转换游戏？
A: 下载SC采用特别的硬件结构，游戏需要转换才能在上面运行，另外，金手指，复位，即时存档，压缩功能都需要在这里解决．其它烧录卡也转换过的, 只不过他们是在烧录的时候转换的, 他们烧录的时候速度慢, 在转换你也感觉不到.

Q: SC卡会不会烧CF/SD卡？
A: 有可能。在玩到自动关机，不充电马上重新开机时，可能会烧掉CF/SD卡。所以玩SC的时候一定要注意，电源灯变红灯时，马上充电，接着电源玩，这样才会相对安全

### 关于Supercard卡GBA游戏功能

Q: 如何用SC卡在游戏机上玩GBA游戏？
A: GBA游戏必须经过转换软件转换后，才能在SC卡上玩。1. 运行转换软件，在游戏列表菜单中，按增加按钮，就可加入游戏，支持多选，支持ZIP(文件中必须只有一个GBA文件)，GBA后缀的文件。 2. 按输出按钮，转换ROM。 3. 将CF/SD卡插入读卡器，将输出目录中的游戏复制到CF/SD卡上。(注意：每个游戏会生成三个文件，一个是.GBA的游戏文件，一个是.SAV的普通存档文件，一个是.SCI的即时存档文件，要将这三个文件都复制到CF卡上。) 4. 将SD/CF卡插入SC卡中，再把SC卡插入游戏机中，开机。

Q: 什么是即时存档？
A: 即时存档也有叫实时存档，英文名叫：Real Time Save，玩家不用再等到玩到游戏存盘点才能存档，直接在任何时候都可以保存下当时的游戏状态，死了后再重来，或以后接着玩，所以香港等地叫"无限复活".
最早推出这个功能要追述到上世纪90年代，香港邦谷公司推出了著名的超任博士，极大扩展了当时雄霸游戏市场的超级任天堂的功能，加入了金手指，慢动作，即时存档（无限复活），等强大功能。当年的电视广告就是，超级玛莉在进行游戏中，一遇到难的地方，马上用慢动作功能，一旦死掉，马上用即时存档功能来无限复活，呵呵，就象时光可以倒流一样，打不过，从刚才存的地方马上又重来，没有玩不过的游戏啦。
当然，还有一个重要的功能，就是ＧＢＡ的游戏存档格式，或掉档再也不会困扰大家了，想什么时候存盘就什么时候存盘，不会出现这种情况：＂老妈说：快睡觉啦＂，这边还没有找到游戏中存档的地方，结果被老妈强行关机，白玩啦，呵呵

Q: 即时存档效果如何呢？
A: 即时存档，无限复活实战录象
http://www.romman.net/forum/dispbbs.asp?boardID=37&ID=19274&page=1

Q: 如何保存游戏存档？
A: ＧＢＡ绝大部分游戏都是需要存档的，ＳＣ卡没有电池设计，存档需要保存到CF/SD卡上，所以在游戏中存完档后，需要按L+R+A+SELECT进入存档菜单，这样存档才会被保存到ＣＦ卡上，永不掉档，下次玩游戏时，存档会自动调入．

Q: 游戏中有哪些热键？
A: 普通存档：热键是：L+R+A+SELECT。按A确认，按B取消。游戏都有存档，这就是普通存档，需要备份到CF/SD卡上. 下次玩游戏的时候可自动调入存档. 如果在转换游戏时，将允许多个存档选上的话，会有四个存档位。即时存档：热键是：L+R+B+SELECT。按A确认，按B取消。进入即时存档菜单，可以存，也可以调出。如果在转换游戏时，将允许多个即时存档选上的话，会有四个即时存档位。即时攻略：热键是：L+R+B+START。L+R翻十页，左右键翻一页，按B退出。边玩游戏，边看攻略，可马上切换到功略画面。注意：需要在转换游戏时，将允许加入文本文件选上的，并加入攻略文本文件。 实时金手指：热键是：L+R+A+START。按A修改，按B退出。可在游戏中随时切换到金手指画面，进行金手指调整，可单独打开或关上金手指单项，玩游戏的利器。

Q: 游戏白屏如何办？
A: 在请在游戏转换的时候，关闭游戏复位和金手指选项，这是由于补丁错误造成的．

Q: 补丁库是怎么用的？
A: 补丁库放到电脑ＳＣ软件安装后的目录，覆盖原来旧的补丁库就行了，是转换软件自动使用的，不用放到CF/SD卡上．

Q: 用关机存档办法解决网球王子2004（1473，1474）问题?
A: 这个游戏如果打上复位补丁就会白屏, 不打的话, 可以玩, 但是存不了档, 因为热键不起作用. 这时候就要用关机存档的办法啦. 方法是: 在游戏中存了档后, 关机马上开, 2秒之内要开, 这时游戏的存档还在SC卡上, 但是可以回到SC主菜单了, 按右键, 进入SAVE菜单, 找到你刚才玩的那个游戏的名字的存档文件, 如: 网球王子.SAV, 按A保存. 就可将SC内存中的存档保存到CF卡上了, 就不会掉档了. 此方法也适用于其它类似的游戏.

Q: 对于256M大游戏，或一些打了复位补丁就不能正常运行的游戏，如何存档呢？
A: 有些256M的大游戏，如果打了复位补丁或金手指补丁，就会大于256M，不能运行，或是如果打了复位补丁就不能正常运行的游戏如何存档呢？因为如果没打复位补丁的话，就不能在游戏中按L+R+A+SELECT将存档保存到CF卡上，一关机存档就没有了，这时在转换游戏的时候，只打存档补丁, 在玩游戏中想存档到CF卡的时候，关机后，马上开机，到SC卡的SAVER菜单中，选中你刚才玩的那个游戏的.SAV文件，按A，就可将存档保存在CF卡上了。因为SC卡可在关机后20秒内存档不会丢失。

Q: 要是忘记保存存档到CF卡就关了机，如何办呢？
A: 如果你能在20秒内能再开机的话，存档都还在SC卡上，因为SC卡可在关机后20秒内存档不会丢失。方法是：马上开机，到SC卡的SAVER菜单中，选中你刚才玩的那个游戏的.SAV文件，按A，就可将存档保存在CF卡上了。

### 关于SuperCard卡nds游戏功能

Q: 用烧录卡玩NDS游戏对游戏机有什么要求？
A: 游戏机必须使用PASSME引导或者FLASHME引导。PASSME1代只支持部分主机。PASSME2代兼容所有主机。用PASSME引导需要一张正版卡。FLASHME引导是使用破解的FIRMWARE引导，需要刷机，不需要正版卡。

Q: PassMe1代兼容哪些nds主机？
A: PASSME官方网调查的NDS最新兼容性列表 http://www.dspassme.com/dstrackerlist.shtml

Q: 如何用SC卡在游戏机上玩NDS游戏？
A: NDS游戏必须经过转换软件转换后，才能在SC卡上玩。1. 运行转换软件，在游戏列表菜单中，按增加按钮，就可加入游戏，支持多选，支持ZIP(文件中必须只有一个NDS文件)，NDS后缀的文件。 2. 按输出按钮，转换ROM。 3. 将CF/SD卡插入读卡器，将输出目录中的游戏复制到CF/SD卡上。 4. 将SD/CF卡插入SC卡中，再把SC卡插入游戏机中，按住A-B-X-Y开机。

Q: NDS游戏如何存档的?
A: NDS游戏转换后会有两个文件, 其中一个是.sav文件, 就是存档文件了, 将这两个文件都复制到SD卡上, NDS游戏在游戏中存档的时候, 会自动存档到.SAV文件. 下次游戏会自动调入, 十分方便, 对玩家来说感觉就象正版游戏一样存档. 而且这个.sav文件还可方便备份到电脑, 或与别人交换存档文件.

Q: NDS游戏如何使用别人的存档的?
A: 很简单, 只需要将别人的\*\*\*.sav改名成和你的NDS游戏文件名前面一样就行了, SuperCard是根据文件名前面相同自动找.sav文件的.

Q: 玛丽奥ds吃到一颗星就会死机死机，一些游戏白屏，如何解决？
A: 这些游戏rom可能在dump的时候发生错误，需要打补丁。在网上搜索IPS补丁就可以找到补丁以及打补丁的工具。

### 关于SuperCard卡其它功能

Q: 如何看电影？
A: 首先要下载电影播放软件，解压后放到CF/SD卡上，然后象运行游戏一样运行它，会出现电影播放软件的菜单，第一个菜单就是放电影的．当然，ＧＢＡ格式的电影你要放到CF/SD卡上，你才有电影可看．

Q: 如何转换电影？
A: 首先要下载电影转换软件，将一般的视频转换为ＧＢＡ专用格式．

Q: FC/PCE/GB/SMS等游戏存档的方法?
A:

1. 复制一个\*.sav的存档文件（大小64k)
2. 将该文件名改成与游戏ROM同名（例如：游戏ROM是bbaa.nes 存档文件名应为bbaa.sav)
3. 打开模拟器的即时存档，存游戏
4. 按LEFT+RIGHT+A+SELECT将进度存入CF卡中，
5. 下次玩游戏时，SC将会自动装载该存档

Q: SC卡能玩GBC游戏吗?
A: 部分游戏能玩. 部分GBC游戏能在GB游戏机上以黑白的方式玩, 这部分游戏也能在SC上玩, 因为SC上的内部GB模拟器只模拟了GB, 不有模拟GBC的. 比如GBC游戏坏玛莉就可以在SC上玩, 不过是黑白的.

Q: SC卡如何播放音乐?
A: 把MP3用电影转换软件转成GBS格式，下载电影播放软件filmplay.bin到CF/SD卡中，在ＧＢＡ上先运行filmplay.bin，然后就有看电影，放音乐的介面了，进入放音乐相应的菜单，可找到．ＧＢＳ文件，就可放音乐了．
