---
title: "温州第二实验中学学生成绩管理系统"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

## 温州第二实验中学学生成绩管理系统

### 系统概述

系统的目标是满足学校任课教师对考试成绩的日常处理，包括录入、修改；满足学校各管理部门对考试成绩的日常处理，包括录入、修改、删除、查询、统计、报表。系统包括以下几个子模块：学生管理模块、考试信息管理模块、成绩统计模块、单元考试模块。

系统所涉及的角色包括：系统管理员、教务管理员（校长、教务处等）、班级管理员（班主任）、任课教师。系统管理员管理维护温州第二实验中学学生成绩管理系统，设置各级管理部门人员及其权限。教务管理员完成全校范围内的学生管理模块的日常处理、成绩统计模块的日常处理以及考试信息管理模块中的考试管理。班级管理员对所管理班级进行成绩统计模块的日常处理。任课教师在其所担任的课程范围内进行考试信息管理模块的成绩管理以及成绩统计模块的日常处理。

### 学生管理模块

#### 模块概述

该模块完成学生及其相关信息的日常处理，包括学生信息的录入、批量导入、修改和删除，教师信息的录入、修改和删除，年级、班级信息的录入、修改和删除。

#### 数据定义

1. 年级的信息包括：入学年份
1. 班级的信息包括：所属年级、班级序号、班主任
1. 学生的信息包括：姓名、性别、所属班级、学号、状态（是否毕业、休学、退学）
1. 教师的信息包括：姓名、任教学科（可以多个）

#### 功能定义

1. 年级信息的录入、修改、删除
1. 班级信息的录入、修改、删除
1. 教师信息的录入、修改、删除
1. 学生信息的录入、批量导入（用Excel软件导出的文件导入）、修改、删除

以上操作只有教务管理员能够处理。班主任可以修改学生信息？？

### 考试信息管理模块

#### 模块概述

该模块完成考试相关信息的日常处理，包括考试类别的，考试科目的

#### 数据定义

1. 考试类别的信息包括：考试类别名称、所属年级、学期、总分优秀分数线、总分及格分数线
1. 考试科目的信息包括：考试科目的名称。其中体育科目分男女生，男女生有不同的任课教师。
1. 考试的信息包括：所属考试类别、所属考试科目、教师录入截止时间、优秀分数线、及格分数线、在考试类别中的比重、考试满分值、分数制。
1. 考试成绩的信息包括：所属学生、所属考试、考试成绩。
1. 考试成绩等级制表：制的名称，级数（个数），级的表示（一个字母），各级分数段。
1. 教师任课信息包括：所属班级、任教课程、任教教师、任教学期。

学期用一个整数表示，1表示初一上学期，2表示初一下学期，3表示初二上学期，4表示初二下学期，5表示初三上学期，6表示初三下学期。

#### 功能定义

1. 考试类别的录入、修改和删除
1. 考试科目的录入、修改和删除
1. 考试的录入、修改和删除
1. 考试成绩的录入、批量导入、修改和删除。教师录入成绩的时候，输入一个成绩，按回车可以自动跳到下一格录入下一个学生。

本模块所有信息都可以由教务管理员处理。考试成绩的信息可以由任课教师进行处理。

### 成绩统计模块

#### 模块概述

该模块完成学生及考试相关信息的各种查询、统计、报表和分析处理

#### 数据定义

#### 功能定义

1. 学生统计信息包括：各考试的班名次、段名次（同分数的排名应该一致），各考试类别总分的班名次、段名次、总分、平均分。
1. 班级统计信息包括：各考试的班平均分、班优秀率、班及格率，各考试类别总分的班平均分、班优秀率、班及格率。
1. 年级统计信息包括：各考试的年级平均分、年级优秀率、年级及格率，各考试类别总分的年级平均分、年级优秀率、年级及格率。

某学生某考试类别的总分由该学生该考试类别中的各个科目成绩按照比重加权得到。

1. 班级成绩汇总表：包括该班级在某考试类别中每个学生各学科的成绩和考试类别统计信息的列表。按分数从高到低排序，也可以按学号排序。可以将该表导出成EXCEL能打开的文件。
1. 年级成绩汇总表：包括该年级在某考试类别中每个学生各学科的成绩和考试类别统计信息的列表。按分数从高到低排序，也可以按学号排序。可以将该表导出成EXCEL能打开的文件。
1. 考试类别成绩汇总表：包括该考试类别中各班中各科的统计信息，以及各年级中各科的统计信息，列出各班各科任教教师的名字。（可以指定某个学生是否参与此表统计，指定时列出班级中所有学生按照学号排序，或者列出年级中所有学生按照总分排序）
1. 汇总表：某班级每个学生在多个考试类别中若干个特定学科分数、总分和排名
1. 汇总表：某年级每个学生在多个考试类别中若干个特定学科分数、总分和排名，按分数从高到低排序，也可以按学号排序。
1. 汇总表：某个班级每个学生某两次考试类别间的总成绩、班名次、段名次对比
1. 汇总表：某个年级及其中各个班级在某个考试类别中的某个科目的成绩在指定的各个分数段的分布情况、该科目的平均分
1. 汇总表：某个年级某考试类别的某个学科或者总分的前X名（可以指定一个范围）在各个班级中的分布情况

班级管理员可以查询本班学生的统计信息和本班的统计信息。教务管理员可以查询全校各学生的统计信息、全校各班统计信息、全校各年级统计信息。

注：优秀率和及格率的算法。算法一：取全段20%名以上的最低分分值，高于此分为优秀；全段人数80%名以上最低分的分值做为及格分，高于此分为及格，低于此分算不及格。算法二：指定及格分数线和优秀分数线，高于或等于优秀分数线为优秀，低于及格分数线为不及格，其他为及格。）

注二：输出格式可以按照百分制输出，也可以按照ABCDE五级制输出。ABCDE分别代表优秀、良好、中等、及格、不及格。百分制到五级制的转换算法是15%是A，30%是B，30%是C，20%是D，5%是E。

### 单元考模块

#### 数据定义

* 单元考试的信息包括：单元考试序号，所属科目，所属班级，学期，考试满分
* 单元考试成绩信息包括：所属单元考试，学生，考试成绩

#### 功能定义

* 单元考试的创建、修改、删除。
* 单元考试成绩的录入、批量导入、修改、删除。
* 学生单元考试汇总报表：某学生某学期某科目各次单元考（可以多选）的成绩，并给出各单元考之间班级排名升降的情况。
* 单元考试报表：在某班某学期某科目某单元考试中，列出所有学生成绩、名次并按成绩从高到低的顺序排列，并给出平均分。可以打印，可以导出成EXCEL可读的格式。
* 各科单元考试汇总报表：列出某班某学期每个学生的相同序号的各科目单元成绩的总分，给出班级排名。可以打印，可以导出成Excel可读的格式。

班主任可以对任教班级进行所有报表功能处理。任课教师可以进行任教课程范围内的所有处理。

### 运行要求

在单台微型服务器上实现：

* 系统要至少能够承受每年1000学生至少十年的成绩存储和处理的需求。
* 系统要至少能够承受30个教师同时在线进行各种处理的需求。

## The End
