---
title: "万维网"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000002 在备份中缺失；以下内容来自最新可读取版本 00000001。
:::

万维网（亦作“网络”、“WWW”、“W3”，英文「Web」或“World Wide Web”），是一个资料空间。在这个空间中一样有用的事物为一样“资源”，并且由一个全域“统一资源标志符”（URI）标示。这些资源通过超文本传输协议传送给使用者，而后者通过点击链接来获得资源。

万维网常被当成互联网的同义词，不过其实万维网是靠着互联网运行的一项服务。

### 基本术语

超文本是由一个叫做网页浏览器的程序显示。网页浏览器从网页服务器取回被称为“文档”或“网页”的资料并予以显示。通常是显示在电脑显示器。人可以跟隨网页上的超链接再获取资料，甚至也可以发出资料给服务器。顺着超链接链获取资料的行为又叫浏览网页。相关的資料通常互相联系在一起形成一群网页集，又叫网站。

英文短语“surfing the Internet”（“网上冲浪”），即浏览网络，首先由一个叫简·阿莫尔·泡利（Jean Armour Polly）的作家通过他的作品《网上冲浪》使这个概念被大众接受。这本书由威尔逊出版社在1992年6月正式出版。她可能是独立提出这个概念的，但在更早的1991年到1992年间在Usenet就有人使用了。有人记得在这两年之前就有一些黑客使用这个词了。泡利在互联网领域有时被称作“网络妈妈”（NetMom）。

尽管英文单词worldwide通常被写为一个词（没有空格或者连字符），全称World Wide Web 和其简称WWW现在在一些正规的英文中也被广泛使用。最早的文献谈到万维网称其为WorldWideWeb（这正是一个编程序的人喜欢连词字，即把几个词连在一起成一个新词，的绝佳例子）或者World-Wide Web （加了连字符，这样这个版本的名字最接近正式的英语用法)。

有趣的是，“WWW”成为了少数音节比它的本来的名字更长的简称。在英语里，World Wide Web共三个音节，而单单一个W字母就有三个音节。

### 万维网的中文名称

1994年6月，北美的中国新闻电脑网络(China News Digest)，即CND，在其电子出版物《华夏文摘》上将 World Wide Web 称为“万维网”，这样其中文名称汉语拼音也是以 WWW 开始。万维网这一名称后来被广泛采用。

在台湾，“全球資訊網”这一名称则是比较直接的意译。

### 工作原理

当你想进入万维网上一个网页, 或者其他网络资源的时候，通常你要首先在你的浏览器上键入你想访问网页的统一资源定位符，或者通过超链接方式链接到那个网页或网络资源。这之后的工作首先是URL的服务器名部分被名为域名系统的分布于全球的因特网数据库解析并决定进入哪一个IP地址。

接下来的步骤是为所要访问的网页，向在那个IP地址工作的服务器发送一个HTTP请求。在通常情况下，HTML文本、图片和构成该网页的一切其他文件很快会被逐一请求并发送回用户。

网络浏览器接下来的工作是把HTML、[CSS]]和其他接受到的文件所描述的内容，加上图像、链接和其他必须的资源，显示给用户。这些就构成了你所看到的“网页”。

大多数的网页自身包含有超链接指向其他相关网页，可能还有下载、源文献、定义和其他网络资源。像这样通过超链接把有用的相关资源组织在一起的集合，就形成了一个所谓的信息的“网”。这个网在因特网上被方便使用，就构成了最早在1990年代初蒂姆·伯纳斯－李所说的万维网。[1] [2]。

### 起源

可以参考因特网

最早的网络构想可以追溯到遥远的1980年蒂姆·伯纳斯－李构建的ENQUIRE项目。这是一个类似维基百科的超文本在线编辑数据库。尽管这与我们现在使用的万维网大不相同，但是它们有许多相同的核心思想，甚至还包括一些伯纳斯－李的万维网之后的下一个项目语义网中的构想。

1989年3月，伯纳斯－李撰写了《关于信息化管理的建议》一文，文中提及 ENQUIRE 并且描述了一个更加精巧的管理模型。[3]1990年11月12日他和罗伯特·卡里奥（Robert Cailliau）合作提出了一个更加正式的关于万维网的建议。[4]。在1990年11月13日他在一台NeXT工作站上写了第一个网页以实现他文中的想法。[5]

在那年的圣诞假期，伯纳斯－李制作了要一个网络工作所必须的所有工具[6]：第一个万维网浏览器（同时也是编辑器）和第一个網頁伺服器。

1991年8月6日，他在alt.hypertext新闻组上贴了万维网项目简介帖子。这一天也标志着因特网上万维网公共服务的首次亮相。

万维网中至关重要的概念超文本起源于1960年代的几个从前的项目。譬如泰德·尼尔森（Ted Nelson）的仙那都项目（Project Xanadu）和道格拉斯·英格巴特（Douglas Engelbart）的NLS。而这两个项目的灵感都是来源于万尼瓦尔·布什在其1945年的论文《和我们想得一样》中为微缩胶片设计的“记忆延伸”（memex）系统。

蒂姆·伯纳斯－李的另一个才华横溢的突破是将超文本嫁接到因特网上。在他的书《编织网络》中，他解释说他曾一再向这两种技术的使用者们建议它们的结合是可行的，但是却没有任何人响应他的建议，他最后只好自己解决了这个计划。他发明了一个全球网络资源唯一认证的系统：統一資源標識符。

### 万维网和其他超文本系统有很多不同之处：

\* 万维网上需要单项连接而不是双向连接，这使得任何人可以在资源拥有者不作任何行动情况下链接该资源。和早期的网络系统相比，这一点对于减少实现网络服务器和网络浏览器的困难至关重要，但它的副作用是产生了坏链的慢性问题。
\* 万维网不像某些应用软件如HyperCard，它不是私有的，这使得服务器和客户端能够独立地发展和扩展，而不受许可限制。

1993年4月30日，歐洲核子研究組織宣布万维网对任何人免费开放，并不收取任何费用。两个月之后Gopher宣布不再免费，造成大量用户从Gopher转向万维网。

### 万维网标准

万维网的核心部分是由三个标准构成的：

\* 统一资源标识符（URI），这是一个世界通用的负责给万维网上例如网页这样的资源定位的系统。
\* 超文本传送协议(HTTP)，它负责规定浏览器和服务器怎样互相交流。
\* 超文本标记语言（HTML)，作用是定义超文本文档的结构和格式。

蒂姆·伯纳斯－李现在是万维网联盟(W3C)的领导人，这个组织的作用是使计算机能够在万维网上不同形式的信息间更有效的储存和通信。

### Java语言和JavaScript语言

万维网在技术上的另一个显著地进步是升阳公司的Java编程语言。它最初的作用是使得网络服务器可以在传给客户端的信息中直接嵌入叫applet的小程序，这些小程序可以直接在终端用户的计算机上使用，可以使用户交互更快更丰富。后来，Java语言逐渐发展成一种在服务器端生成复杂的即时内容的工具。

JavaScript是一种处理网页的脚本语言。其标准版本是ECMAScript，由网景通讯公司提交给欧洲标准协会制订。尽管它的名字和Java类似，但是它是由网景公司开发的而不是由升阳公司开发的，除了两者的语法都是从C语言发展而来这一点外，它们之间几乎没有什么关系。之所以叫JavaScript，只是当时Netscape公司希望能借助Java的名气推广它。和Java一样，Javascript类似C++是一种面向对象的语言，与Java不同但和C++相同的是它允许混合代码，即面向对象的和基于进程的代码可以同时存在。由于网页浏览器中，JavaScript与文档对象模型（Document Object Model）紧密结合，能够很好的处理网页，使得它比它的作者原本预期的要有用得多。它的用途可以用术语DHTML（动态HTML）表达，以强调它和静态HTML网页的区别。

### 社会影响

今天，万维网使得全世界的人们以史无前例的巨大规模相互交流。相距遥远的人们，甚至是不同年代的人们可以通过网络发展亲密的关系或者使彼此思想境界得到升华，甚至改变他们对待小事的态度以及精神。情感经历、政治观点、文化习惯、表达方式、商业建议、艺术、摄影、文学都可以以人类历史上从来没有过的低投入实现数据共享。尽管使用万维网仍然要依靠于存在自身缺陷的物化的工具，但至少它的信息保存方式不是使用人们熟悉的方式如图书馆、出版物那样实在的东西。因此信息传播是经由万维网和英特网来实现，而无须被搬运具体的书卷，或者手工的或实物的复制而限制。而且数字储存方式的优点是，你可以比查阅图书馆或者实在的书籍更容易有效率的查询网络上的信息资源。而且你可以比通过事必躬亲地去找，或通过邮件、电话、电报或者其他通讯方式来找，更加快速地获得信息。

万维网是人类历史上最深远，最广泛的传播媒介。它可以使它的用户可以和分散于这个行星上不同时空的其他人群相互联系，其人数远远超过通过具体接触或其他所有已经存在的通讯媒介的总和所能达到的数目。

由于万维网是全世界性的，有些人认为它将培养人们全球范围的相互理解。万维网可能培育人们的相互同情和合作，但是也有可能煽动全球范围的敌意，甚至给那些善于煽动人们偏激情绪的政客和压制人民的政权以人类历史上从未有过的强大力量。

### 发布网页

网络独立于大众传媒而被大家使用。如果你要发布一个网页，你不需要去拜访出版商或者任何其他传媒机构，而且你潜在的读者可能遍布于世界各地。

与传统书籍文献不同，超文本没有一个线性的顺序从头到尾。它不能分解成章，节，段等层次。

现在在万维网上可以寻找到不同种类的信息，你想了解其他的国家以及那里的风土人情变得十分容易。当你在外国或者一个偏僻的小镇旅游的时候，你可以通过网络找到关于这个地方的信息，尤其是如果是在一个发达国家的话。当地的报纸，官方出版物和其他资料都可以非常容易的找到，因此，花一样的努力你可以通过网络找到更多种类的相关资讯。

尽管有些站点有多种语言的版本，但是大部分站点只有当地语言版本。而且，不是所有的软件都能很好地支持所有的特殊字符和那些从右向左写的语言（如阿拉伯语或希伯来语）。这些因素使得关于万维网使得地球融为地球村的观点受到挑战。

随着大量的免费网络主页服务器的出现，涌现出了无数的个人主页以及家庭主页，小商店的主页等等，在网络上发布资料显而易见地越来越容易。

### 统计

据2001年一份研究[7]表明，互联网上有超过5500亿份文档，大多数文件在不可见的“深层网络”。2002年一份通过20亿2千4百万网页调查[8]表明至今大多数的网页内容是用英语写成的，为56.4%；之后是德语（7.7%），法语（5.6%）和日语（4.9%）。但是中文的站点也有很快的增长。一份最近的研究[9] 通过在75种语言的网络调查取样表明，到2005年1月为止，有超过115亿个网页在公共索引页面中。

### 速度问题

由于因特网的基础结构的缺陷造成的堵塞问题和显现为浏览速度的减慢的延迟经常让人很烦。结果是有人要给万维网改成 World Wide Wait（全球等）。利用點對點技術和服务质量来提高因特网的速度的讨论一直在进行。其他解决方案也可以在W3C的网站上找到。

### 学术会议

和WWW有关的主要学术会议为IW3C2. 发起的万维网系列会议。这是有关这一系列会议的链接

### 标准

以下是一些有关于万维网的一些标准：

\* 统一资源定位符(URL)
\*\*RFC 1738, URL Specification (updated by RFC 3986 "Uniform Resource Identifier (URI): Generic Syntax" in January 2005)
\* 超文本标志语言(HTML)
\*\*Internet Draft, HTML version 1
\*\*RFC 1866, HTML version 2.0
\*\*HTML 3.2 Reference Specification
\*\*HTML 4.01 Specification
\*\* Extensible HTML (XHTML) Specification
\* HyperText Transfer Protocol (HTTP)
\*\*RFC 2068, HTTP version 1.1
\*\*RFC 2616, HTTP version 1.1 (updated)
