---
title: "关于温州百科"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

### 温州信息化的现状

现在是信息化的社会，但是

* 政府、企事业单位等各类机构网站只有少数人维护，信息量少，更新慢
* 这些网站太多，信息分散，很难查找
* 很多信息还只停留在图书馆和档案馆里面，不能在网络上得到

这对温州本地的信息化进程带来不利的影响，也给外界了解温州带来了障碍。

### 什么是维基

维基(wiki)作为一种新型的互联网内容管理模式，是由“Wiki之父”沃德·坎宁安（Ward Cunningham）于1995年所创。它是一种可在网络上开放多人协同创作的超文本系统。该系统的特点包括：

* 能简易创造、改变HTML网页
* 记录以及编目所有的改变，并提供还原改变的功能

使用维基系统的网站称为维基网站，维基网站容许任何造访网站的人能快速轻易的加入、删除、编辑所有的内容，而且通常连登入都不必。维基系统也可以包括各种辅助工具，让使用者能轻易追踪维基的持续变化，或是让众使用者之间讨论解决关于维基内容的固有争议。

### 维基可以用来做什么

维基系统属于一种人类知识的网络系统，我们可以在Web的基础上对维基文本进行浏览、创建、更改，而且这种创建、更改及发布的代价远比HTML文本小；与此同时维基系统还支持那些面向社群的协作式写作，为协作式写作提供了必要的帮助；最后，维基的写作者自然构成了一个社群，维基系统为这个社群提供了简单的交流工具。与其它超文本系统相比，维基有使用简便且开放的特点，适合团队合作的写作方式，所以维基系统可以帮助我们在一个社群内共享某个领域的知识。成功的案例包括：

* 维基百科
* 台湾棒球维基馆 http://twbsball.dils.tku.edu.tw/
* 量子化学维基 http://wiki.quantumchemistry.net/
* 中文教学馆 http://chinese.wikia.com/

### 这项计划的出发点

我们的想法是把维基这种内容管理的形式应用到温州的信息化建设中去，做一个有关温州的百科全书，我们称其为“温州百科”。

“温州百科”是一个免费的开放的协作的关于温州的知识库建设计划。其目标及宗旨是为每一个温州人及关心温州的人提供一本百科全书——有关温州的知识的总和。内容涵盖：经济、交通、语言、文化、艺术、娱乐、旅游、饮食、服装、教育、体育、历史、地理、科技、农业、人物、企业等等温州相关各方面内容。不同于以往的网站的特点是，普通人不但可以浏览它，还可以参与它，任何人都可以对它进行补充、修改、完善。它带来的好处是：

* 可以为温州政府和各类企事业单位和团体提供一个信息集中发布的平台
* 可以为所有人提供一个了解温州的窗口
* 可以为温州人民的生活提供极大的方便
* 可以为所有人提供一个关于温州的讨论的平台
* 可以引导一种良好的精神文明氛围

### 如何鼓励大家参与

为了鼓励普通人参与到网站的编辑中来：

* 政府宣传，鼓励普通市民参与
* 规定政府机构必须在网站上发布内容
* 网站设立各种排行，对于达到一定要求的参与者给予一定的荣誉奖项，鼓励激励大家参与编辑
* 良性循环：浏览者多&lt;=促进=&gt;参与者多

### 网站的管理

虽然是所有人可以参与的网站，但是它同样需要管理。

* 首先是制定网站的方针政策，制定在网站上可以写什么、不可以写什么的规则，所有参与的人遵守规则对系统进行维护。
* 然后是对网站内容的日常维护，管理员要对每日创建、修改、删除的内容进行检查：
    * 如果有人进行破坏，恶意删除、篡改内容，管理人员可以对内容进行回退，对于恶意破坏的用户进行封锁。
    * 如果因事实不明、观点不同而发生争执，造成网页内容的摇摆不定时，管理人员可以对页面进行保护，等事实澄清后再开放进行编辑。
    * 如果有发现违反国家法律或者网站相关规定的内容时，管理员可以对其进行删除。

管理团队由核心团队和社区团队组成。

* 核心团队是由协会的专职人员担任，负责整个网站的规划、整个网站内容的控制以及对社区团队的管理。这个团队人数少，所以对内容进行管理的速度会比较慢。
* 社区团队在网站参与者中选出的志愿者构成，由核心团队委任，负责对网站某方面内容进行管理。这个团队人员数量多，对内容的响应速度快。
* 其他人也可以参与管理，但是没有直接的权限，可以将要求提请管理团队，在得到管理团队认可后由管理团队执行。

管理团队的大小，要看参与网站内容编辑的人员的数量以及每日增加、修改内容的数量，需要时可以进行扩充。

### 网站的内容策略

基本准则：

* 避免偏颇：任何内容都以中性的观点来写，公平地表述一个主题的不同观点。
* 不侵犯著作权
* 遵守礼仪，相互尊重

温州百科不是什么：

* 它不是发表个人思想或分析的地方（原创的研究、赞词或批评、个人论文、时事评论、论坛）
* 它不是演讲台、宣传工具或者广告场所，不是说服他人或拥护某方的场所。有关商业机构或产品的条目，应该以客观、无偏见的笔调撰写。网站本身不会支持任何个别商业机构，或结立任何宣传伙伴。
* 它不是战场，每个用户都应该以文明、冷静、抱持合作精神的态度，来与其它用户交流。

### 技术策略

参考其他维基网站架设的成功经验，硬件平台使用：

* 起始采用单一服务器架构
* 在网站规模扩大到一定程度时，考虑升级到集群架构

软件平台使用：

* 使用Linux作为操作系统平台
* 使用Apache作为web服务器
* 使用MySQL作为数据库服务器
* 使用mediawiki作为维基引擎
* 使用squid作为前置缓冲

该软件方案的特点是：

* 这些产品经过很多大型网站的实际检验，成熟稳定
* 产品开源免费，成本低，安全性好，同时保证产品的可延续性

### 计划的可行性

人员：

* 由计算机协会组织技术人员，组建一支管理队伍

本网站是非盈利性网站，资金主要靠以下渠道获得：

* 由政府投入的财力物力
* 由社会各界提供捐助
* 将网站内容编辑成书籍、刊物或光盘出版
* 出售网站相关纪念品

### 成果的形式

* 维基网站
* 一个维基参与人员组成的社群
* 书籍、刊物或者光盘出版

### 目标和进度

从启动资金投入时开始

* 2个月内完成起始管理队伍的组建
* 4个月内完成起始软硬件系统的架构和建设
* 2年内形成一个有一定规模的维基社群，同时组建出一支有效的管理团队
* 5年内使网站内容达到一定的规模，可以出版书籍、刊物或者光盘

在需要时进行：

* 当网站内容和用户数量达到一定规模时，进行软硬件系统的升级
* 当用户数量达到一定的规模时，需要对管理团队进行扩充。

### 其他问题

* 版权问题：在网站上的内容可以是属于公共领域的没有版权的资料，也可以是符合网站特定的版权说明的资料。对于有特定版权的资料，如果版权所有人自身愿意贡献出来，以符合网站规定的版权发布，那么这些资料也可以记录在网站上。对于其他不符合版权规定的资料，经管理员发现或者版权所有人指出，会主动从网站上删除。
* 安全的问题：除了管理员人工检查以外，还可以开启系统的自动语义和词汇过滤机制，公安信息安全机构的相关研究成果可以借用。
* 错误内容：维基的内容也可能有误，因为使用者必定会加上不正确的资料。所以浏览者对上面的资料不可100%全信，
