---
title: "操作系统历史"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000002 在备份中缺失；以下内容来自最新可读取版本 00000001。
:::

### 历史

各类平台上操作系统的功能演化综观电脑之历史，操作系统与电脑硬件的发展息息相关。操作系统之本意原为提供简单的工作排序能力，后为辅助更新更复杂的硬件设施而渐渐演化。从最早的批次模式开始，分时机制也随之出现，在多处理器时代来临时，操作系统也随之添加多处理器协调功能，甚至是分布式系统的协调功能。其他方面的演变也类似于此。另一方面，在个人电脑上，个人电脑之操作系统因袭大型电脑的成长之路，在硬件越来越复杂、强大时，也逐步实践以往只有大型电脑才有的功能。

总而言之，操作系统的历史就是一部解决电脑系统需求与问题的历史。

### 1980年代前

Maurice Vincent Wilkes，微程序的创建者
IBM System/360，大型主机的经典之作第一部电脑并没有操作系统。这是由于早期电脑的建立方式（如同建造机械算盘）与效能不足以执行如此程序。但在 1947年发明了晶体管，以及莫里斯·威尔克斯（Maurice V. Wilkes）发明的微程序方法，使得电脑不再是机械设备，而是电子产品。系统管理工具以及简化硬件操作流程的程序很快就出现了，且成为操作系统的滥觞。到了1960年代早期，商用电脑制造商制造了批次处理系统，此系统可将工作的建置、调度以及执行序列化。此时，厂商为每一台不同型号的电脑创造不同的操作系统，因此为某电脑而写的程序无法移植到其他电脑上执行，即使是同型号的电脑也不行。
到了1964年，IBM System/360推出了一系列用途与价位都不同的大型电脑，而它们都共享代号为OS/360的操作系统（而非每种产品都用量身订做的操作系统）。让单一操作系统适用于整个系列的产品是System/360成功的关键，且实际上IBM目前的大型系统便是此系统的后裔；为System/360所写的应用程序依然可以在现代的IBM机器上执行！
OS/360也包含另一个优点：永久贮存设备—硬盘驱动器的面世（IBM称为DASD（Direct access storage device））。另一个关键是分时概念的建立：将大型电脑珍贵的时间资源适当分配到所有使用者身上。分时也让使用者有独占整部机器的感觉；而 Multics的分时系统是此时众多新操作系统中实践此观念最成功的。
1963年，奇异公司与贝尔实验室合作以PL/I语言建立的Multics[1]，是激发1970年代众多操作系统建立的灵感来源，尤其是由 AT&T贝尔实验室的丹尼斯·里奇与肯·汤普逊所建立的Unix系统，为了实践平台移植能力，此操作系统在1969年由C语言重写；另一个广为市场采用的小型电脑操作系统是VMS。

### 80年代

第一代微型计算机并不像大型电脑或小型电脑，没有装设操作系统的需求或能力；它们只需要最基本的操作系统，通常这种操作系统都是从ROM读取的，此种程序被称为监视程序（Monitor）。1980年代，家用电脑开始普及。通常此时的电脑拥有8-bit处理器加上64KB内存、屏幕、键盘以及低音质喇叭。而80年代早期最著名的套装电脑为使用微处理器6510（6502芯片特别版）的Commodore C64。此电脑没有操作系统，而是以一8KB只读内存BIOS初始化彩色屏幕、键盘以及软驱和打印机。它可用8KB只读内存BASIC语言来直接操作 BIOS，并依此撰写程序，大部分是游戏。此BASIC语言的解释器勉强可算是此电脑的操作系统，当然就没有内核或软硬件保护机制了。此电脑上的游戏大多跳过BIOS层次，直接控制硬件。

* 家用电脑C64的抽象架构
* 简单应用程序 机器语言

（游戏直接操作）

* 8k BASIC ROM
* 8k ROM-BIOS
* 硬件（中央处理器、储存设备等）

早期最著名的磁盘启动型操作系统是CP/M，它支持许多早期的微电脑，且被MS-DOS大量抄袭其功能。最早期的IBM PC其架构类似C64。当然它们也使用了BIOS以初始化与抽象化硬件的操作，甚至也附了一个BASIC解释器！但是它的BASIC优于其他公司产品的原因在于他有可携性，并且兼容于任何符合IBM PC架构的机器上。这样的PC可利用Intel-8088处理器（16-bit寄存器）寻址，并最多可有1MB的内存，然而最初只有640KB。软式磁盘机取代了过去的磁带机，成为新一代的储存设备，并可在他512KB的空间上读写。为了支持更进一步的文件读写概念，磁盘操作系统（Disk Operating System，DOS）因而诞生。此操作系统可以合并任意数量的磁区，因此可以在一张磁盘片上放置任意数量与大小的文件。文件之间以档名区别。IBM并没有很在意其上的DOS，因此以向外部公司购买的方式取得操作系统。1980年微软公司利用骗术[2]取得了与IBM的合约，并且收购了一家公司出产的操作系统，在将之修改后以MS-DOS的名义出品，此操作系统可以直接让程序操作BIOS与文件系统。到了Intel-80286处理器的时代，才开始实作基本的储存设备保护措施。MS-DOS的架构并不足以满足所有需求，因为它同时只能执行最多一个程序（如果想要同时执进程式,只能使用TSR的方式来跳过 OS而由程序自行处理多任务的部份），且没有任何内存保护措施。对驱动程序的支持也不够完整，因此导致诸如音效设备必须由程序自行设置的状况，造成不兼容的情况所在多有。某些操作的效能也是可怕地糟糕。许多应用程序因此跳过MS-DOS的服务程序，而直接存取硬件设备以取得较好的效能。虽然如此，但MS- DOS还是变成了IBM PC上面最常用的操作系统（IBM自己也有推出DOS，称为IBM-DOS或PC-DOS）。MS-DOS的成功使得微软成为地球上最赚钱的公司之一。

* MS-DOS在个人电脑上的抽象架构
* 普通应用程序（Shell script、文本编辑器）
* MS-DOS（文件系统）
* BIOS（驱动程序）
* 硬件（中央处理器、储存设备等）

而1980年代另一个崛起的操作系统异数是Mac OS，此操作系统紧紧与麦金塔电脑捆绑在一起。此时一位全录伯拉图实验室的员工Dominik Hagen访问了苹果电脑的史蒂夫·乔布斯，并且向他展示了此时全录发展的图形化使用者界面。苹果电脑惊为天人，并打算向全录购买此技术，但因伯拉图实验室并非商业单位而是研究单位，因此全录回绝了这项买卖。在此之后苹果一致认为个人电脑的未来必定属于图形使用者界面，因此也开始发展自己的图形化操作系统。现今许多我们认为是基本要件的图形化接口技术与规则，都是由苹果电脑打下的基础（例如下拉式菜单、桌面图标、拖曳式操作与双点击等）。但正确来说，图形化使用者界面的确是全录创始的。

### 90年代

Apple I电脑，苹果电脑的第一代产品。延续1980年代的竞争，1990年代出现了许多影响未来个人电脑市场深厚的操作系统。由于图形化使用者界面日趋繁复，操作系统的能力也越来越复杂与巨大，因此强韧且具有弹性的操作系统就成了迫切的需求。此年代是许多套装类的个人电脑操作系统互相竞争的时代。
上一年代于市场崛起的苹果电脑，由于旧系统的设计不良，使得其后继发展不力，苹果电脑决定重新设计操作系统。经过许多失败的项目后，苹果于1997年释出新操作系统——MacOS的测试版，而后推出的正式版取得了巨大的成功。让原先失意离开苹果的Steve Jobs风光再现。
除了商业主流的操作系统外，从1980年代起在开放原码的世界中，BSD系统也发展了非常久的一段时间，但在1990年代由于与AT&T的法律争端，使得远在芬兰赫尔辛基大学的另一股开源操作系统——Linux兴起。Linux内核是一个标准POSIX内核，其血缘可算是Unix家族的一支。 Linux与BSD家族都搭配GNU计划所发展的应用程序，但是由于使用的许可证以及历史因素的作弄下，Linux取得了相当可观的开源操作系统市占率，而BSD则小得多。相较于MS-DOS的架构，Linux除了拥有傲人的可移植性（相较于Linux，MS-DOS只能运行在Intel CPU上），它也是一个分时多进程内核，以及良好的内存空间管理（普通的进程不能存取内核区域的内存）。想要存取任何非自己的内存空间的进程只能通过系统调用来达成。一般进程是处于使用者模式（User mode）底下，而执行系统调用时会被切换成内核模式（Kernel mode），所有的特殊指令只能在内核模式执行，此措施让内核可以完美管理系统内部与外部设备，并且拒绝无权限的进程提出的请求。因此理论上任何应用程序执行时的错误，都不可能让系统崩溃（Crash）。

#### 几乎完整的Linux架构图

* 使用者
* 模式 应用程序（sh、vi、OpenOffice.org等）
* 复杂函数库（KDE、glib 等）
* 简单函数库（opendbm、sin 等）
* C函数库（open、fopen、socket、exec、calloc 等）
* 内核
* 模式 系统中断、调用、错误等软硬件消息
* 内核（驱动程序、进程、网络、内存管理等）
* 硬件（处理器、内存、各种设备）

另一方面，微软对于更强力的操作系统呼声的回应便是Windows NT于1999年的面世。
1983年开始微软就想要为MS-DOS建构一个图形化的操作系统应用程序，称为Windows（有人说这是比尔盖兹被苹果的Lisa电脑上市所刺激）。一开始Windows并不是一个操作系统，只是一个应用程序，其背景还是纯MS-DOS系统，这是因为当时的BIOS设计以及MS-DOS的架构不甚良好之故。在1990年代初，微软与IBM的合作破裂，微软从OS/2（早期为命令行模式，后来成为一个很成功但是曲高和寡的图形化操作系统）项目中抽身，并且在1993年7月27日推出Windows 3.1，一个以OS/2为基础的图形化操作系统。并在1995年8月15日推出Windows 95。直到这时，Windows系统依然是建立在MS-DOS的基础上，因此消费者莫不期待微软在2000年所推出的Windows 2000上，因为它才算是第一个脱离MS-DOS基础的图形化操作系统。
下面的表格为Windows NT系统的架构：在硬件阶层之上，有一个由微内核直接接触的硬件抽象层（HAL），而不同的驱动程序以模块的形式挂载在内核上执行。因此微内核可以使用诸如输入输出、文件系统、网络、信息安全机制与虚拟内存等功能。而系统服务层提供所有统一规格的函数调用库，可以统一所有副系统的实作方法。例如尽管 POSIX与OS/2对于同一件服务的名称与调用方法差异甚大，它们一样可以无碍地实作于系统服务层上。在系统服务层之上的副系统，全都是使用者模式，因此可以避免使用者程序执行非法行动。
简化版本的Windows NT抽象架构
\*使用者
\*模式 OS/2
\*应用程序 Win32
\*应用程序 DOS
\*程序 Win16
\*应用程序 POSIX
\*应用程序
\*其他DLL函数库 DOS 系统 Windows 模拟系统
\*OS/2 副系统 Win32 副系统 POSIX.1 副系统
\*内核
\*模式 系统服务层
\*输入输出管理
\*文件系统、网络系统 对象管理系统 / 安全管理系统 / 进程管理 / 对象间通讯管理 / 进程间通讯管理 / 虚拟内存管理
\*微内核 窗口管理程序
\*驱动程序 硬件抽象层（HAL） 图形驱动
\*硬件（处理器、内存、外部设备等）
副系统架构第一个实作的副系统群当然是以前的微软系统。DOS副系统将每个DOS程序当成一进程执行，并以个别独立的MS-DOS虚拟机器承载其运行环境。另外一个是Windows 3.1模拟系统，实际上是在Win32副系统下执行Win16程序。因此达到了安全掌控为MS-DOS与早期Windows系统所撰写之旧版程序的能力。然而此架构只在Intel 80386处理器及后继机型上实作。且某些会直接读取硬件的程序，例如大部分的Win16游戏，就无法套用这套系统，因此很多早期游戏便无法在 Windows NT上执行。Windows NT有3.1、3.5、3.51与4.0版。Windows 2000是Windows NT的改进系列（事实上是Windows NT 5.0）、Windows XP（Windows NT 5.1）以及Windows Server 2003（Windows NT 5.2）与Windows Vista（Windows NT 6.0）也都是立基于Windows NT的架构上。
而本年代渐渐增长并越趋复杂的嵌入式设备市场也促使嵌入式操作系统的成长。

### 今日

现代操作系统通常都有一个使用的绘图设备的图形化使用者界面，并附加如鼠标或触控面版等有别于键盘的输入设备。旧的OS或效能导向的服务器通常不会有如此亲切的接口，而是以命令行接口（CLI）加上键盘为输入设备。以上两种接口其实都是所谓的壳，其功能为接受并处理使用者的指令（例如按下一按钮，或在命令提示列上键入指令）。
选择要安装的操作系统通常与其硬件架构有很大关系，只有Linux与BSD几乎可在所有硬件架构上执行，而Windows NT仅移植到了DEC Alpha与MIPS Magnum。在1990年代早期，个人电脑的选择就已被局限在Windows家族、类Unix家族以及Linux上，而以Linux及Mac OS X为最主要的另类选择，直至今日。
大型机与嵌入式系统使用很多样化的操作系统。大型主机近期有许多开始支持Java及Linux以便共享其他平台的资源。嵌入式系统近期百家争鸣,从给 Sensor Networks用的Berkeley Tiny OS到可以操作Microsoft Office的Windows CE都有。

#### 个人电脑

个人电脑市场目前分为两大阵营，此两种架构分别有支持的操作系统：
IBM兼容PC - 微软 Windows， Mac OS X，Unix 家族的OS以及Linux 家族。
Apple Macintosh - Mac OS （一个Unix分支OS，属 BSD 族系，Darwin），Windows （x86版本）， Linux 与 BSD

#### 大型电脑

最早的操作系统是针对20世纪60年代的大型主结构开发的，由于对这些系统在软件方面做了巨大投资，因此原来的计算机厂商继续开发与原来操作系统相兼容的硬件与操作系统。这些早期的操作系统是现代操作系统的先驱。现在仍被支持的大型主机操作系统包括：
Burroughs MCP-- B5000,1961 to Unisys Clearpath/MCP, present.
IBM OS/360 -- IBM System/360, 1964 to IBM zSeries, present
UNIVAC EXEC 8 -- UNIVAC 1108, 1964, to Unisys Clearpath IX, present.
现代的大型主机一般也可运行Linux或Unix变种。

#### 嵌入式系统

嵌入式系统使用非常广泛的操作系统（如VxWorks、eCos、Symbian OS及Palm OS）以及某些功能缩减版本的Linux或者其他操作系统。某些情况下，OS指称的是一个内置了固定应用软件的巨大泛用程序。在许多最简单的嵌入式系统中，所谓的OS就是指其上唯一的应用程序。

#### 类Unix系统

一个在Linux底下执行的客制化KDE桌面系统所谓的类Unix家族指的是一族种类繁多的OS，此族包含了System V、BSD与Linux。由于Unix是The Open Group的注册商标，特指遵守此公司定义的行为的操作系统。而类Unix通常指的是比原先的Unix包含更多特征的OS。
Unix系统可在非常多的处理器架构下执行，在服务器系统上有很高的使用率，例如大专院校或工程应用的工作站。自由软件Unix变种，例如Linux与BSD近来越来越受欢迎，它们也在个人桌面电脑市场上大有斩获，例如Ubuntu系统，但大部分都是电脑高手在使用。
某些Unix变种，例如HP的HP-UX以及IBM的AIX仅设计用于自家的硬件产品上，而SUN的Solaris可安装于自家的硬件或x86电脑上。苹果电脑的Mac OS X是一个从NeXTSTEP、Mach以及FreeBSD共同派生出来的微内核BSD系统，此OS取代了苹果电脑早期非Unix家族的Mac OS。经历数年的披荆斩棘，自由开源的Unix系统逐渐蚕食鲸吞以往专利软件的专业领域，例如以往电脑动画运算巨擘──SGI的IRIX系统已被 Linux家族及Plan 9[3]丛集所取代。

#### 微软Windows

Microsoft Windows 系列操作系统是在微软给IBM机器设计的MS-DOS的基础上设计的图形操作系统。现在的Windows系统，如Windows 2000、Windows XP皆是建立于现代的Windows NT内核。NT内核是由OS/2和OpenVMS等系统上借用来的。Windows 可以在32位和64位的Intel和AMD的处理器上运行，但是早期的版本也可以在DEC Alpha、MIPS与PowerPC架构上运行。虽然由于人们对于开放源代码作业系统兴趣的提升，Windows的市场占有率有所下降，但是到2004年为止，Windows操作系统在世界范围内占据了桌面操作系统90%的市场。[4]
Windows系统也被用在低阶和中阶服务器上，并且支持网页服务的数据库服务等一些功能。最近微软花费了很大研究与开发的经费用于使Windows拥有能运行企业的大型程序的能力。
WindowsXP在2001年10月25日发布，2004年8月24日发布最新的升级包WindowsXP Service Pack 2。微软最新的操作系统 Windows Vista（开发代码为Longhorn）于2007年1月30日发售[5]。Windwos Vista增加了许多功能，尤其是系统的安全性和网络管理功能。Windows Vista拥有界面华丽的Aero Glass。

#### 苹果Mac OS

苹果Mac OS系列操作系统是苹果公司 (原称苹果电脑)给苹果个人电脑系列设计的OS。

#### 其他

大型主机以及嵌入式操作系统均与Unix或Windows家族关系不大，除了Windows CE、Windows NT Embedded 4.0及Windows XP Embedded是Windows的血亲产品，以及数种\*BSD和嵌入式Linux包为例外。
少数较旧的OS今日依然在一些需要稳定性的市场中活跃，例如IBM的OS/2[6]BeOS以及XTS-400。
在达康时代狂潮过后，如AmigaOS与RISC OS等少数人使用的OS依然持续建立，以满足狂热的爱好者社群与特殊专业使用者。

### 未来

研究与建立未来的操作系统依旧进行著。操作系统朝提供更省电、网络化、华丽的使用者界面的方向来改进。Linux及一些类UNIX OS正努力让自己成为个人用户舒适的环境。GNU Hurd是一个企图完全兼容Unix并加强许多功能的微内核架构。微软Singularity是一个奠基于.Net并以建立较佳内存保护机制为目目标研究计划。
