---
title: "机器语言"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000002 在备份中缺失；以下内容来自最新可读取版本 00000001。
:::

### 机器语言

英  文：  Machine Language

别  名：  低级[语言](<语言历史.qmd>)，二进制代码[语言](<语言历史.qmd>)

### 定  义：

机器语言是直接用二进制代码指令表达的计算机语言，指令是用0和1组成的一串代码，它们有一定的位数，并分成若干段，各段的编码表示不同的含义，例如某台计算机字长为16位，即有 16个二进制数组成一条指令或其它信息。16个0和1可组成各种排列组合，通过线路变成电信号，让计算机执行各种不同的操作。

如某种计算机的指令为1011011000000000，它表示让计算机进行一次加法操作；而指令1011010100000000则表示进行一次减法操作。它们的前八位表示操作码，而后八位表示地址码。从上面两条指令可以看出，它们只是在操作码中从左边第0位算起的第6和第7位不同。这种机型可包含256（=2的8次方）个不同的指令。<br>
机器语言即是机器指令的集合。每种计算机都有自己的指令集合，计算机能直接执行用机器语言所编的程序。机器语言包括：指令系统、数的形式、通道指令、中断字、屏蔽字、控制寄存器的信息等。机器码是计算机能理解和执行的唯一语言。机种不同，其机器码组合方式也不一样。同一个题目到不同的计算机上计算时，必须编写不同机器语言的程序。机器语言是最低级的语言。

### 特  点：

机器语言或称为二进制代码语言，计算机可以直接识别，不需要进行任何翻译。每台机器的指令，其格式和代码所代表的含义都是硬性规定的，故称之为面向机器的语言，也称为机器语言。它是第一代的计算机语言。机器语言对不同型号的计算机来说一般是不同的。

### 缺  点：

* 1.大量繁杂琐碎的细节牵制着程序员，使他们不可能有更多的时间和精力去从事创造性的劳动，执行对他们来说更为重要的任务。如确保程序的正确性、高效性。

* 2.程序员既要驾驭程序设计的全局又要深入每一个局部直到实现的细节，即使智力超群的程序员也常常会顾此失彼，屡出差错，因而所编出的程序可靠性差，且开发周期长。

* 3.由于用机器语言进行程序设计的思维和表达方式与人们的习惯大相径庭，只有经过较长时间职业训练的程序员才能胜任，使得程序设计曲高和寡。

* 4.因为它的书面形式全是"密"码，所以可读性差，不便于交流与合作。

* 5.因为它严重地依赖于具体的计算机，所以可移植性差，重用性差。

这些弊端造成当时的计算机应用未能迅速得到推广

总之，由于机器码指令是用许多二进制数表示的，用机器语言编程必然很繁琐，非常消耗精力和时间，难记忆，易弄错，并且难以检查程序和调试程序，工作效率低。因此，现在一般不使用机器语言。
