---
title: "网络电视地址"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000011 在备份中缺失；以下内容来自最新可读取版本 00000010。
:::

## 中央台

* CCTV-1 综合频道(450k) mms://live1.cnnb.com.cn/startv
* CCTV-1 综合频道(500k) mms://61.155.44.132/cctv1
* CCTV-1 新闻频道 mms://live.cctv.com/live1
* CCTV新闻（128k) mms://winmedia.cctv.com.cn/live1
* CCTV新闻（500k) mms://live1.cnnb.com.cn/channelv
* CCTV2(450k) mms://61.155.44.132/cctv2
* CCTV2 mms://winmedia.cctv.com.cn/live2
* CCTV-4 国际频道 mms://220.175.6.130/TV21/
* CCTV4(128k) mms://winmedia.cctv.com.cn/live
* CCTV4 mms://live.cctv.com/live
* CCTV-5 体育频道 mms://220.189.220.87/cctv5
* CCTV-5 体育频道 rtsp://cctv5.tzinfo.net/cctv
* CCTV-5 体育频道 mms://cctv5.tzinfo.net/cctv
* CCTV-7 军农少频道 rtsp://218.22.10.163/broadCast/cctv7
* CCTV8 mms://218.69.107.40//湖南卫视/live
* CCTV-9 英语频道（1） mms://live.cctv.com/live3
* CCTV-9 英语频道（2） mms://winmedia.cctv.com.cn/live3

## 浙江

* 宁波都市文化 mms://vod1.nbtv.com.cn/nbtv3
* 宁波经济频道 mms://vod1.nbtv.com.cn/nbtv2
* 宁波影视频道 mms://vod1.nbtv.com.cn/nbtv4
* 金华新闻综合 mms://61.153.35.38/PublishingPoint1
* 温州新闻综合 mms://202.107.219.58/wztv1
* 温州经济生活 mms://202.107.219.58/wztv2
* 浙江公共电视 mms://ztv7.zrtg.com:1095/
* 浙江卫星电视 mms://video3.zjol.com.cn/ztv
* 浙江教育科技 mms://218.108.49.123:3340/
* 浙江少儿频道 mms://61.175.162.21/ztv8
* 浙江影视娱乐 mms://61.175.162.22/ztv5
* 丽水一台 mms://202.96.114.251/lstv
* 丽水二台 mms://202.96.114.251/lstv2

## 广东

* 广州美在花城 mms://219.136.240.2/beauty
* 广州短剧频道 mms://219.136.240.2/gzdj
* 珠海综合频道 mms://www.zhtv.com/airshow
* 潮州新闻综合 mms://219.131.159.153/cztv1
* 潮州公共频道 mms://219.131.159.152/cztv2
* 炫动卡通卫视 http://202.109.80.136/channel15
* 珠海电视 mms://www.zhtv.com/airshow

## 山西陕西

* 山西卫星电视 rtsp://218.26.3.81/encoder/SHANXITV_1.rm
* 山西新闻综合 rtsp://218.26.3.80/encoder/SHANXITV_3.rm
* 山西都市频道 rtsp://218.26.3.81/encoder/SHANXITV_2.rm
* 山西影视频道 rtsp://218.26.3.80/encoder/SHANXITV_4.rm
* 西安白鸽都市 mmst://live2.xatvs.com/Station1
* 西安新闻综合 mmst://live1.xatvs.com/Station1
* 陕西新闻综合 mms://Vod.sxtvs.com/live4
* 陕西都市青春(1) mms://Vod.sxtvs.com/live1
* 陕西都市青春(2) mms://Vod.sxtvs.com/live3
* 安康综合频道 mms://61.150.111.204/news

## 湖北成都

* 湖北卫视 mms://219.140.163.36/zbws
* 荆州新闻综合 rtsp://61.232.208.50/broadcast/xinwen/xinwen.rm
* 荆州精彩频道 rtsp://61.232.208.50/broadcast/jingcai/jingcai.rm
* 荆州公共频道 rtsp://61.232.208.50/broadcast/gonggong/gonggong.rm
* 成都综合频道 rtsp://vod.chengdutv.com/encoder/live.rm

## 海南

* 海南旅游卫视 mms://218.77.178.156/LIVECAM1
* 海南新闻综合 mms://218.77.178.156/LIVECAM2
* 海南影视娱乐 mms://218.77.178.158/LIVECAM4
* 海南公共频道 mms://218.77.178.158/LIVECAM6
* 海南少儿频道 mms://218.77.178.158/LIVECAM7

## 江苏

* 无锡都市资讯 rtsp://v.thmz.com/tv-2
* 无锡综合频道 rtsp://v.thmz.com/tv-1
* 徐州公共频道 mms://218.3.205.10/徐州广播电视网_公共频道
* 徐州新闻频道 mms://218.3.205.10/徐州广播电视网_新闻综合
* 徐州经济生活 mms://218.3.205.10/徐州广播电视网_经济生活
* 徐州文化影视 mms://218.3.205.10/徐州广播电视网_文艺影视
* 常州新闻频道 mms://vod1.cztv.tv/cztv1
* 常州都市频道 mms://vod1.cztv.tv/cztv2
* 常州影视频道 mms://vod1.cztv.tv/cztv3
* 常州公共 rtsp://vod1.cztv.tv/cztv4
* 江苏影视频道 mms://vod.jsgd.com.cn/jsys.jsgd
* 江苏城市频道 mms://vod.jsgd.com.cn/city.jsgd
* 江苏综艺频道 mms://vod.jsgd.com.cn/video1.jsgd
* 江苏靓装频道 mms://vod.jsgd.com.cn/lzpd
* 江苏南京文体频道 rtsp://live.njbg.com.cn/broadcast/O3.rm
* 江苏卫星电视 mms://vod.jsgd.com.cn/jsws.jsgd
* 江苏少儿频道 mms://vod.jsgd.com.cn/jsse.jsgd
* 江苏国际频道 mms://vod.jsgd.com.cn/jsgj.jsgd

## 天津

* 天津影视频道 mms://221.238.193.6/tj3
* 天津文化娱乐 mms://221.238.193.6/tj2
* 天津少儿频道 mms://221.238.193.6/tj7
* 天津经济生活 mms://221.238.193.6/tj1
* 天津卫视频道 mms://221.238.193.6/tj8
* 天津卫视频道 mms://221.238.193.6/tj6
* 天津都市频道 mms://221.238.193.6/tj4
* 天津体育频道 mms://221.238.193.6/tj5
* 盘山新闻综合频道 mms://219.149.86.98:8888

## 安徽

* 安徽卫视 mms://218.22.14.85/live1
* 安徽经济生活 mms://218.22.14.85/live2
* 淮南综合频道 mms://202.102.208.42/live1
* 淮南第二频道 mms://202.102.208.42/live2
* 淮南第三频道 mms://202.102.208.42/live3

## 江西

* 江西导视频道 mms://movie.jxgdw.com/tvzn
* 江西公共频道 rtsp://movie.jxgdw.com/jswjxtv5
* 江西影视频道 rtsp://movie.jxgdw.com/jswjxtv4
* 江西卫星频道 mms://movie.jxgdw.com/jswjxgdwjxtv
* 江西经济频道 mms://220.175.6.130/TV40/
* 江西都市频道 mms://220.175.6.130/TV41/
* 江西教育频道 mms://movie.jxgdw.com/jxjy
* 鹰潭新闻综合 mms://movie.ytgdw.com/ytgd/yttv/xwzh

## 云南

* 玉溪公共频道 rtsp://v2.yxtv.cn/encoder/yxtv-21.rm
* 玉溪综合频道 rtsp://v2.yxtv.cn/encoder/yxtv-11.rm

## 山东

* 山东齐鲁频道 http://202.102.188.43/qltv
* 山东公共频道 http://202.102.188.43/ggtv
* 山东综合频道 http://202.102.188.43/zhtv
* 山东体育频道 http://202.102.188.43/zhtv
* 山东公共 http://202.102.188.43/ggtv
* 山东新综 http://202.102.188.43/zhtv

## 上海

* 上海东方音乐(368k) mms://218.19.175.167:1755/stv4
* 上海东方卫视(368k) mms://218.19.175.167:1755/stv
* 上海文艺频道(368k) mms://218.19.175.167:1755/stv5
* 上海新闻娱乐(368k) mms://218.19.175.167:1755/stv7
* 上海新闻综合(368k) mms://218.19.175.167:1755/stv1
* 上海生活时尚(368k) rtsp://218.15.56.101:1755/stv6
* 上海第一财经(368k) mms://218.19.175.167:1755/stv2
* 上海电视剧(368k) mms://218.15.56.101:1755/stv8
* 上海体育频道(368k) mms://218.19.175.167:1755/stv3

## 郑州

* 郑州电视一台 rtsp://219.150.142.5/zztv1
* 郑州电视二台 rtsp://219.150.142.5/zztv2
* 郑州电视三台 rtsp://219.150.142.5/zztv3
* 郑州电视四台 rtsp://219.150.142.5/zztv4

## 其他地方

* 湖南卫视频道 mms://218.69.107.40//cctv2/live
* 广西卫视 mms://mov11.n169.com/广西-20051209
* 陕西体育健康频道 mms://Vod.sxtvs.com/live2
* 河南南阳电视 mms://61.136.113.41/nytv_1
* 重庆卫星频道 mms://218.201.44.232/ccqtv
* 厦门海峡卫视 mms://218.5.65.171/hx

## 香港

* 星空卫视(1)mms://220.170.199.249/xk
* 星空卫视(2)mms://222.47.122.127/litv06
* 星空卫视(网通1）mms://218.69.107.40//星空卫视/live
* 星空卫视(网通2）mms://218.69.107.45/星空卫视/live
* 凤凰卫视中文台（1） mms://222.47.122.127/litv01
* 凤凰卫视中文台（2） mmst://219.151.3.10/channelv
* 凤凰卫视中文台（3） mms://218.67.245.10/凤凰中文/live
* 凤凰咨询台（1） mms://222.77.180.5:554/Lchinavnet_phzb01
* 凤凰咨询台（2） mms://218.30.119.102:554/Lchinavnet_phzb01
* 凤凰咨询台（3） mms://218.1.69.165:554/Lchinavnet_phzb01
* 大爱电视台(300k) mms://210.59.147.3/wmtencoder/300k.wmv
* 阳光卫视 rtsp://222.47.122.127/litv04
* 游戏玩家频道（450k)mms://220.130.8.253:8080
* 中华电视台(300k) mms://vod1.cts.com.tw/Cts100
* 佛卫慈悲台(100k) mms://61.222.239.122:1140
* 好消息卫视(120k) mms://mark.goodtv.com.tw/NLive
* 交通电视台(141) mms://video.ftv.com.tw/fmtv
* V音乐台(1) mms://218.69.107.40/卫视电影/live
* V音乐台(2) mms://222.47.122.127/litv02
* 美亚电影 mms://live1.cnnb.com.cn/meiya
* 原住民电视 mms://4.19.71.132/itv-200
* 年代购物台 mms://203.69.41.22/rose
* 富邦购物台 http://203.69.41.24/momo

## 体育

* 上海体育频道(1) mms://218.19.175.167:1755/stv3
* 上海体育频道(2) rtsp://218.15.56.101:1755/stv3
* CCTV5(1)星空转播 mms://cctv5.tzinfo.net/cctv
* CCTV5 (2) mms://60.18.129.179/live2
* 卫视体育频道(1) rtsp://222.47.122.127/litv08
* 上海东方卫视(512k) http://218.19.175.165:80/4_VNET_stv
* 天津体育频道(450k) mms://221.238.193.6/tj5
* 江苏体育频道(450k) mms://vod.jsgd.com.cn/jsty.jsgd
* 宁波文体频道(450) mms://live1.cnnb.com.cn/nbtv3
* C N 8体育频道 mms://68.87.109.4/cn8winmedia
* 湖北体育频道 mms://219.140.163.36/zbty
* 足球频道(1) mms://219.136.254.119/350a
* 足球频道(2) mms://winmedia.cctv.com.cn/live1

## 音乐影视

* 音乐现场频道 mms://218.1.70.8:1755/XinLiRenSheng
* 音乐无限频道 mms://218.1.70.8:1755/YinYueWuXian
* 上海电视剧台 mms://218.15.56.101:1755/stv8
* 徐州影视频道 mms://218.3.205.10/徐州广播电视网_文艺影视
* 江苏影视频道 mms://vod.jsgd.com.cn/jsys.jsgd
* 浙江影视频道 mms://61.175.162.21/ztv5
* 江苏综艺频道 mms://vod.jsgd.com.cn/video1.jsgd
* 常州影视频道 mms://vod1.cztv.tv/cztv3
* 江西影视频道 mms://218.64.55.171/jswjxtv4
* 天津影视频道 mms://211.148.164.152/tj3
* 娱乐快递频道 mms://218.1.70.200/YuLeKuaiDi
* 网络电影频道(1) mms://livemms.online2.sh.cn/JingPinYingYuan
* 网络电影频道(2)mms://61.185.209.254:1755/station1
* CCTV影院频道 mms://218.1.70.72:1755/OnIndexPage
* 海南影视娱乐 mms://218.77.178.158/LIVECAM4
* 宁波影视频道 mms://vod1.nbtv.com.cn/nbtv4
* 南京影视 rtsp://live.njbg.com.cn/broadcast/O2.rm
* 互联星空MTV mms://218.30.64.14/live

## 国外

* WMTV mms://146.101.200.150/WAMTV
* 美国CN8 mms://68.87.109.4/cn8winmedia
* 英国BBC mms://mplay.donga.com/bbc
* ABC mms://mplay.donga.com/abc
* BBC国际新闻 mms://mplay.donga.com/bbc
* 泰星UBC（体育） mms://61.90.149.194/ubcsport/
* 韩国TBC频道 mms://203.251.80.184/tbc_tv
* 韩国MBC频道 mms://live.wjmbc.co.kr/wjmbctv
* 小日本LFX频道 mms://bbn-lf.stream.ne.jp/lfx2
* 韩国购物频道 mms://61.78.39.245/encoder1
* 韩国阿里郎台 mms://211.43.217.85/world2_live
* 美国街景实拍 mms://216.242.118.141/broadband/broadband
* 韩国EBSE频道 mmst://219.240.37.11/L-ST2_300k
* 韩国购物二台 mmst://media.woori.com/live300
* 拉脱维亚TV5 http://stream.grafton.lv/live_tv5
* 亚洲电视台mmst://211.233.84.172/262-300
* 泰国游戏频道 http://203.170.198.56/webcast_game
* 西班牙土方台 mms://212.22.34.30/tvcyl_tvsa
* ABC亚太频道 mms://210.115.150.11/abc
* 美国音乐频道 mms://stream.nwez.net/nwez3
* 泰国nation rtsp://61.90.149.195/nationchannel
* 印度新闻频道 http://164.100.51.209/DDLive
* 马耳他TVM频道 http://winmedia.di-ve.com/TVM
* 德国Kitz TV mms://217.14.230.62/kitztv
* 纽约WHOH台 http://whoh-tv.org/whoh.wvx
* 捷克CeskaTV mms://stream3a.visual.cz/CT24-High

## 网通用户地址

* 星空卫视 mms://218.67.245.12/星空卫视24/live
* 凤凰咨询频道 mms://218.69.107.40//凤凰咨询/live
* 中天娱乐频道 mms://218.69.107.40//vod1-/live
* HBO电影频道 mms://218.69.107.40//HBO/live
* 凤凰中文频道 mms://218.67.245.10/凤凰中文/live
* 华娱卫视频道 mms://218.67.245.5/阳光卫视/live
* 卫视电影频道 mms://218.67.245.10/中央二/live
* CCTV体育频道 mms://218.69.107.40//中央五/live
* CCTV体育频道 mms://218.67.245.10/中央五/live
* 青岛电视频道 mms://down.qingdaomedia.com/qtv
* 东风卫视频道 mms://218.69.107.40//东风卫视/live
* 星空体育频道 mms://218.69.107.45/星空体育/live
* 中央八套频道 mms://218.67.245.13/湖南卫视22/live
* 新知台频道 mms://218.67.245.13/美亚电影22/live
* 星空卫视频道 mms://218.69.107.45/星空卫视/live
* V音乐频道 mms://218.69.107.40//卫视电影/live
* 湖南卫视频道 mms://218.69.107.40//cctv2/live
* 凤凰咨询频道 mms://218.67.245.13/凤凰咨询22/live
* 山东卫视 http://202.102.188.43/sdtv
* 齐鲁电视 http://202.102.188.43/qltv
* 山东公共电视 http://202.102.188.43/ggtv
* 山东网络综合 http://202.102.188.43/zhtv
* 长春电视台 mms://61.138.179.3:8080/zxmm
* 安阳一套 mms://61.54.222.33/video2
* 安阳三套 mms://61.54.222.33/video1

### 广播地址

#### 北京丶上海丶天津丶重庆

mms://202.108.248.145/am603 北京电台首都生活
mms://202.108.248.145/fm974 北京电台音乐广播
mms://202.108.248.145/am774 北京电台外语广播
mms://202.108.248.145/fm1006 北京电台新闻广播
mms://202.108.248.145/am927 北京电台体育广播
mms://202.108.248.145/fm1039 北京电台交通广播
mms://202.108.248.145/fm1073 北京电台经济广播
mms://listen1.bjradio.com.cn/cfm986 北京电台古典音乐
mms://alive.bjradio.com.cn/fm1073 北京电台城市管理
mms://listen1.bjradio.com.cn/cfm1043 北京电台文学影视
mms://listen1.bjradio.com.cn/cfm970 北京电台通俗音乐
mms://listen1.bjradio.com.cn/cfm994 北京电台北京教学
mms://alive.bjradio.com.cn/fm876 北京电台文艺广播
mms://listen1.bjradio.com.cn/cfm1051 北京电台戏曲曲艺
mms://listen1.bjradio.com.cn/cfm1065 北京电台亚洲流行
mms://listen1.bjradio.com.cn/cfm1075 北京电台轻音乐
mms://listen1.bjradio.com.cn/DAB 北京电台 DAB广播
http://www.stv.sh.cn/classic.asx 上海人民广播电台经典947
http://www.stv.sh.cn/103.asx 上海人民广播电台魅力音乐103
http://www.stv.sh.cn/990.asx 上海人民广播电台新闻频率
http://www.stv.sh.cn/648.asx 上海人民广播电台交通频率
http://www.stv.sh.cn/1045.asx 上海人民广播电台东广新闻
http://www.stv.sh.cn/792.asx 上海人民广播电台都市792
http://www.stv.sh.cn/popmusic.asx 上海人民广播电台动感101
http://www.stv.sh.cn/977.asx 上海人民广播电台第一财经
http://www.stv.sh.cn/977.asx 上海人民广播电台开心调频
http://www.stv.sh.cn/1197.asx 上海人民广播电台海上戏剧
mms://218.1.74.225/940 上海人民广播电台体育频率
mms://61.136.19.228/live1 天津广播电台新闻频道
mms://61.136.19.228/live2 天津广播电台音乐频道
mms://61.136.19.228/live3 天津广播电台经济频道
mms://61.136.19.228/live4 天津广播电台文艺频道
mms://61.136.19.228/live5 天津广播电台交通频道
mms://61.136.19.228/live6 天津广播电台生活频道
mms://61.136.19.228/live7 天津广播电台滨海频道
mms://61.136.19.228/live9 天津广播电台古典音乐频道
mms://211.158.10.48/fm881 重庆音乐广播电台

#### 香港丶台湾丶澳门

mms://210.59.227.130/heart32k 台北真心之音电台
mms://202.177.192.108/radio5 香港电台第5台
mms://202.177.192.108/radio2 香港电台第2台
mms://202.177.192.108/radio1 香港电台第1台
mms://202.177.192.108/radio3 香港电台第3台（英语）
mms://202.177.192.108/radio4 香港电台第4台（英语）
rtsp://www.am873.net/encoder/news 海峡之声新闻时政频道
http://metromedia.104metrofinance.com/LiveAM1044 新城采讯台（英语）
mms://203.129.68.232/fmselect 新城财经台104
mms://203.129.68.232/hit997 新城娱乐台
mms://202.177.192.223/cr1 香港商业电台一台雷霆881
mms://202.177.192.223/cr2 香港商业电台二台叱咤903
mms://203.187.31.160/khkiss KISSRADIO
mms://203.187.31.160/fm917 台北之音音乐电台
mms://203.187.31.160/fm1077 台北之音都会台
mms://media.family977.com.tw/live 台湾好家庭电台
mms://61.218.197.178:8080 台湾云嘉广播电台
mms://media.iwant-in.net/pop 台湾银河流行音乐台
mms://61.220.226.218:8080 台湾桃园广播电台
mms://61.221.98.46:8080 台湾省都广播电台
mms://203.71.144.133:8080 教育广播-台东台
mms://203.71.142.50:1029 教育广播-高雄台
mms://220.132.146.146:8080 新竹劳工之声客家电台
mms://202.175.80.10/liveaudio 澳门电台

#### 广东丶广西丶福建

mms://210.53.201.134:8080 新会电台(广东江门)
mms://211.156.183.154:8080/radio 江门电台
mms://61.145.112.81/fm914 广东卫星广播电台
mms://211.96.13.249/pub 花都广播电台
mms://221.4.151.102:1427 高明电台
mms://fm1047.heshan.net/fm1047 江门鹤山电台
mms://210.53.200.4/tsradio 台山人民广播电台
mms://www.gdsgbc.com/live_sg 韶关人广普通话频道
mms://www.gdsgbc.com/live_bj 韶关人广广州话频道
mms://61.131.4.158/fm913_128k 福建电台音乐广播
rtsp://218.16.123.9/broadcast/blivefm936 广东电台南方生活广播

#### 浙江丶江苏

mms://video3.zjol.com.cn/am810 浙江人广新闻综合频道
mms://video3.zjol.com.cn/fm95 浙江经济台
mms://video3.zjol.com.cn/voc107/voc107.asx 浙江城市之声
mms://218.108.20.172/audio_live1 杭州新闻综合
mms://218.108.20.172/audio_live2 杭州西湖之声广播电台
mms://218.108.20.172/audio_live3 杭州经济之声广播电台
mms://218.108.20.172/audio_fm89 杭州广播电台fm89
mms://222.46.65.21/live 温州人广新闻综合
mms://222.46.65.22/live 温州人广经济交通
mms://222.46.65.23/live 温州人广音乐之声
mms://av.zhoushan.cn/Radio 舟山人民广播电台
mms://210.22.209.202/1 镇江人民广播电台994新闻综合频率
mms://211.140.147.252/1 金华新闻综合
mms://211.140.147.252/2 金华经济频道
mms://211.140.147.252/3 金华交通音乐
mms://media.hz66.com/diantai 湖州人民广播
mms://61.155.11.22/njyyt 南京音乐频道
mms://online.njbs.com.cn/njjtt 南京交通台
mms://online.njbs.com.cn/njxwt 南京新闻台
mms://online.njbs.com.cn/njjjt2 南京体育台
mms://online.njbs.com.cn/njjjt1 南京经济台
mms://vod.jsgd.com.cn/audio1.jsgd 江苏人民广播电台综合频率
mms://vod.jsgd.com.cn/audio4.jsgd 江苏人民广播电台音乐频率
mms://vod.jsgd.com.cn/audio3.jsgd 江苏人民广播电台文艺频率
mms://vod.jsgd.com.cn/audio2.jsgd 江苏人民广播电台经济频率
mms://vod.jsgd.com.cn/audio6.jsgd 江苏人民广播电台金陵之声

#### 云南丶湖南丶湖北

mms://220.163.44.116:8080 云南音乐台
mms://www.radiokm.com/live1 昆明人民广播电台阳光调频
mms://www.radiokm.com/live2 昆明人民广播电台都市调频
mms://video.rednet.com.cn/918 湖南人民广播电台交通频道
mms://video.rednet.com.cn/975 湖南人民广播电台文艺频道
mms://video.rednet.com.cn/1032 湖南人民广播电台新闻频道
mms://video.rednet.com.cn/1061 长沙人民广播电台音乐频道
mms://media.csonline.com.cn/fm105 长沙人民广播电台星沙之声
mms://220.202.29.39:8280 宜昌人民广播电台新闻台
mms://220.202.29.39:8180 宜昌人民广播电台交通台
mms://220.202.29.39:8380 宜昌人民广播电台都市台
mms://219.138.45.181/jiaotong 襄樊交通音乐频率
mms://219.138.45.181/xinwen 襄樊新闻频率
mms://219.138.45.181/wenyi 襄樊文艺频率
mms://218.200.149.203/fm 黄石交通音乐台
mms://listen.sycatv.net:8080/.asf 十堰音乐

#### 陕西丶河南丶河北

mms://61.185.214.171/fm931 西安音乐
mms://219.144.240.171/audio1 陕西人广新闻综合台
mms://219.144.240.171/audio2 陕西人民广播文艺台
mms://219.144.240.171/audio4 陕西人民广播交通台
mms://219.144.240.171/audio5 陕西人民广播农村台
mms://219.144.240.171/audio6 陕西人民广播音乐台
mms://219.144.240.171/audio7 陕西人民广播生活台
mms://219.144.240.171/audio3 陕西人民广播财富台
mms://audio.hndt.com/jtgb 河南人广交通广播
mms://audio.hndt.com/wygb 河南人广文艺广播
mms://audio.hndt.com/nygb 河南人广农业广播
mms://audio.hndt.com/jjgb 河南人广经济广播
mms://audio.hndt.com/yygb 河南人广音乐广播
mms://audio.hndt.com/fm90 河南人广文艺调频
mms://fm926.net/fm926 河南星河之声
mms://218.28.9.116/新闻广播 郑州新闻广播
mms://218.28.9.116/音乐广播 郑州音乐广播
mms://218.28.9.116/经济广播 郑州经济广播
mms://218.28.9.116/都市广播 郑州都市广播
mms://218.28.9.116/文艺广播 郑州文艺广播
mms://218.28.9.116/城市广播 郑州城市广播
mms://www.sqradio.com/商丘电台都市频道927khz
mms://www.sqradio.com/商丘电台交通频道
mms://www.sqradio.com/商丘电台新闻频道729khz
mms://61.134.39.94:4185/汉中音乐台
mms://www.lfradio.com:8080/1003 廊坊广播电台交通长书频道

#### 江西丶安徽丶山东

mms://movie.jxgdw.com/jswjxdt 江西人民广播电台新闻综合频率
mms://movie.jxgdw.com/jswjjsh 江西人民广播电台生活经济频率
mms://movie.jxgdw.com/jswwyyy 江西人民广播电台文艺音乐频率
mms://movie.jxgdw.com/jswxxxxjt 江西人民广播电台信息交通频率
mms://live.ahradio.com.cn/livemusic 安徽音乐电台
mms://218.106.82.110/audio3 合肥交通广播电台
mms://218.106.82.110/audio1 合肥人民广播电台
mms://218.106.82.110/audio2 合肥文艺广播电台
mms://210.77.193.6/music1 济南Music887
mms://61.156.28.17/jingji 济宁经济广播电台
mms://61.156.28.17/wenyi 济宁交通文艺台
mms://mms.zhaowo.com/wfradio 潍坊交通频道
mmst://61.156.23.102/rxinwen 威海广播新闻频道
mms://movie.top86.com/qdgb 青岛人民广播电台
mms://av1.jiaodong.net/radio3 烟台交通频道
mms://av1.jiaodong.net/radio2 烟台音乐频道
mms://av1.jiaodong.net/radio1 烟台新闻频道
rtsp://60.216.51.155/encoder/xinwen 山东广播新闻频道
rtsp://60.216.51.155/encoder/jingji 山东广播经济频道
rtsp://60.216.51.155/encoder/wenyi 山东广播文艺频道
rtsp://60.216.51.155/encoder/shenghuo 山东广播生活频道
rtsp://60.216.51.155/encoder/jiaotong 山东广播交通频道
rtsp://60.216.51.155/encoder/diliu 山东广播第六频道
rtsp://60.216.51.155/encoder/xiuxianyinyue 山东广播数字休闲音乐频道
rtsp://60.216.51.155/encoder/yinyue 山东广播音乐频道

#### 四川丶宁夏丶东北丶新疆

mms://61.133.211.228:1113/宁夏人民广播电台新闻综合频率
mms://61.133.211.228:4512/宁夏人民广播电台交通音乐频率
mms://61.133.211.228:4575/宁夏人民广播电台经济频率
mms://61.133.211.228:4619/宁夏都市生活频率
mms://media.newssc.org/fm94 四川人民广播电台经济频率FM94
mms://media.newssc.org/fm894 四川人民广播电台经济频率FM89.4
mms://broadcast.ucatv.com.cn/station5 乌鲁木齐生活
mms://broadcast.ucatv.com.cn/station6 乌鲁木齐维语
mms://broadcast.ucatv.com.cn/station3 乌鲁木齐旅游
mms://broadcast.ucatv.com.cn/station1 乌鲁木齐文艺
mms://broadcast.ucatv.com.cn/station2 乌鲁木齐新闻
mms://broadcast.ucatv.com.cn/station4 乌鲁木齐音乐
mms://59.44.238.2:6999/live 辽北广播辽北广播

#### 网络音乐

mms://vstream.sina.com.cn/900 新浪音乐台
mms://pub.qmoon.net:8009/audio 北京广播网青檬网络电台
http://mediaserver.iwant-in.net/player/casx.php?GApp=liveradio&GFiles=pop 银河网络电台
mms://live.mop.com/mopradio 猫扑网络电台
mms://zjlive1.45doo.com/live 45度网络电台
rtsp://radio.21cn.com/id/live2.rm 21CN网络电台(国)

#### 中央人民广播电台

mms://211.89.225.101/live1中央人民广播电台中国之声
mms://211.89.225.101/live2中央人民广播电台经济之声
mms://211.89.225.101/live3中央人民广播电台音乐之声
mms://211.89.225.101/live4中央人民广播电台都市之声
mms://211.89.225.101/live5中央人民广播电台中华之声
mms://211.89.225.101/live6中央人民广播电台神州之声
mms://211.89.225.101/live7_p中央人民广播电台华夏普通
mms://211.89.225.101/live7_s中央人民广播电台华夏双语
mms://211.89.225.101/live8中央人民广播电台民族之声
mms://211.89.225.101/live9中央人民广播电台文艺之声

#### 国外电台

http://am990.co.nz/2004/ram/4962-1.asx 新西兰BBC中文台
http://www.am990.co.nz/2004/ram/mm.asx 新西兰BBC中文台午间新闻
http://www.am990.co.nz/2004/ram/mc.asx 新西兰BBC中文台午间新闻[粤]
http://www.am990.co.nz/2004/ram/em.asx 新西兰BBC中文台晚间新闻
http://www.am990.co.nz/2004/ram/ec.asx 新西兰BBC中文台晚间新闻[粤]
http://202.172.226.198/RadioLive/FM933.asx 新加坡(醉心Y.e.s 93.3FM)
http://202.172.226.198/RadioLive/FM950.asx 新加坡(Class 95FM)　
http://202.172.226.198/RadioLive/FM972.asx 新加坡(最爱Love 97.2FM)　
http://202.172.226.198/RadioLive/FM968.asx 新加坡(Oli 96.8FM)　
http://202.172.226.198/RadioLive/FM987.asx 新加坡(Perfect 10 FM98.7)
http://202.172.226.198/RadioLive/FM897.asx 新加坡(Ria 89.7FM)　
http://202.172.226.198/RadioLive/FM942.asx 新加坡(Warna 94.2FM)　
http://media.netroasia.com/power98/power98.asx 新加坡(Power 98FM)
http://media.netroasia.com/power98/power98.asx 新加坡(WKRZ 91.3FM)
http://media.netroasia.com/ufm1003/ufm1003.asx 新加坡(UFM100.3)
mms://enmms.chinabroadcast.cn/am846 中国国际广播电台 am846
mms://enmms.chinabroadcast.cn/am1008 中国国际广播电台 am1008
mms://enmms.chinabroadcast.cn/fm91.5 中国国际广播电台 fm91.5
mms://chbcnews.com:1250 中国华艺广播
mms://www.fm926.net/fm926 中原流行音乐电台
mms://216.18.70.242/AM1470N 加拿大温哥华AM1470
mms://vruk.wm.llnwd.net/vruk_vr_lo Virgin Radio
mms://media4.abc.net.au/raflp 音乐澳洲广播电台
mms://a1234.l663344172.c6633.e.lm.akamaistream.net/d/1234/6633/666/reflector:44172 法国国际广播电台
mms://203.117.6.22/rsi-mandarin (RSI) 中文
mms://stream.eseenet.com/fm889 加拿大中文电台AM889
mms://216.18.70.242/fm961n 温哥华fm96.1
mms://living.chinabroadcast.cn/inet INetRadio
mms://enmms.chinabroadcast.cn/am846 CRIenglish FM846
mms://enmms.chinabroadcast.cn/am1008 CRIenglish am1008
mms://enmms.chinabroadcast.cn/fm91.5 5CRIenglish fm91.5
mms://enmms.chinabroadcast.cn/roundtheclock CRIenglish roundtheclock
rtsp://a1702.l211020409.c2110.g.lr.akamaistream.net:554.live/D/1702/2110/v0001.reflector:23641 美国之音(不用代理)
rtsp://a247.r.akareal.net/live/D/247/2110/v001/reflector:44464 美国之音VOANews
http://www.abc.net.au/streaming.ra.ram 澳州广播英文电台
http://av.sina.com/crn/show/crnlive.rpm 纽约中国广播网
http://tbn.twnet.com/live-cav.ram 纽约侨声综合台
rtsp://208.46.156.10/cav/news3.rm 纽约侨声新闻台
http://208.138.159.49/am1300.asx 中文广播电台
http://208.138.159.50/am1430.asx 华语广播电台
http://www.abc.net.au/streaming/newsradio.ram ABC NewsRadio(Real)
http://radiostorm.com/alt128.pls Alternative
http://www.radiostorm.com/classic128.pls Classic Rock
pnm://video.c-span.org/encoder/wcsp.ra C-SPAN
http://www.bloomberg.com/streams/audio/delivery/radio_live.asx?synd=msoft Bloomberg
http://www.di.fm/mp3/classical40k.pls MostlyClassical.com(40k)
http://www.di.fm/mp3/classical56k.pls MostlyClassical.com(56k)
http://www.di.fm/mp3/classical128k.pls MostlyClassical.com(128k)
http://www.kbs.co.kr/onair/L_1FM.asx 韩国KBS1FM
mms://210.124.186.162/kfm 京畿放送FM99.9
