---
title: "网络设备"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

如果说由于微型计算机的普及，导致了若干台微机相互连接，从而产生了局域网的话，那么由于网络的普遍应用，为了满足在更大范围内实现相互通信和资源共享，因而，导致了网络之间的互联。本节将介绍一般网络互联的硬件设备。

网络互联时，必须解决如下问题：在物理上如何把两种网络连接起来。一种网络如何与另一种网络实现互访与通信，如何解决它们之间协议方面的差别，如何处理速率与带宽的差别，解决这些问题，协调，转换机制的部件就是中继器，网桥，路由器和网关等。

#### 中继器

传输介质超过了网段长度后，可用中继器(repeater)延伸网络的距离，对弱信号予以再生放大，IEEE802标准规定最多允许四个中继器接五个网段。中继器工作在物理层，不提供网段隔离功能。

#### 集线器

集线器(hub)是一种以星型拓并结构将通信线路集中在一起的设备，相当于总线， 工作在物理层，是局域网中应用最广的连接设备，按配置形式分为独立型hub，模块化hub和堆叠式hub三种。

智能型hub改进了一般hub的缺点，增加了桥接能力，可滤掉不属于自己网段的帧，增大网段的频宽，且具有网管能力和自动检测端口所连接的PC网卡速度的能力。

市场上常见有10M，100M等速率的hub。

#### 交换器

交换式以太网数据包的目的地址将以太包从原端口送至目的端，向不同 的目的端口发送以太包时，就可以同时传送这些以太包，达到提高网络实际吞吐量的效果。交换器可以同时建立多个传输路径，所以在应用联结多台服务器的网段上可以收到明显的效果。主要用于联hub，server或分散式主干网。

按采用技术对交换器进行分类：

* 直通交换．(cut—through)：一旦收到信息包中的目标地址，在收到全帧之前便开始转发。适用于同速率端口和碰撞误码率低的环境。
* 存储转发：(store—and—forward)：确认收到的帧，过滤处理坏帧。适用于不同速率端口和碰撞，误码串高的环境。

应用注意：

1. 选10／100M适应交换机。
1. 选两种以上技术的交换机。

#### 网桥

网桥(bridge)

1. 过滤和转发。
1. 学习功能。
1. 连接不同的传输介质，无路径选择能力。

#### 路由器

路由器(router)是在多个网络和介质之间实现网络互联的一种设备，是一种比网桥更复杂的网络互联设备。 主要功能：

1. 分组转发，提供最佳路径，将不同硬件技术的网络互联起来。必要时进行分组格式和分组长度的转换。
1. 提供隔离，划分子网，路由器的每一端口都是一个单独的子网。
1. 提供经济合理的WAN接入。
1. 支持备用网络路径，支持网状网络拓扑，交换机，网桥要求，无环路拓扑。互联各种局域网和广域网。适用于大型交换网络。 可以认为使用Route后，形形色色的通信子网融为一体，形成了一个更大范围的网络，从宏观的角度出发,可以认为通信子网实际上是由路由器组成的网络，路由器之间的通信则通过各种通信子网的通信能力予以实现。

#### 网关

网关(gateway)用来互联完全不同的网络。主要功能：把一种协议变成另一种协议，把一种数据格式变成另一种数据格式，把一种速率变成另一种速率，以求两者的统一。提供中转中间接口。在Internet中，网关是一台计算机设备，它能根据用户通信用的计算机的IP地址，界定是否将用户发出的信息送出本地网络，同时，它还将外界发送给本地网络计算机的信息接收。
