---
title: "预防病毒的正确姿势"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“其他历史页面”](<../其他历史页面.qmd>)

::: {.callout-warning}
**已恢复历史版本**

当前版本 00000005 在备份中缺失；以下内容来自最新可读取版本 00000004。
:::

## 预防病毒的正确姿势

前段时间看到[这篇文章](http://googleonlinesecurity.blogspot.sg/2015/07/new-research-comparing-how-security.html)，深有感触。现在身边很多小白们都在用错误的方法保护自己的计算机和手机，导致他们使用计算机或者手机的时候战战兢兢，不敢安装任何软件，也不敢打开别人给的链接，生怕中了病毒。而计算机也被一堆打着安全保护的旗子的软件拖垮，使用起来像蜗牛一样缓慢。即使这样，还是免不了经常被木马和病毒的侵扰。所以觉得有必要写一篇文章，讲讲预防病毒和木马的正确姿势。

本人从94年开始使用计算机，超过20年的使用经验。曾在DOS时代中过一次病毒（名字忘记了），用F-PROT杀之，此后一直使用杀毒软件预防病毒。但是到了2003年，中了[冲击波病毒](https://en.wikipedia.org/wiki/Blaster_(computer_worm))，此后对如何防病毒有了新的认识，然后就再也没有中过病毒了。以下是我总结出来的六条建议。

### 卸载安全软件

保护计算机安全是操作系统本身的责任，第三方杀毒软件是防不住病毒的。比如Linux和iOS都没有杀毒软件，也没有被病毒感染的危险。而本人在2003年的时候用Windows计算机，在安装了最新的杀毒软件情况下，也还是受到了冲击波病毒感染。可见杀毒软件对于预防病毒来说，效果是很有限的。而且有些杀毒软件本身就是病毒或者流氓软件，难以卸载或者安插后面，或者杀毒软件厂商本身也在制造病毒木马或者流氓软件，比如最近的[卡巴斯基](http://www.ifanr.com/552433)，还有众多国产杀毒软件公司就无须点名了。况且安装了安全软件还有很多坏处，安全软件占用大量内存，拖慢应用的执行速度，因此同样配置的电脑运行Linux总比运行装了杀毒软件的Windows快很多，而卸载杀毒软件后，系统运行速度总是有大幅地提升。

具体做法：

* **如果已经安装了任何安全软件，卸载它们**，包括XX杀毒，XX安全管家，XX安全卫士，XX安全浏览器，XX管家，XX手机卫士，XX手机助手，……
* 如果是Windows上装了360百度之类的流氓安全软件，恭喜你，正常的官方的卸载程序可能无法彻底卸载它们，它们会在你的系统里面留下后台服务或者驱动程序继续运行。这时你就需要一些特殊的高级的技巧了（进入安全模式、修改注册表、删除隐藏文件等等），还是干脆重装系统吧。

### 安装最新操作系统补丁

如果操作系统本身有漏洞，其他任何安全措施都挡不住病毒。就像我说过的我中冲击波的经历，就是因为操作系统有漏洞，被远程攻击。那再装上网络防火墙是不是就好了？答案是否定的。操作系统除了有被网络攻击的漏洞外，还可能有其他类型的系统漏洞，比如提权漏洞，可以让普通权限下的病毒或者木马程序获得管理员权限，进而感染系统文件。何况有些服务是用户特意要对外提供，比如文件共享，不能通过网络防火墙关闭。

具体做法：

* **使用官方还在支持和维护的操作系统**，这样才能获得最新的安全补丁。比如，不要使用Windows XP，很古老的Mac OS X和Linux发行版。对于Android手机来说，如果厂商已经放弃你的Android手机型号，不提供最新的安全补丁，那么你也必须马上放弃你的手机，换一部厂商能够继续提供最新安全补丁的手机。
* **使用官方的更新渠道更新你的系统**。Windows上使用系统自带Windows Update功能，Mac上使用App Store，iOS上在系统设置中检查与下载更新，Linux上使用自带包管理器（比如Ubuntu的APT），Android上也使用系统自带的更新功能。不要通过第三方渠道或者工具，比如360之类的软件，来安装系统补丁。
* 经常检查操作系统有无更新（可以设置自动定时检查更新）。如果有更新，**立刻安装更新**。不要老是推迟你的Windows安装补丁和推迟重启。不要让你的iOS的“设置”程序右上角总有一个红色的数字1。

### 只从正规渠道下载安装软件

安装应用软件通常需要管理员权限，如果安装程序被人篡改加入木马或者病毒，那么它就可以绕过操作系统的安全权限，这样可能非常严重的危害。通过正规渠道下载安装软件可以确保安装程序是软件厂商或者作者发布的版本，不是被别人篡改的版本。很多操作系统都有官方的应用市场，官方的应用市场有专人监管，如果有人在官方应用市场中上传病毒或者木马，通常无法通过审核或者会被很快清除。而众多第三方的下载网站以及盗版下载网站则相反，它们充斥着木马与病毒，从这些地方下载是极其危险的。Android的第三方市场上的软件，很多都被篡改，加入了广告，甚至木马和病毒。所以不要使用Android第三方应用市场。也不要使用第三方的安装工具，比如什么什么助手之类的，它们也是同样的问题。

具体做法：

* iOS平台用App Store安装应用，**Android用Google Play安装应用**，Mac首先用Mac App Store搜索你需要安装的应用，Linux首先使用系统包管理器搜索应用（比如Ubuntu的APT），Windows 8（或者以上）首先使用Windows Store搜索应用。如果你的Android手机没有自带Google Play应用商店，你可以Google一个叫[OpenGapps](http://opengapps.org)的东西装上，同时卸载或者禁用手机上的第三方的应用市场。
* 如果官方市场中搜索不到需要的应用，或者操作系统没有官方市场（比如Windows 7），那么就**去软件的官方网站下载**。你可以用Google搜索来找到应用的官网。不要用百度搜索，因为通过百度往往找不到官方网站，而把你导向第三方下载地址。不要问我怎么才能打开Google，这个问题请自行Google之……
* 如果嫌搜索官方网站再下载很麻烦，还可以使用一些可靠的包管理工具，比如Windows上可以用[Chocolatey](https://chocolatey.org)，Mac可以用[HomeBrew](http://brew.sh)和HomeBrew Cask。它们会帮助你方便地从官方网站下载安装软件。
* 官方网站下载有时可能会有点慢，可以用一些多线程下载工具加快下载速度，比如multiget之类的。但不要用P2P下载软件，比如迅雷，这些软件会从不信任的第三方下载软件。
* 尽量不要使用国产的不开源的免费软件，它们的盈利模式通常不健康，要么充满了广告，要么盗取用户隐私，要么捆绑其他软件，要么不能卸载等等。

### 更新所有软件到最新版本

很多应用软件也会有安全漏洞，这也会导致感染木马，比如用有安全漏洞的微软Office打开别人发送的来的word文档，就可能会中木马。很多浏览器插件可能会有安全漏洞，在浏览恶意网站的时候，轻则可能导致隐私泄漏，重则可能导致操作系统中病毒，比如Adobe Flash插件，各种银行的插件等都可能有安全漏洞。

具体做法：

* 经常使用软件自带更新功能或者到官方网站更新应用，不要使用第三方工具或者第三方网站下载更新。
* 卸载或者禁用不常用的浏览器插件。

### 以非管理员方式登录操作系统

用权限较低的非管理员用户登录系统，即使执行了恶意程序，也可以大大限制恶意程序的危害。为什么Windows比Linux/Mac病毒多很多？一个重要原因就是因为Windows用户通常使用管理员用户Administrator登录。

具体做法：

* Mac和Linux系统通常已经是非管理员用户登录，不需要做什么。
* 如果是Windows系统，需要在操作系统控制面板的用户管理中创建一个普通用户，并用这个普通用户登录。需要安装软件或者用管理员权限执行某些程序时，在程序上点击右键，选择以管理员执行。
* Android和iOS正常情况下都是以普通用户登录运行的。iOS不要越狱。Android不要root。

### 定时备份

无论如何完备的防范措施，也是无法彻底杜绝系统被病毒和木马感染的可能性。很多时候，系统被病毒感染后，数据也会被破坏，只能从备份恢复。而有些病毒一旦感染，这些病毒是无法或者很难被彻底从系统中清除的，除非重装系统。除此以外，备份还可以避免其他原因引起的数据丢失，比如硬盘损坏，误操作等。

具体做法：

* **定时进行全盘备份**。所使用的备份软件最好支持增量备份，并**保留多份备份**，这样可以恢复到更早的备份，避免备份中也含有病毒而无法恢复。Mac可以使用Time Machine，Windows也有自带的备份工具。iOS可以选择备份到iCloud或者iTunes，
* 不仅备份你的操作系统本身，还要**备份你的数据**。数据比程序更重要，而且数据中也可能藏有木马。
* 加密你的备份。避免因备份失窃而泄露私密数据。

### 总结

要避免你的计算机、手机系统被病毒木马和其他恶意软件侵害，不能依靠一个所谓的安全软件，而是要**改变你使用它们的习惯**，而以上这些是最重要也是比较容易做到的几条建议，希望你也和我一样，用正确的姿势，不再有被恶意程序破坏的担忧，愉快地使用你的计算机和手机。欢迎你在下面的评论中，提出问题、建议或者意见。
