---
title: "TCPL/4.11.1_File_Inclusion"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“TCPL”](<../TCPL.qmd>)

#### 4.11.1 File Inclusion 文件包含

File inclusion makes it easy to handle collections of #defines and declarations (among other things). Any source line of the form
```
   #include "filename"
```
or
```
   #include <filename>
```
is replaced by the contents of the file filename. If the filename is quoted, searching for the file typically begins where the source program was found; if it is not found there, or if the name is enclosed in &lt; and &gt;, searching follows an implementation-defined rule to find the file. An included file may itself contain #include lines.

文件包含指令(即#include指令)使得处理大量的#define指令以及声明更加方便。在源文件中，任何形如：

```
   #include "filename"
```

或

```
   #include <filename>
```

的行都将被替换为由文件名指定的文件的内容。如果文件名用引号引起来，则在源文件所在位置查找该文件；如果在该位置没有找到文件，或者如果文件名是用尖括号&lt;与&gt;括起来的，则将根据相应的规则查找该文件，这个规则同具体的实现有关。被包含的文件本身也可包含#include指令。

There are often several #include lines at the beginning of a source file, to include common #define statements and extern declarations, or to access the function prototype declarations for library functions from headers like &lt;stdio.h&gt;. (Strictly speaking, these need not be files; the details of how headers are accessed are implementation-dependent.)

源文件的开始处通常都会有多个#include指令，它们用以包含常见的#define语句和extern声明，或从头文件中访问库函数的函数原型声明，比如&lt;stdio.h&gt;。(严格地说，这些内容没有必要单独存放在文件中；访问头文件的细节同具体的实现有关。)

#include is the preferred way to tie the declarations together for a large program. It guarantees that all the source files will be supplied with the same definitions and variable declarations, and thus eliminates a particularly nasty kind of bug. Naturally, when an included file is changed, all files that depend on it must be recompiled.

在大的程序中，#include指令是将所有声明捆绑在一起的较好的方法。它保证所有的源文件都具有相同的定义与变量声明，这样可以避免出现一些不必要的错误。很自然，如果某个包含文件的内容发生了变化，那么所有依赖于该包含文件的源文件都必须重新编译。
