---
title: "TCPL/5_Pointers_and_Arrays"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“TCPL”](<../TCPL.qmd>)

## Chapter 5 - Pointers and Arrays 指针与数组

A pointer is a variable that contains the address of a variable. Pointers are much used in C, partly because they are sometimes the only way to express a computation, and partly because they usually lead to more compact and efficient code than can be obtained in other ways. Pointers and arrays are closely related; this chapter also explores this relationship and shows how to exploit it.

指针是一种保存变量地址的变量。在C语言中，指针的使用非常广泛，原因之一是，指针常常是表达某个计算的唯一途径，另一个原因是，同其他方法比较起来，使用指针通常可以生成更高效、更紧凑的代码。指针与数组之间的关系十分密切，我们将在本章中讨论它们之间的关系，并探讨如何利用这种关系。

Pointers have been lumped with the `goto` statement as a marvelous way to create impossible-to-understand programs. This is certainly true when they are used carelessly, and it is easy to create pointers that point somewhere unexpected. With discipline, however, pointers can also be used to achieve clarity and simplicity. This is the aspect that we will try to illustrate.

指针和goto语句一样，会导致程序难以理解。如果使用者粗心，指针很容易就指向了错误的地方。但是，如果谨慎的使用指针，便可以利用它写出简单、清晰的程序。在本章中我们将尽力说明这一点。

The main change in ANSI C is to make explicit the rules about how pointers can be manipulated, in effect mandating what good programmers already practice and good compilers already enforce. In addition, the type `void \*` (pointer to `void`) replaces `char \*` as the proper type for a generic pointer.

ANSI C的一个最重要的变化是，它明确地制定了操纵指针的规则。事实上，这些规则已经被很多优秀的程序设计人员和编译器所采纳。此外，ANSI C适用类型void \*(指向void的指针)代替char \*作为通用指针的类型。

* [5.1 Pointers and Addresses 指针与地址](<5.01_Pointers_and_Addresses.qmd>)
* [5.2 Pointers and Function Arguments 指针与函数参数](<5.02_Pointers_and_Function_Arguments.qmd>)
* [5.3 Pointers and Arrays 指针与数组](<5.03_Pointers_and_Arrays.qmd>)
* [5.4 Address Arithmetic 地址算数运算](<5.04_Address_Arithmetic.qmd>)
* [5.5 Character Pointers and Functions 字符指针与函数](<5.05_Character_Pointers_and_Functions.qmd>)
* [5.6 Pointer Arrays; Pointers to Pointers 指针数组与指向指针的指针](<5.06_Pointer_Arrays;_Pointers_to_Pointers.qmd>)
* [5.7 Multi-dimensional Arrays 多维数组](<5.07_Multi-dimensional_Arrays.qmd>)
* [5.8 Initialization of Pointer Arrays 指针数组的初始化](<5.08_Initialization_of_Pointer_Arrays.qmd>)
* [5.9 Pointers vs. Multi-dimensional Arrays 指针与多维数组](<5.09_Pointers_vs._Multi-dimensional_Arrays.qmd>)
* [5.10 Command-line Arguments 命令行参数](<5.10_Command-line_Arguments.qmd>)
* [5.11 Pointers to Functions 指向函数的指针](<5.11_Pointers_to_Functions.qmd>)
* [5.12 Complicated Declarations 复杂声明](<5.12_Complicated_Declarations.qmd>)
