---
title: "TCPL/B.01_Input_and_Output:_<stdio.h>"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“TCPL”](<../TCPL.qmd>)

### B.1 Input and Output: &lt;stdio.h&gt;

The input and output functions, types, and macros defined in &lt;stdio.h&gt; represent nearly one third of the library.

A stream is a source or destination of data that may be associated with a disk or other peripheral. The library supports text streams and binary streams, although on some systems, notably UNIX, these are identical. A text stream is a sequence of lines; each line has zero or more characters and is terminated by '\\n'. An environment may need to convert a text stream to or from some other representation (such as mapping '\\n' to carriage return and linefeed). A binary stream is a sequence of unprocessed bytes that record internal data, with the property that if it is written, then read back on the same system, it will compare equal.

A stream is connected to a file or device by opening it; the connection is broken by closing the stream. Opening a file returns a pointer to an object of type FILE, which records whatever information is necessary to control the stream. We will use "file pointer" and "stream" interchangeably when there is no ambiguity.

When a program begins execution, the three streams stdin, stdout, and stderr are already open.

* [B.1.1 File Operations](<B.01.1_File_Operations.qmd>)
* [B.1.2 Formatted Output](<B.01.2_Formatted_Output.qmd>)
* [B.1.3 Formatted Input](<B.01.3_Formatted_Input.qmd>)
* [B.1.4 Character Input and Output Functions](<B.01.4_Character_Input_and_Output_Functions.qmd>)
* [B.1.5 Direct Input and Output Functions](<B.01.5_Direct_Input_and_Output_Functions.qmd>)
* [B.1.6 File Positioning Functions](<B.01.6_File_Positioning_Functions.qmd>)
* [B.1.7 Error Functions](<B.01.7_Error_Functions.qmd>)
