# theme: jekyll-theme-minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Zhongke's Personal Wiki
description: Zhongke's shared personal notes
show_downloads: false
google_analytics: G-WNLDZWNFJM
