project:
  type: website
  output-dir: _site
  render:
    - 404.qmd
    - index.md
    - LICENSE.md
    - wiki/Nostr.md
    - wiki/Raspberry Pi.md
    - wiki/SteamDeck.md
    - wiki/Tetris.md
    - wiki/YubiKey.md
    - wiki/乒乓球.md
    - wiki/去中心化.md
    - wiki/围棋.md
    - wiki/科学上网.md
    - old/首页.qmd
    - old/TCPL.qmd
    - old/Answer_to_Chapter_1.qmd
    - old/Examples_from_TCPL.qmd
    - old/Illustrated_C.qmd
    - old/Ch运行环境.qmd
    - old/C++集成开发环境.qmd
    - old/温大机房优化脚本.qmd
    - old/算法.qmd
    - old/计算理论.qmd
    - old/计算理论/*.qmd
    - old/计算机科学导论.qmd
    - old/计算机科学导论/**/*.qmd
    - old/离散数学.qmd
    - old/计算机图形学.qmd
    - old/算法与数据结构.qmd
    - old/程序设计语言.qmd
    - old/程序设计语言/**/*.qmd
    - old/数据结构.qmd
    - old/数据结构/**/*.qmd
    - old/数字图像处理.qmd
    - old/数字图像处理/*.qmd
    - old/Python游戏开发基础.qmd
    - old/Python游戏开发基础/*.qmd
    - old/高级语言程序设计课程.qmd
    - old/高级语言程序设计课程/*.qmd
    - old/面向对象程序设计课程.qmd
    - old/面向对象程序设计课程/*.qmd
    - old/Linux.qmd
    - old/Linux/*.qmd
    - old/ICPC.qmd
    - old/ICPC/*.qmd
  resources:
    - CNAME

lang: zh

website:
  title: "Zhongke's Personal Wiki"
  site-url: https://gw.ch3n2k.com
  repo-url: https://github.com/zhongkechen/wiki
  repo-branch: master
  repo-actions: [source]
  google-analytics: G-WNLDZWNFJM
  search: true
  page-footer:
    center: |
      Zhongke's shared personal notes<br>
      [![知识共享许可协议](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)](https://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      本作品采用[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://creativecommons.org/licenses/by-nc-sa/4.0/)进行许可。

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
    link-external-newwindow: true
