---
title: "图像处理教案"
---

[返回“图像处理课程”](图像处理课程.qmd)

## 温州大学课程教案

* 学院：计算机科学与学院
* 课程名称：数字图像处理
* 学时：36
* 教材：图像工程（上）
* 授课教师：陈忠克
* 授课对象：计算机本科

## 第一课

## 授课时间：

2课时

## 授课类型：

讨论课

## 授课题目：

什么是数字图像处理

## 本授课单元教学目标：

让学生了解什么是图像，什么是数字图像，什么是数字图像处理，掌握数字图像处理的基本过程，了解数字图像处理系统的基本组成，了解数字图像处理的应用领域，了解数字图像处理的工具。

## 本授课单元教学重点和难点：

* 重点：MATLAB中的使用方法
* 难点：数字图像的概念

## 本授课单元教学过程设计：

* （20分钟）讨论什么是图像，什么是数字图像，什么是数字图像处理
* （20分钟）介绍数字图像处理的起源，介绍数字图像处理的主要应用领域
* （15分钟）讨论数字图像处理有哪些步骤，数字图像处理系统有哪些组成部分
* （25分钟）介绍数字图像处理的工具MATLAB，演示简单的使用方法
* （5分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第二课

## 授课时间：

2课时

## 授课类型：

讨论课

## 授课题目：

数字图像处理基础

## 本授课单元教学目标：

让学生了解人眼是看到东西的原理，理解光的本质，掌握传感器如何捕获光，掌握在计算机中图像如何存储，以及像素之间存在的关系

## 本授课单元教学重点和难点：

* 重点：像素之间的关系
* 难点：图像的采样和量化

## 本授课单元教学过程设计：

* （20分钟）讨论：人眼是如何看到东西？人眼看东西有什么特点？
* （10分钟）讨论：什么是光和电磁场？
* （15分钟）讨论：图像传感器如何获取图像？传感器如何排列？
* （20分钟）讨论：图像在计算机中如何采样和量化？
* （20分钟）讨论：像素之间存在哪些关系（相邻、连通、距离）？
* （5分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第三课

## 授课时间：

2课时

## 授课类型：

讨论课

## 授课题目：

图像的空间变换

## 本授课单元教学目标：

让学生了解空间坐标如何变换，掌握平面坐标如何变换，掌握像素如何插值

## 本授课单元教学重点和难点：

* 重点：空间变换、插值
* 难点：空间变换

## 本授课单元教学过程设计：

* （30分钟）空间坐标如何表示？空间坐标有哪些基本的变换？坐标变换有些什么性质？
* （30分钟）平面上的坐标变换有哪些？它们各有什么特性？不同的变换之间有什么联系？
* （25分钟）在对图形进行几何变形时，为什么需要对像素进行插值？有哪些插值的算法？
* （5分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第四课

## 授课时间：

4课时

## 授课类型：

讨论课

## 授课题目：

图像的空间增强

## 本授课单元教学目标：

让学生掌握如何对像素进行运算，如何在空域进行滤波

## 本授课单元教学重点和难点：

* 重点：像素之间的关系
* 难点：图像的采样和量化

## 本授课单元教学过程设计：

* （30分钟）图像间的运算有哪些？它们有什么应用？
* （30分钟）图像像素的灰度变换有哪些操作？会带来什么效果？
* （30分钟）什么是直方图？利用直方图如何进行增强？
* （45分钟）如何进行空域的卷积？有哪些模板？可以产生什么效果？
* （40分钟）非线性滤波有哪些方法？各自可以产生什么效果？
* （5分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第五课

## 授课时间：

6课时

## 授课类型：

讨论课

## 授课题目：

图像的频域增强

## 本授课单元教学目标：

让学生掌握如何对图像进行傅立叶变换和离散余弦变换，掌握如何在变换域对图像进行增强

## 本授课单元教学重点和难点：

* 重点：频域增强
* 难点：傅立叶变换和离散余弦变换

## 本授课单元教学过程设计：

* （90分钟）什么是傅立叶变换？如何进行一维和二维的傅立叶变换？傅立叶变换有什么特性？
* （45分钟） 什么是离散余弦变换？它与傅立叶变换有什么关系？它有什么特点和应用？
* （20分钟） 频域图像处理的过程是怎样的？
* （70分钟） 如何设计低通滤波器？
* （35分钟） 如何设计高通滤波器？
* （10分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第六课

## 授课时间：

4课时

## 授课类型：

讨论课

## 授课题目：

彩色图像的处理

## 本授课单元教学目标：

让学生掌握彩色图像如何表示，掌握如何对彩色图像进行增强

## 本授课单元教学重点和难点：

* 重点：彩色增强的原理
* 难点：颜色模型

## 本授课单元教学过程设计：

* （25分钟）人是如何看到彩色的？三基色的原理是什么？
* （30分钟）什么是色度？什么是色度图？如何看色度图？
* （35分钟）常用的颜色模型有哪些？他们之间如何转化？(RGB,CMYK,YUV,YIQ,HSI等)
* （45）什么是伪彩色增强？有哪些伪彩色增强的方法？
* （35）如何对真彩色图像进行增强？
* （10分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第七课

## 授课时间：

4课时

## 授课类型：

讨论课

## 授课题目：

图像的恢复

## 本授课单元教学目标：

让学生掌握图像是如何退化的，掌握如何对退化的图像进行恢复

## 本授课单元教学重点和难点：

* 重点：退化的原理
* 难点：逆滤波

## 本授课单元教学过程设计：

* （20分钟）什么是噪声？噪声从哪里来？
* （25分钟）图像是如何被退化的？用什么模型来表示图象退化的过程？
* （40分钟）有什么方法可以去除图像中的噪声？
* （40分钟）有什么方法可以恢复退化了的图像？
* （45分钟）空间变形的图像如何恢复？如何确定空间变形的模型参数？
* （10分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第八课

## 授课时间：

3课时

## 授课类型：

讨论课

## 授课题目：

图像编码

## 本授课单元教学目标：

让学生掌握图像压缩的原理，掌握JPEG是如何对图像进行压缩的

## 本授课单元教学重点和难点：

* 重点：图像压缩原理
* 难点：JPEG算法

## 本授课单元教学过程设计：

* （40分钟）图像上有哪几种冗余存在？图像压缩和解压缩要经过哪些步骤？
* （35分钟）什么是哈夫曼编码？如何进行哈夫曼编码和解码？
* （50分钟）JPEG如何压缩图像？
* （10分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第九课

## 授课时间：

4课时

## 授课类型：

讨论课

## 授课题目：

数学形态学处理

## 本授课单元教学目标：

让学生掌握图像形态学处理的基本原理，掌握形态学处理的常见应用

## 本授课单元教学重点和难点：

* 重点：膨胀、腐蚀、开、闭
* 难点：形态学处理的应用

## 本授课单元教学过程设计：

* （30分钟）什么是膨胀(Dilation)和腐蚀(Erosion)？
* （45分钟）有哪些膨胀和腐蚀的组合运算？(Opening, Closing, Hit-or-Miss等)
* （35分钟）如何标记连通区域？
* （30分钟）什么是形态学重建？
* （35分钟）灰度图像如何做形态学处理？
* （10分钟）总结、布置作业

## 作业

 预习下一节课程内容，做好预习报告。下一节课的内容详见课程伴随网站。

## 第十课

## 授课时间：

5课时

## 授课类型：

讨论课

## 授课题目：

图像的分割

## 本授课单元教学目标：

让学生掌握图像分割的基本方法

## 本授课单元教学重点和难点：

* 重点：边缘检测算子，霍夫变换
* 难点：自适应阈值

## 本授课单元教学过程设计：

* （35分钟）如何检测图像中的点、线？
* （35分钟）如何检测图像中的边缘？
* （45分钟）如何检测直线？
* （45分钟）如何进行阈值分割？如何选取阈值？
* （40分钟）什么是区域生长？如何进行区域分裂与合并？
* （25分钟）总结、布置论文

## 作业

 准备期末论文。
