---
title: "图像处理实验教学大纲"
---

[返回“图像处理课程”](图像处理课程.qmd)

* [数字图像处理实验教学大纲.doc](<assets/图像处理实验教学大纲/数字图像处理实验教学大纲.doc>)

## 《数字图像处理实验》实验大纲

## 课程名称：

数字图像处理实验 Lab on Digital Image Processing

## 课程编码：

1421264009

## 课程目标和基本要求：

《数字图像处理实验》是《数字图像处理》的实践性配套课程，以Matlab作为主要实验开发环境。通过本课程的实验使得学生更牢固地掌握数字图像处理的基本方法和原理。通过本实验课程的学习，要求学生达到：掌握经典的数字图像处理算法的实现方法；了解常用的数字图像处理算法的运行效果；学会分析与比较各种方法的差异。

## 课程总学时：

36学时(严格按教学计划时数)[理论：0学时；实验：36学时]

## 课程总学分：

1学分(严格按教学计划学分)

## 适用专业和年级：

计算机科学与技术专业3年级

## 实验项目汇总表：

| 序号 | 实验编号 | 实验名称 | 时数 | 实验类别 | 实验类型 | 实验要求 | 每组人数 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 实验一 | 142126400901* | 熟悉MATLAB环境 | 6 | 专业 | 设计研究 | 必修 | 1 |
| 实验二 | 142126400902* | 图像空间变换 | 4 | 专业 | 设计研究 | 必修 | 1 |
| 实验三 | 142126400903* | 图像空域增强 | 6 | 专业 | 设计研究 | 必修 | 1 |
| 实验四 | 142126400904* | 图像频域增强 | 4 | 专业 | 设计研究 | 必修 | 1 |
| 实验五 | 142126400905* | 彩色图像处理 | 4 | 专业 | 设计研究 | 必修 | 1 |
| 实验六 | 142126400906* | 图像压缩 | 4 | 专业 | 设计研究 | 必修 | 1 |
| 实验七 | 142126400907* | 图像数学形态学处理 | 4 | 专业 | 设计研究 | 必修 | 1 |
| 实验八 | 142126400908* | 图像分割 | 4 | 专业 | 设计研究 | 必修 | 1 |

## 大纲内容

### 实验一  熟悉MATLAB环境实验

[实验目的和要求]

1. 掌握MATLAB的基本语法
1. 用MATLAB写几个小函数

基本要求：
   掌握MATLAB的基本语法，学会使用MATLAB编写简单的程序
[实验内容]

1. 编写4到5个完成一定功能的MATLAB函数

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验二  图像空间变换

[实验目的和要求]

1. 对图像进行空间缩放、旋转、剪切等变换
1. 对图像进行仿射变换

  基本要求：
    掌握常用的图像空间变换
[实验内容]

1. 简单图像空间变换：尝试使用各种简单的图像空间变换（缩放、旋转、剪切）对图像进行变换（在MATLAB里面已经有现成的函数可以使用， imresize、imrotate、imcrop，查看帮助去了解这些函数如何使用）。比较使用各种不同的插值方法所产生的图像效果的差别。
1. 写一个函数对图像进行仿射变换

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验三  图像空域增强实验

[实验目的和要求]

1. 按要求进行强度变换
1. 计算直方图
1. 对图像进行直方图均衡化
1. 对图像进行拉普拉斯滤波
1. 对图像进行Unsharp Mask滤波

  基本要求：
    掌握图像强度变换，掌握直方图和直方图均衡化，掌握图像间算术运算，掌握空域滤波算法
[实验内容]

1. 使用强度变换的图像增强
1. 直方图均衡化
1. 算术运算
1. 空域滤波
1. 拉普拉斯滤波
1. Unsharp masking

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验四  图像频域增强实验

[实验目的和要求]

1. 计算图像的傅立叶变换
1. 在频域进行低通滤波
1. 在频域进行高通滤波

  基本要求：
    掌握图像的傅立叶变换，掌握频域滤波算法
[实验内容]

1. 傅立叶频谱和平均值
1. 低通滤波
1. 使用低通滤波来实现高通滤波

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验五  彩色图像处理

[实验目的和要求]

1. 使用web-safe颜色替换真彩色图像
1. 对灰度图像进行伪彩色增强
1. 对彩色图像进行分割

  基本要求：
    掌握图像颜色的表示方法，掌握伪彩色增强，掌握真彩色图像的简单处理。
[实验内容]

1. Web-Safe颜色
1. 伪彩色图像处理
1. 彩色图像分割

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验六  图像压缩实验

[实验目的和要求]

1. 计算压缩图像的保真度
1. 计算图像的信息熵

  基本要求：
    掌握图像保真度的计算，掌握图像信息熵的计算
[实验内容]

1. 写一个程序，计算压缩图像的均方根误差和均方信噪比
1. 写一个程序计算图像的信息熵。

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验七  图像数学形态学处理实验

[实验目的和要求]

1. 腐蚀、膨胀运算
1. 开运算、闭运算

  基本要求：
    掌握基本的图像数学形态学处理。
[实验内容]

1. 实现形态学操作和其他集合操作
1. 边界提取
1. 连通分量
1. 形态学处理的一个应用

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

### 实验八  图像分割实验

[实验目的和要求]

1. 检测图像的边缘
1. 对图像进行阈值分割
1. 对图像进行区域生长

  基本要求：
    掌握基本的边缘检测算法，掌握基本的阈值分割算法，掌握图像区域生长算法。
[实验内容]

1. 写程序进行图像的边缘检测
1. 写程序进行全局阈值分割
1. 写程序进行区域生长分割

[主要实验仪器与器材]

1. 计算机硬件
1. MATLAB软件

## 主要实验教材（指导书）及参考用书：

教材：

1. 《数字图像处理(MATLAB版)》 Rafael Gonzalez，电子工业出版社，2004

参考书和网站：

1. 《数字图像处理》 Rafael Gonzalez，电子工业出版社，2004
1. 《图象工程(上册) 图象处理和分析》 章毓晋，清华大学出版社
1. 《图像工程（上册）--图像处理（第2版）》 章毓晋，清华大学出版社

## 课程考核方式及成绩评定办法：

1. 成绩评定：其成绩由预习成绩、实验报告成绩、实验态度等组成
1. 实验总评成绩将以20%的比例计入该门课程的总成绩中。
