---
title: "图像处理理论教学大纲"
---

[返回“图像处理课程”](图像处理课程.qmd)

* [《数字图像处理》教学大纲.doc](<assets/图像处理理论教学大纲/《数字图像处理》教学大纲.doc>)
* [数字图像处理教学大纲.doc](<assets/图像处理理论教学大纲/数字图像处理教学大纲.doc>)

## 数字图像处理教学大纲

1. 课程名称：数字图像处理（Digital Image Processing）
1. 课程代码：1421046009
1. 学分/总学时：2/36
1. 开课单位：计算机科学与工程学院
1. 面向专业：计算机科学与技术专业及相关专业

## 课程的性质、目的和任务

数字图像处理是计算机应用的一个分支，《数字图像处理》课程是一门研究如何用计算机处理数字图像的专业选修课。主要目的是讲授数字图像处理与模式识别的基础知识，并通过编程实践来培养学生的动手能力和研究相关领域问题的能力。

通过本课程的学习，要求学生达到：

1. 讲授数字图像处理的基本知识；
1. 讲授图像分析与图像识别的部分基本算法；
1. 讲授统计模式识别的基本概念；
1. 讲授图像处理领域的基本编程实践方法；

## 学习本课程学生应掌握的前设课程知识

本课程的先行课程有：《高等数学》、《线性代数》、《离散数学》、《高级语言程序设计》、《信号与系统》、《数字信号处理》、《数据结构》、《多媒体技术基础》。

## 学时分配

课程授课时间为36学时

| 章节 | 理论学时 | 实验学时 | 合计学时 |
| --- | --- | --- | --- |
| 第1章 | 2 | 0 | 2 |
| 第2章 | 4 | 0 | 4 |
| 第3章 | 4 | 0 | 4 |
| 第4章 | 4 | 0 | 4 |
| 第5章 | 2 | 0 | 2 |
| 第6章 | 4 | 0 | 4 |
| 第7章 | 4 | 0 | 4 |
| 第8章 | 4 | 0 | 4 |
| 第9章 | 4 | 0 | 4 |
| 第10章 | 4 | 0 | 4 |
| 合计 | 36 | 0 | 36 |

本课程的实验另外单独开课，不在此处列出。

## 课程内容和基本要求

第一章：绪论（课时数见前表）
 主要内容：

1. 什么是图像？什么是数字图像？什么是数字图像处理？
1. 图像上那些值表示的是什么？
1. 数字图像处理有几个层次？
1. 数字图像处理什么时候起源？ 数字图像处理在哪些领域有应用？
1. 数字图像处理有哪些处理步骤？一个数字图像处理系统有哪些部分组成？
1. 进行数字图像处理的研究可以使用什么软件工具？

 基本要求：

1. 掌握图像处理的基本内容
1. 掌握图像处理的应用领域
1. 了解图像处理的工具MATLAB及其图像处理工具包

第二章：数字图像处理基础（课时数见前表）
 主要内容

1. 人眼是如何看到东西？人眼看东西有什么特点？
1. 图像在计算机中如何采样和量化？
1. 像素之间存在哪些关系（相邻、连通、距离）？
1. MATLAB如何表示和处理数字图像？

 基本要求：

1. 掌握数字图像的基本概念
1. 掌握MATLAB的基本语法
1. 掌握MATLAB中数字图像的表示
1. 掌握MATLAB中数字图像的读写、显示、类型转换、

第三章：图像强度变换和空域滤波（课时数见前表）
 主要内容：

1. 图像间的运算有哪些？它们有什么应用？
1. 图像像素的灰度变换有哪些操作？会带来什么效果？
1. 什么是直方图？利用直方图如何进行增强？
1. 如何进行空域的卷积？有哪些模板？可以产生什么效果？
1. 非线性滤波有哪些方法？各自可以产生什么效果？

 基本要求：

1. 掌握图像间的算术运算
1. 掌握灰度变换
1. 掌握直方图的基本概念和基本处理方法
1. 掌握空域滤波的方法

第四章：频域图像处理（课时数见前表）
 主要内容：

1. 什么是傅立叶变换？如何进行一维和二维的傅立叶变换？傅立叶变换有什么特性？
1. 频域图像处理的过程是怎样的？
1. 如何设计低通滤波器？
1. 如何设计高通滤波器？

 基本要求：掌握：

1. 掌握傅立叶变换的原理和方法
1. 掌握频域滤波的过程
1. 掌握频域滤波器的设计方法

第五章：图像恢复（课时数见前表）
 主要内容：

1. 什么是噪声？如何去除图像中的噪声？
1. 空间变形的图像如何恢复？如何确定空间变形的模型参数？

 基本要求：

1. 掌握图像降噪的方法和不同方法的效果
1. 掌握图像空间几何变换与灰度插值

第六章：彩色图像处理（课时数见前表）
 主要内容：

1. 人是如何看到彩色的？三基色的原理是什么？
1. 什么是色度？什么是色度图？如何看色度图？
1. 常用的颜色模型有哪些？他们之间如何转化？(RGB,CMYK,YUV,YIQ,HSI等)
1. 什么是伪彩色增强？有哪些伪彩色增强的方法？
1. 如何对真彩色图像进行增强？

 基本要求：

1. 掌握彩色图像的表示方法
1. 掌握彩色图像的基本处理方法

第七章：图像压缩（课时数见前表）
 主要内容：

1. 图像上有哪几种冗余存在？图像压缩和解压缩要经过哪些步骤？
1. 什么是哈夫曼编码？如何进行哈夫曼编码和解码？
1. 什么是离散余弦变换？它与傅立叶变换有什么关系？它有什么特点和应用？
1. JPEG如何压缩图像？

 基本要求：

1. 掌握图像压缩的原理
1. 掌握常见的图像压缩方法

第八章：形态学图像处理（课时数见前表）
 主要内容：

1. 什么是膨胀(Dilation)和腐蚀(Erosion)？
1. 有哪些膨胀和腐蚀的组合运算？(Opening, Closing, Hit-or-Miss等)
1. 如何标记连通区域？
1. 什么是形态学重建？
1. 灰度图像如何做形态学处理？

 基本要求：

1. 掌握基本的数学形态学运算（膨胀、腐蚀、开、闭等）
1. 掌握形态学重建方法
1. 掌握连通区域标记方法

第九章：图像分割（课时数见前表）
 主要内容：

1. 如何检测图像中的边缘？
1. 如何用霍夫变换检测图像中的直线？
1. 如何进行阈值分割？如何选取阈值？
1. 什么是区域生长？如何进行区域分裂与合并？
1. 如何用分水岭算法进行图像分割？

 基本要求：

1. 掌握常用的边缘检测算子
1. 掌握霍夫变换
1. 掌握阈值分割方法
1. 掌握区域生长方法
1. 掌握分水岭算法

第十章：表达与描述（课时数见前表）
 主要内容：

1. 如何用链码表达对象的轮廓？
1. 如何描述一个轮廓？
1. 如何描述一个区域？

 基本要求：

1. 掌握链码与骨架表达
1. 掌握傅立叶描述
1. 掌握纹理和不变矩描述

## 教材及学生参考书

教材：

1. 《数字图像处理（MATLAB版）》，Rafael C. Gonzalez, Richard E. Woods, Steven L. Eddins主编，Prentice Hall出版社，2004年

参考书和网站：

1. 《图像处理和分析》，章毓晋主编，清华大学出版社，2000年
1. 《数字图像处理（第二版）》， Rafael C.Gonzalez Richard E.Woods主编，Prentice Hall出版社，2003年

## 作业及课外学习要求

为了培养学生主动学习能力，综合分析和解决问题的能力，要求学生在课外阅读参考书目，并要有相当多的动手实践。每次课前完成相关内容的预习和自学，提交预习报告。

## 课程考核方式及成绩评定方法

* 期末考核：撰写数字图像处理论文一篇
* 总评成绩：作业、平时考勤及学习态度（含实验）占 70%，论文占30%。

## 其它说明
