---
title: "图像处理实验教案"
---

[返回“图像处理课程”](图像处理课程.qmd)

## 温州大学课程实验教案

* 学院：计算机科学与学院
* 课程名称：数字图像处理实验
* 学时：36
* 教材：数字图像处理matlab版
* 授课教师：陈忠克
* 授课对象：计算机本科

## 第一课

## 授课时间：

6课时

## 授课类型：

实验课

## 授课题目：

熟悉MATLAB环境

## 本授课单元教学目标：

* 掌握MATLAB的基本语法，学会使用MATLAB编写简单的程序
* 用MATLAB写几个小函数

## 本授课单元教学重点和难点：

重点：掌握MATLAB的基本语法
难点：如何不使用循环实现所需功能

## 本授课单元教学过程设计：

1. 自学matlab语法（3课时）
1. 编写4到5个完成一定功能的MATLAB函数（2课时）
1. 完成实验报告（1课时）

## 第二课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

图像空间变换

## 本授课单元教学目标：

* 掌握对图像进行空间缩放、旋转、剪切等变换
* 掌握对图像进行仿射变换

## 本授课单元教学重点和难点：

* 重点：基本的空间几何变换
* 难点：仿射变换、插值

## 本授课单元教学过程设计：

1. 简单图像空间变换：尝试使用各种简单的图像空间变换（缩放、旋转、剪切）对图像进行变换（在MATLAB里面已经有现成的函数可以使用， imresize、imrotate、imcrop，查看帮助去了解这些函数如何使用）。比较使用各种不同的插值方法所产生的图像效果的差别。（1课时）
1. 写一个函数对图像进行仿射变换（2课时）
1. 完成实验报告（1课时）

## 第三课

## 授课时间：

6课时

## 授课类型：

实验课

## 授课题目：

图像空域增强

## 本授课单元教学目标：

掌握图像强度变换，掌握直方图和直方图均衡化，掌握图像间算术运算，掌握空域滤波算法

## 本授课单元教学重点和难点：

* 重点：图像强度变换，直方图和直方图均衡化，图像间算术运算，空域滤波算法
* 难点：直方图均衡化

## 本授课单元教学过程设计：

完成如下内容：

1. 使用强度变换的图像增强（1课时）
1. 直方图均衡化（1课时）
1. 算术运算（1课时）
1. 空域滤波、拉普拉斯滤波、Unsharp masking （2课时）
1. 完成实验报告（1课时）

## 第四课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

图像频域增强

## 本授课单元教学目标：

* 掌握图像的傅立叶变换，掌握频域滤波算法

## 本授课单元教学重点和难点：

* 重点：低通滤波、高通滤波
* 难点：傅立叶变换

## 本授课单元教学过程设计：

完成：

1. 傅立叶频谱和平均值（1课时）
1. 低通滤波（1课时）
1. 使用低通滤波来实现高通滤波（1课时）
1. 完成实验报告（1课时）

## 第五课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

彩色图像处理

## 本授课单元教学目标：

* 掌握图像颜色的表示方法，掌握伪彩色增强，掌握真彩色图像的简单处理。

## 本授课单元教学重点和难点：

* 重点：颜色的表示方法
* 难点：彩色图像分割

## 本授课单元教学过程设计：

完成：

1. Web-Safe颜色处理（1课时）
1. 伪彩色图像处理（1课时）
1. 彩色图像分割（1课时）
1. 完成实验报告（1课时）

## 第六课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

图像压缩

## 本授课单元教学目标：

* 掌握图像保真度的计算，掌握图像信息熵的计算

## 本授课单元教学重点和难点：

* 重点：保真度和熵的计算
* 难点：

## 本授课单元教学过程设计：

完成：

1. 写一个程序，计算压缩图像的均方根误差和均方信噪比。（2课时）
1. 写一个程序计算图像的信息熵。（1课时）
1. 完成实验报告（1课时）

## 第七课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

图像数学形态学处理

## 本授课单元教学目标：

* 掌握基本的图像数学形态学处理（腐蚀、膨胀、开、闭等）

## 本授课单元教学重点和难点：

* 重点：腐蚀、膨胀运算、开运算、闭运算
* 难点：数学形态学应用

## 本授课单元教学过程设计：

1. 实现形态学操作和其他集合操作（0.5课时）
1. 边界提取（0.5课时）
1. 连通分量（1课时）
1. 形态学处理的一个应用（1课时）
1. 完成实验报告（1课时）

## 第八课

## 授课时间：

4课时

## 授课类型：

实验课

## 授课题目：

图像分割

## 本授课单元教学目标：

掌握基本的边缘检测算法，掌握基本的阈值分割算法，掌握图像区域生长算法。

## 本授课单元教学重点和难点：

* 重点：检测图像的边缘、对图像进行阈值分割、对图像进行区域生长
* 难点：区域生长

## 本授课单元教学过程设计：

完成：

1. 写程序进行图像的边缘检测（1课时）
1. 写程序进行全局阈值分割（1课时）
1. 写程序进行区域生长分割（1课时）
1. 完成实验报告（1课时）
