---
title: "timus1052"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## Rabbit hunt

http://acm.timus.ru/problem.aspx?space=1&num=1052

Time Limit: 2.0 second

Memory Limit: 1 000 KB

A good hunter kills two rabbits with one shot. Of course, it can be easily done since for any two points we can always draw a line containing the both. But killing three or more rabbits in one shot is much more difficult task. To be the best hunter in the world one should be able to kill the maximal possible number of rabbits. Assume that rabbit is a point on the plane with integer x and y coordinates. Having a set of rabbits you are to find the largest number K of rabbits that can be killed with single shot, i.e. maximum number of points lying exactly on the same line. No two rabbits sit at one point.

### Input

An input contains an integer N (2&lt;=N&lt;=200) specifying the number of rabbits. Each of the next N lines in the input contains the x coordinate and the y coordinate (in this order) separated by a space (-1000&lt;=x,y&lt;=1000).

### Output

The output contains the maximal number K of rabbits situated in one line.

### Sample Input

```
6
7 122
8 139
9 156
10 173
11 190
-100 1
```

### Sample Output

```
5
```

Problem Author: Vasiljev S.

---
