---
title: "zju1949"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## Error Correction

http://acm.zju.edu.cn/show_problem.php?pid=1949

Time limit: 1 Seconds

Memory limit: 32768K

A boolean matrix has the parity property when each row and each column has an even sum, i.e. contains an even number of bits which are set. Here's a 4 x 4 matrix which has the parity property:
```
1 0 1 0
0 0 0 0
1 1 1 1
0 1 0 1
```
The sums of the rows are 2, 0, 4 and 2. The sums of the columns are 2, 2, 2 and 2.

Your job is to write a program that reads in a matrix and checks if it has the parity property. If not, your program should check if the parity property can be established by changing only one bit. If this is not possible either, the matrix should be classified as corrupt.

### Input

The input will contain one or more test cases. The first line of each test case contains one integer n (n &lt; 100), representing the size of the matrix. On the next n lines, there will be n integers per line. No other integers than 0 and 1 will occur in the matrix. Input will be terminated by a value of 0 for n.

### Output

For each matrix in the input file, print one line. If the matrix already has the parity property, print "OK". If the parity property can be established by changing one bit, print "Change bit (i,j)" where i is the row and j the column of the bit to be changed. Otherwise, print "Corrupt".

### Sample Input

```
4
1 0 1 0
0 0 0 0
1 1 1 1
0 1 0 1
4
1 0 1 0
0 0 1 0
1 1 1 1
0 1 0 1
4
1 0 1 0
0 1 1 0
1 1 1 1
0 1 0 1
0
```

### Sample Output

```
OK
Change bit (2,3)
Corrupt
```

Problem Source: University of Ulm Local Contest 1998

---

```cpp
//2007-01-11 21:26:33 Accepted 1949 C++ 00:00.01 404K
//writen by 曹高挺
#include <stdio.h>

bool mat[100][100];
bool row[100];
bool col[100];

int main(){
	int size;
	int i, j;
	int posi, posj;
	int oddi, oddj;
	while( scanf("%d", &size), size ){
		for(i=0; i<size; i++){
			row[i] = col[i] = false;
		}
		for(i=0; i<size; i++){
			for(j=0; j<size; j++){
				scanf("%d", &mat[i][j]);
				row[i] = row[i]^mat[i][j];
				col[j] = col[j]^mat[i][j];
			}
		}
		oddi = oddj = 0;
		for(i=0; i<size; i++){
			if( row[i] ){
				oddi ++;
				posi = i;
			}
			if( col[i] ){
				oddj ++;
				posj = i;
			}
		}
		if( !oddi && !oddj ){
			printf("OK\n");
			continue;
		}
		if( oddi==1 && oddj==1 ){
			printf("Change bit (%d,%d)\n", posi+1, posj+1);
			continue;
		}
		printf("Corrupt\n");
	}

	return 1;
}
```
