---
title: "zju1168"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## Function Run Fun

http://acm.zju.edu.cn/show_problem.php?pid=1168

Time limit: 1 Seconds

Memory limit: 32768K

We all love recursion! Don't we?

Consider a three-parameter recursive function w(a, b, c):

if a <= 0 or b <= 0 or c <= 0, then w(a, b, c) returns:
1

if a > 20 or b > 20 or c > 20, then w(a, b, c) returns:
w(20, 20, 20)

if a < b and b < c, then w(a, b, c) returns:
w(a, b, c-1) + w(a, b-1, c-1) - w(a, b-1, c)

otherwise it returns:
w(a-1, b, c) + w(a-1, b-1, c) + w(a-1, b, c-1) - w(a-1, b-1, c-1)

This is an easy function to implement. The problem is, if implemented directly, for moderate values of a, b and c (for example, a = 15, b = 15, c = 15), the program takes hours to run because of the massive recursion.

### Input

The input for your program will be a series of integer triples, one per line, until the end-of-file flag of -1 -1 -1. Using the above technique, you are to calculate w(a, b, c) efficiently and print the result. For example:
```
1 1 1
2 2 2
10 4 6
50 50 50
-1 7 18
-1 -1 -1
```

### Output

Print the value for w(a,b,c) for each triple, like this:

```
w(1, 1, 1) = 2
w(2, 2, 2) = 4
w(10, 4, 6) = 523
w(50, 50, 50) = 1048576
w(-1, 7, 18) = 1
```

Problem Source: Pacific Northwest 1999

------

```cpp
/* 1168 ymC */
#include <stdio.h>
const int N3=9261;
const int N2=441;
const int N1=21;
int w[9261];
void init()
{
     int a,b,c;
     int t;
     int i;
     for(a=0;a<N1;a++)
     {
        for(b=0;b<N1;b++)
          w[a*N2+b*N1]=1;
        for(c=0;c<N1;c++)
          w[a*N2+c]=1;
     }
     for(b=0;b<N1;b++)
        for(c=0;c<N1;c++)
          w[b*N1+c]=1;

     for(i=0;i<N3;i++)
     {
          if(w[i]!=1)
          {
              a=i/N2;
              c=i%N1;
              b=i/N1-a*N1;
              if(a<b&&b<c)
                  w[i]=w[i-1]+w[i-N1-1]-w[i-N1];
              else
                  w[i]=w[i-N2]+w[i-N2-N1]+w[i-N2-1]-w[i-N2-N1-1];
          }
     }
}
int main()
{
    int a,b,c;
    init();
    scanf("%d %d %d",&a,&b,&c);
    while(a!=-1||b!=-1||c!=-1)
    {
          printf("w(%d, %d, %d) = ",a,b,c);
          if(a<=0||b<=0||c<=0)
               printf("1\n");
          else if(a>20||b>20||c>20)
              printf("%d\n",w[N3-1]);
          else
          {
               printf("%d\n",w[a*N2+b*N1+c]);
          }
          scanf("%d %d %d",&a,&b,&c);
    }

}
```
