---
title: "zju2108"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## Elevator

http://acm.zju.edu.cn/show_problem.php?pid=2108

Time limit: 1 Seconds

Memory limit: 32768K

The highest building in our city has only one elevator. A request list is made up with N positive numbers. The numbers denote at which floors the elevator will stop, in specified order. It costs 6 seconds to move the elevator up one floor, and 4 seconds to move down one floor. The elevator will stay for 5 seconds at each stop.

For a given request list, you are to compute the total time spent to fulfill the requests on the list. The elevator is on the 0th floor at the beginning and does not have to return to the ground floor when the requests are fulfilled.

### Input

There are multiple test cases. Each case contains a positive integer N, followed by N positive numbers. All the numbers in the input are less than 100. A test case with N = 0 denotes the end of input. This test case is not to be processed.

### Output

Print the total time on a single line for each test case.

### Sample Input

```
1 2
3 2 3 1
0
```

### Sample Output

```
17
41
```

------
```cpp
/*Written by czk*/
#include <iostream>
#include <sstream>
using namespace std;

int main() {
	while(1) {
		int count;
		int current = 0;
		int next;
		int total_time = 0;
		cin >> count;
		if(count==0) break;
		for(int i = 0; i < count; i++) {
			cin >> next;
			if(next > current)
				total_time += 6 * (next - current) + 5;
			else if(next < current)
				total_time +=4*(current - next)+5;
			else
				total_time += 5;
			current = next;
		}
		cout << total_time  << endl;
	}

}
```
