---
title: "zju2475"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## Benny's Compiler

http://acm.zju.edu.cn/show_problem.php?pid=2475

Time limit: 1 Seconds

Memory limit: 32768K

These days Benny has designed a new compiler for C programming language. His compilation system provides a compiler driver that invokes the language preprocessor, compiler, assembler and linker. C source file (with .C suffix) is translated to relocatable object module first, and then all modules are linked together to generate an executable object file.

The translator (preprocessor, compiler and assembler) works perfectly and can generate well optimized assembler code from C source file. But the linker has a serious bug -- it cannot resolve global symbols when there are circular references. To be more specific, if file 1 references variables defined in file 2, file 2 references variables defined in file 3, ... file n-1 references variables defined in file n and file n references variables defined in file 1, then Benny's linker walks out because it doesn't know which file should be processed first.

Your job is to determine whether a source file can be compiled successfully by Benny's compiler.

### Input

There are multiple test cases! In each test case, the first line contains one integer N, and then N lines follow. In each of these lines there are two integers Ai and Bi, meaning that file Ai references variables defined in file Bi (1 &lt;= i &lt;= N). The last line of the case contains one integer E, which is the file we want to compile.

A negative N denotes the end of input. Else you can assume 0 &lt; N, Ai, Bi, E &lt;= 100.

### Output

There is just one line of output for each test case. If file E can be compiled successfully output "Yes", else output "No".

### Sample Input

```
4
1 2
2 3
3 1
3 4
1

4
1 2
2 3
3 1
3 4
4

-1
```

### Sample Output

```
No
Yes
```

---

```cpp
/*Written by czk*/
#include <iostream>
#include <vector>
#include <queue>
using namespace std;

int main()
{
  while(1) {
    int n;
    cin >> n;
    if(n<0) break;

    vector< vector<int> > g(n, vector<int>(n, false) ); /*if replace int with bool, ZOJ will give runtime error! why?*/
    vector<int> in(n, 0);
    vector<int> used(n, false);

    for(int i = 0; i < n; i++) {
      int A, B;
      cin >> A >> B;
      if(A == B)
        continue;
      if(!g[A-1][B-1]) {
	g[A-1][B-1] = true;
	in[B-1] ++;
      }
    }
    int E;
    cin >> E;

    queue<int> v;
    v.push(E-1);
    while(!v.empty()) {
      int next = v.front();
      v.pop();
      for(int i = 0; i < n; i++) {
	if(g[next][i] && !used[i]) {
      used[i] = true;
      v.push(i);
	}
      }
    }

    for(int i = 0; i < n; i++)
      if(in[i] == 0||!used[i])
	v.push(i);
    while(!v.empty()) {
      int next = v.front();
      v.pop();
      for(int i = 0; i < n; i++) {
	if(g[next][i]) {
      g[next][i] = false;
      in[i]--;
      if(in[i] == 0)
        v.push(i);
	}
      }
    }
    bool result = true;
    for(int i = 0; i < n; i++) {
      if(used[i] && in[i] != 0) {
	result = false;
	break;
      }
    }
    cout << (result?"Yes\n":"No\n");
  }
}
```

```cpp
//2007-02-07 23:33:35 Accepted 2475 C++ 00:00.00 448K
//writen by 曹高挺
//白色：T边
//灰色：B边
//从给定的点开始DFS检测到B边则编译失败（这里需要忽略环）
#include <stdio.h>
#include <string.h>

#define WHITE	-1
#define GRAY	2
#define BLACK	3

inline int mmax(int a, int b){
	return a>b?a:b;
}

inline int mmin(int a, int b){
	return a<b?a:b;
}

int n;
int color[101];
bool map[101][101];
int start;
int low, up;

bool GetInfo(){
	scanf("%d", &n);
	if( n<0 )	return false;
	int i;
	int from, to;
	memset(map, false, sizeof(map));

	low = 200;
	up = -1;
	for(i=0; i<n; i++){
		scanf("%d %d", &from, &to);
		low = mmin(low, from);
		low = mmin(low, to);
		up = mmax(up, from);
		up = mmax(up, to);
		map[from][to] = true;
	}
	scanf("%d", &start);
	return true;
}

bool F(int node){
	color[node] = GRAY;
	int i;
	for(i=low; i<=up; i++){
		if(map[node][i] && i!=node){
			//注意文件I引用文件I的变量可以通过编译
			if(color[i] == GRAY){
				return false;
			}
			if(color[i]==WHITE && !F(i)){
				return false;
			}
		}
	}
    color[node] = BLACK;
	return true;
}

bool Solve(){
	memset(color, WHITE, sizeof(color));
	return F(start);
}

int main(){
	while( GetInfo() ){
		if( Solve() ){
			printf("Yes\n");
		}
		else{
			printf("No\n");
		}
	}

	return 1;
}
```
