---
title: "在线判题系统"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## 普通用户使用方法

实验和作业题目可以在在线判题系统上提交，由判题系统自动给出程序是否正确的判断。在线判题系统的校网地址在[http://wzuacm.3322.org/oj/](http://wzuacm.3322.org/oj/)（如果在外网，可以先vpn到校网内再打开，vpn的方法参见[这里](http://cmet.wzu.edu.cn/news/sub_news/wojiaovpnfuwukaishiceshi-huanyingguangdalaoshiceshishiyong/view)） （原外网服务器 [https://czk.8866.org/oj/](https://czk.8866.org/oj/)已经停止使用）

1. 进入首页后，首先选择网页上部的**登录**链接登陆系统。

1. 然后选择网页上部的**题目**链接，然后选择C++程序设计。

1. 然后在题目列表中选择要做的题目，看清楚题目的意思。

1. 按照题目意思编写程序

1. 在题目页面的最下面选择**提交**，将程序复制到输入框中，然后按提交按钮

1. 稍等片刻，在结果页面中可以看到系统对你提交的程序的判断结果。结果有这么几种：
    * 等待测试: 程序等待被测试，稍等片刻再刷新。长时间处于这样的状态，可能是后台测试程序没有工作。请联系网站管理员。
    * 正在测试: 正在测试，请等待片刻再刷新页面
    * 编译错误: 编译错误
    * 超出时间: Time Limit Exceeded! 运行时间超出题目要求
    * 超出内存: Memory Limit Exceeded! 运行的内存超出题目要求
    * 运行错误: 运行错误（除0或者指针、数组越界）
    * 答案错误: 程序输出结果错误
    * 格式错误 格式错误。可能多了或者少了空格、回车等空白符。
    * 正确: 完全正确，恭喜！
1. 竞赛功能尚未完成

## 管理员使用方法

现在系统主要支持两种方式的自动判题：一种是由用户按题目要求编写完整程序，由服务器根据事先编写好的测试用例对其进行测试。另一种方式是由用户按题目要求编写一个类、一个函数或者其他部分程序，由服务器将其和事先编写主程序一起编译，然后再用测试用例对其进行测试。管理员对题目进行管理的步骤如下：

1. 管理员登录后上面会有**管理**链接，点击管理后进入后台管理界面
1. 进入后台后，点击**问题**可以进入添加和修改题目的界面
1. 一个问题包括：标题、描述、输入格式、输出格式、输入样例、输出样例、时间内存限制、判题规则和测试数据。
1. 判题规则有严格比较输入输出、忽略所有空白、特殊判题程序判题、手动判题等。前两种都会有后台自动判题程序根据测试数据进行自动判题，区别只是在进行结果比对时是否忽略空白。特殊判题程序判题，需要在特殊判题框内输入一个判题程序，由该程序对结果进行比对（特殊判题还不能使用）。手动判题需要手动进行判题。模块判题则由给定主程序与用户提交的程序一起编译，再对编译后的结果进行测试。
1. 添加题目后，在**问题集**设置中将一定的题目加到特定的问题集中，并指定哪些用户具有访问权限。

## 修改记录

* new:限制同时判题的数量（当前是2）
* bugfix:换行符表示错误(测试数据中换行符为\r\n，而判题程序认为换行符为\n)
* bugfix:最后登录时间没有更新
* new:用户排名
* bugfix:用户答对题目列表中有重复项
* fix bug:原来使用的编译器GCC 4.1中在使用优化-O2时的浮点计算错误。换成GCC 4.0后正确。在10月10日之前遇到浮点数的题目WA的可以重新判断一下。
* fix bug:时区设置错误，所有时间差8个小时
* fix bug:显示源代码时没有对尖括号做转义处理
* fix bug:运行时错误只有错误代号，没有错误信息。现在大部分常见signal可以显示。
* new:python语言判题
* fix:中文显示问题
* fix:随机出现的MLE。读取proc文件系统中的进程信息的时候一个解析错误。
* fix:分页显示判题结果和用户列表

## Todo

* 更智能的结果比对
* 用户注册
* 比赛
* java等其他语言判题
* 特殊判题
* 分页显示排名
* security problems:(

-------
要留言请点击[留言](<留言.qmd>)
