---
title: "温州大学ACM_ICPC训练队章程"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“大学生程序设计竞赛”](../ICPC.qmd)

## 温州大学ACM ICPC训练队章程

### 总则

1. 目的

    制定本章程的目的在于规范训练的过程，明确各人的权利和义务，避免不必要的矛盾
1. 人员组成
    * 负责人：学校委任的专门负责ACM ICPC组织、管理工作的教师
    * 教练：有负责人指定的高年级有参赛经验的学生
        * 常务教练：教练中的一名，负责训练期间或非训练期间的日常管理
    * 选手：参加或可能参加当年比赛的学生。选手可以兼任教练。
    * 公众：训练队外的所有人
1. 本章程修改办法

    教师、教练、选手中任何一人提出建议，经有教练组讨论后告知采纳与否以及何时公布下一版征求意见稿。征求意见稿不具效力。征求意见稿在温州大学ACM论坛公布。教师、教练、选手、公众都可以对稿中条款内容、措词、编排等提出意见或建议。征求意见期为两周。两周后三周内，公布表决稿。表决稿不具效力。表决稿公布后一周是表决期，教师、教练、选手都有义务和权利

投票表决。弃权视同赞成。常务教练公布表决结果。赞成票占三分之二以上则通过表决稿，表决稿成为正式章程；否则，原有章程继续有效。人员组成或实验室人员组成发生较大变更后，由常务教练在适当时候公布新的名单

### 人员管理

1. 要成为训练队选手必须符合如下的前提要求：
    * 温州大学全日制在校本科、专科学生
    * 学习（不分必修、选修或者自学）过C语言程序设计、数据结构
    * 学有余力，有充足的课余时间参加训练
1. 要成为训练队选手必须满足如下条件之一：
    * 在校级比赛中获奖
    * 在各主要在线判题网站（比如ZOJ、UVA等）上做题超过100题
    * 曾参加过省级或者以上比赛
1. 选手离队
    * 遇到选手毕业、休学、退学等离开学校的情况，该选手被视为自动退出训练队
    * 如果选手中途需要离开训练队，需要在比赛前一个月提出书面的离队申请，并经负责人同意方可离队
    * 如果选手严重违纪，则被永久开除出训练队，不得重新入队
1. 所有人员调动必须经过训练队负责人同意

### 奖励

1. 在各级程序设计竞赛中获得优胜奖的选手，将得到训练队优秀队员称号，并得到配套的奖金奖励，以及在全校通报表扬。
1. 在训练队坚持训练一年以上的队员，将获得训练队成功参与队员称号，并被永久记入温州大学程序设计竞赛历史。
1. 在训练队坚持训练两年以上的队员，将获得训练队老队员称号，并有资格成为教练。
1. 教练领取一定薪水。

 1.

### 处罚

* 违纪：违纪处罚由常务教练当面给予警告。累计三次违纪视为严重违纪。
* 严重违纪：训练队内人员清除出队；对外人员视作不受欢迎的人，永远不得进入实验室

### 实验室

1. 实验室设备

    实验室设备包括实验室中的桌椅、计算机、打印机、网络设备、空调、以及其他一切家具和办公、生活用品。
1. 实验室人员
    * 常驻人员：经常在实验室工作和学习的人员(老队员和教练)
    * 临时人员：正在训练的队员
    * VIP：资深队员或教练，但是不在实验室工作和学习
    * 队外人员：不在训练队内，但是由于某种原因需要借用实验室设备者。
1. 实验室内行为

    禁止大声喧哗或借助扩音设备发出巨大声响以致影响他人工作。发现后老队员和教练有责任提醒喧哗者，提醒5次后视作违纪一次。严禁破坏实验室设备。故意破坏视作严重违纪；无意识但造成破坏后果的，视作违纪。严禁在未经常务教练许可的情况下使用服务器，包括浏览和打印。违者视作违纪。未经授权，队外人员不得使用实验室设备。授权的权利归教师所有。如果未获授权的队外人员在已获授权的人员的带领、诱导、许可或默许下使用实验室设备，该已获授权者视作违纪。常驻人员、临时人员在训练时、VIP默认获得授权。临时人员在非训练期间可经常务教练的许可后使用实验室设备，或者由于某种原因不便或不及向常务教练通报并在事后获得常务教练追授许可；否则视作违纪。常务教练在以下几种情况下可以不给请求人使用实验室设备的许可：训练期间设备不足；可能对训练造成负面效果；可能对试验设备造成伤害；可能对实验室学习气氛造成负面影响；未获使用授权的人员提出的请求。否则必须许可并及时安排请求人使用实验室设备。未获常务教练许可，任何人不得随意搬动实验室设备。常驻人员和训练中的临时人员和获得授权的队外人员人手一台台式机。在未获对方许可的情况下不得使用他人的机器，或者由于某种原因不便或不及提早向对方通报并在事后获得对方追授许可。违者警告一次；警告满三次后，视作违纪一次。VIP可以使用闲置的台式机。使用闲置的台式机，必须在事先或事后向常务教练通报。在未经所有者许可的情况下，任何人不得使用他人的私人物品，比如耳机、茶杯
1. 实验室清洁
    1. 圆桌

        训练期间由选手轮流清洁，每天清理并擦拭一次。每位选手负责一天。非集训期间由常驻人员负责保持清洁，清洁方案由常驻人员协商给出并贯彻执行。常务教练负责
    1. 地面

        每周扫地并且拖地板一次。集训期间由选手共同完成；非集训期间由常驻人员完成。常务教练负责。
    1. 电脑台

        由各人清洁、整理并负责自己的电脑台
    1. 处罚

        故意逃避责任，视作严重违纪；无意失责五次，视作为一次。

### 训练表现

    在由教练召集的训练中，不能提早一天通知教练缺席缘由，视作违纪。在由教练召集的训练中，不能提早一天通知教练迟到缘由并且迟到超过15分钟，视作违纪。在由教练召集的训练或队友召集的训练中，从事任何与训练无关的活动以至引起队友或教练反感的，视作违纪。

### 保密

1. 责任及处罚

    教练、选手有责任不向公众或被教练宣布不可告知的人员透露保密内容，并且不得在公共场所议论保密内容。无意泄密视作违纪；故意泄密视作严重违纪。
1. 保密内容

    队内自己出的题目、测试数据以及解答程序。服务器的密码，自行开发的竞赛相关系统的管理员权限、文档和源代码。被教练组宣布为保密的任何事物。

### 权利

    教师、教练、选手都有权提出修改本章程，并且对表决稿投赞成或否决票。教师有对本章程的最终解释权和最终裁决权。选手有权参加训练、讲座或其他由训练队组织的活动。教练、选手有权向常务教练提出使用实验室设备。
