---
title: "数字图像处理"
---

[返回首页](首页.qmd)

## 课前准备材料

* 复习线性系统：[Review_of_Linear_Systems.ppt](<数字图像处理/assets/数字图像处理/Review_of_Linear_Systems.ppt>)
* 复习线性代数：[review_of_matrices_and vectors.ppt](<数字图像处理/assets/数字图像处理/review_of_matrices_and vectors.ppt>)
* 复习概率论：[review_of_probability.ppt](<数字图像处理/assets/数字图像处理/review_of_probability.ppt>)

## 数字图像处理

1. [数字图像处理课程简介](<数字图像处理/数字图像处理课程简介.qmd>)
1. [什么是数字图像处理](<数字图像处理/什么是数字图像处理.qmd>)
1. [熟悉MATLAB环境](<数字图像处理/熟悉MATLAB环境.qmd>)
1. [图像的空域增强](<数字图像处理/图像的空域增强.qmd>)
1. [图像的频域增强](<数字图像处理/图像的频域增强.qmd>)
1. [图像的空间变换](<数字图像处理/图像的空间变换.qmd>)
1. [彩色图像的增强](<数字图像处理/彩色图像的增强.qmd>)
1. [数字图像压缩](<数字图像处理/数字图像压缩.qmd>)
1. [图像的数学形态学处理](<数字图像处理/图像的数学形态学处理.qmd>)
1. [图像如何分割](<数字图像处理/图像如何分割.qmd>)
1. [图像的形状表达和描述](<数字图像处理/图像的形状表达和描述.qmd>)
1. [多尺度图像处理](<数字图像处理/多尺度图像处理.qmd>)
1. [图像处理基础](<数字图像处理/图像处理基础.qmd>)
1. [图像如何恢复和重建](<数字图像处理/图像如何恢复和重建.qmd>)

* [数字图像处理作业](<数字图像处理/数字图像处理作业.qmd>)
* [数字图像处理期末论文](<数字图像处理/数字图像处理期末论文.qmd>)

## 数字图像处理实验

1. [熟悉MATLAB环境实验](<数字图像处理/熟悉MATLAB环境实验.qmd>)
1. [图像空域增强实验](<数字图像处理/图像空域增强实验.qmd>)
1. [图像频域增强实验](<数字图像处理/图像频域增强实验.qmd>)
1. [图像的空间变换实验](<数字图像处理/图像的空间变换实验.qmd>)
1. [彩色图像处理实验](<数字图像处理/彩色图像处理实验.qmd>)
1. [图像压缩实验](<数字图像处理/图像压缩实验.qmd>)
1. [数学形态学处理实验](<数字图像处理/数学形态学处理实验.qmd>)
1. [图像分割实验](<数字图像处理/图像分割实验.qmd>)
1. [数字图像处理实验考核](<数字图像处理/数字图像处理实验考核.qmd>)

## 参考资料

* 数字图像处理(Digital Image Processing)
    * Gonzalez & Woods: Digital Image Processing 电子工业出版社，讲得比较全面，而且比较细致，入门的绝对好书。(69元)中文版阮秋琦 译《数字图像处理》(59元)
    * Digital Image Processing (Using Matlab) 电子工业出版社，英文版，和上一本内容相近，但增加了Matlab实现代码。强烈推荐。
    * 章毓晋: 《图像工程(上)》清华大学出版社，上册是中文版入门书中公认比较好的一本(上: 20元)
    * 章毓晋: 《图像分割》科学出版社(科海有售 23元)
* 计算机视觉(Computer Vision)
    * Horn: Robot Vision，相关章节非常清楚紧密，虽然内容少了一点，因为主要和robot有关。不过值得入门看。
    * Marr: Vision，他首先提出把Vision的system，algorithm，theory分开，还提出了诸如2.5 Dimension等概念。只要想想ICCV的best paper叫做Marr's Price就知道他牛了。经典书，老了一点，不过值得看看。
    * David A.Forsyth,Jean Ponce: Computer Vision: A Modern Approach，介绍的topics比较多，可以看看当作vision的overview。另外作者是想描述modern vision，所以可以看看。(draft公开可下载)
    * Ramesh Jain,Rangachar Kasturi,Brain G.Schunck: Machine Vision 机械工业出版社(59元)
    * 章毓晋: 《图像工程(下)》清华大学出版社
    * 政南宁: 《计算机视觉与模式识别》国防工业出版社(45元)很好，但是对于数学的要求也比较高。
    * 张正友、马颂德: 《计算机视觉》浙江大学出版社(有超星电子版) 太难了，对于入门级的读者不是十分合适。
    * 贾云德: 《机器视觉》科学出版社

部分数字图像处理书籍的电子版：

* [数字图像处理电子书](<数字图像处理/数字图像处理电子书.qmd>)

课程建设材料：

* [图像处理课程](<数字图像处理/图像处理课程.qmd>)
