---
title: "美食"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回旧版首页](首页.qmd)

* 开太后面的金聚德 特色菜武昌鱼、新疆牛肉
* 文华后面的吉实家日本面 特色菜中华冷面
* 文华后面的三千里烤肉城 特色菜鸡翅
* 小南路的三百碗拉面 特色菜牛肉饭
* 文华后面的鱼乡人家 特色菜水煮鱼
* 江滨路韩国之家 特色菜牛排
* 马鞍池菜场旁边的巴蜀人家 特色菜鱼香肉丝
* 焦点楼下精武鸭头 特色菜当然是鸭头
* 南站的福建牛杂店 特色菜是牛杂汤 加辣更美味
* 大高桥的东方红川菜馆 特色菜是叫化排骨
* 站前东小区的重庆鱼庄 特色菜是水煮鱼和椒盐玉米
* 乘凉桥的广丰和面馆，特色菜有排骨饭，牛肉套餐饭，新鲜云吞面
* 五洲对面有一家沙县小吃的面条很有特色,
* 南站的一汽边的拉面店里的孜然羊肉
* 开泰和浦发当中那条巷里的一家台湾排骨大王的排骨很好吃
* 鹿港小镇的刨冰甜点系列
* 将军大酒店旁边一家小店的黄牛骨
* 伊甸园旁边的牛肉丸，牛蹄筋
* 学院路牛吧干炒牛荷，牛肉丸
* 小南路的双莲鱼丸店
* 城西街的猪脏粉
* 纱帽河的锅贴
* 晏公殿巷的熟食斋的酥排骨、辣肉
* 东阿外楼的江蟹生
* 龟湖路金丝桥那边海天宾馆一楼的“大东阳美食”里的菜都很地道，冷面也很好吃！
* 公安路那边的米面
* 还有沙帽河的饭团跟锅贴马槽头的陈辉鱼圆
* 强能鱼圆的鱼饼
* 解放北路康乐坊对面的灯盏糕
* 小南门五洲对面的粥天粥地
* 温州饭店对面的 广东小炒
* 五马街中间，高攻桥对面的煎饺和炒螺丝
* 沧桥街口烧饼
* 市中小学对面的鸡骨
* 大南门靠菜场边的金华酥饼
* 下吕浦潮州馆的粥
* 体育馆好又多后门的川之味 推荐回锅冬瓜 鱼香茄子 辣子鸡
* 老三样面馆的羊肚面,
* 乘凉桥的灯盏糕
* 灰桥口的桥头麦饼
* 西城路的丁记牛杂店特色菜霉菜烤鲫鱼
* 西城路的张记老鸭煲特色菜鸦片鱼，豆腐干等
* 乘凉桥（蝉街那里）刘家香辣馆
* 水心跟天窗巷一带的老鸭煲东游路的辣香婆川菜，尤其是那里的水煮鱼

部分餐饮店的联系电话：

乐温州郊县的特色美食：

* 南溪江--麦饼
* 泽雅--农家菜
* 湖岭--牛排
* 藤桥--熏鸡
* 桥下--羊肉
* 敖江--竹楼排挡（活蹦乱跳的海鲜，家乡酒酿 ）
* 平阳--牛肉羹 /抄粉干 （市区的楠溪楼，国际听说有）
* 白象--豆腐干
* 敖江--牛肉碎
* 文成--水晶糕

自助餐介绍：

1. 江心海景酒店中餐78元/位 11：00-14：00晚餐98元/位 17：00---21：00有意式、日式、美式、中式等各种选择特色菜：刺身 牛排是进口牛肉备注：饮料免费，酒水另计。再过一个礼拜，这里将推出韩国料理，且啤酒免费
1. 华侨饭店晚餐 118元/位 17：30---21：30牛排不错有榴莲酥
1. 维多利亚大酒店中餐58元/位 11：00-14：00 （只限周六，周日，平时不做中餐）晚餐88元/位 17：00---21：00特色菜有水煮系列环境好，情侣来的多
1. 意赛仑比萨美食广场中餐39元/位 11：00-14：00晚餐39元/位 17：00---20：30以西餐为主，中餐为辅特色是比萨饮料、啤酒免费，还有冰激淋不过没有停车位和筷子（以后会有）
1. 国际大酒店中餐48元/位 11：00-13：30晚餐78元/位 17：00---21：00好象报纸介绍不多，就不多说了座位分普通区和贵宾区（加收20元）
1. 奥林匹克大酒店中餐39元/位 11：00-13：30晚餐60元/位 17：00---21：00西点不错，有黑森林蛋糕但中餐只有一个牛排也不错，晚上有海鲜停车免费，人很多，要订位置，想多吃，吃好，要早点到
1. 王朝大酒店（体育中心）晚餐：68元/位 17：30---20：45特色菜是西式点心，品种多冰虾好吃，双鹿纯清是免费的
1. 东瓯大酒店中餐60元/位 11：00-14：00晚餐80元/位 17：00---21：00以中式为主，西点不多海鲜和水果不错，鲍鱼限送两个饮料免费，酒是零售的，但价格不贵，啤酒7元一瓶，
1. 新南亚大酒店68元/位 晚上17：00--9：00，中餐不错，特色推荐是蟹蒸饭，个人觉得小炒的味道不好西，其他我还是瞒喜欢的。

温州部分点心店的地理位置及联系电话:

* 店名 电话 地址
* 沙县小吃 88601257 新世纪花园
* 沙县小吃 88360477 黎明立交桥C首12号
* 沙县小吃 88991663 龙沈住宅区
* 小吃 86067966 划龙桥路
* 兴弟点心店 88119857黎明中路24号
* 美味点心店 88352288 黎明中路154号
* 高田点心店 88326752 黎明侨中巷4号
* 诚信点心 88356165 双井头新村
* 阿明锅贴点心 88871160江滨西路十八家路口
* 一品点心 88853087 江滨西路江滨大厦
* 点心店 88377923 车站大道立交桥下
* 农家点心 88792038 吴丰路33号
* 阿虎点心 86763086新南站26号
* 阿雪点心 86766455新南站24号
* 阿明点心 86789092 鱼鳞浃188号
* 阿奇点心店 88660281划龙桥393号
* 旭敏点心 88982928 车站大道金城大厦75号
* 康桥点心 88379961金桥路108号
* 胖仔点心 88355199金桥路87号
* 惠芸点心店 88378092 桥路90号
* 老兵点心店88369622金桥花园B幢
* 雪苗 88388987 下吕浦二区冬宁4幢102
* 蓉蓉 88386790南浦住宅区冬宁11幢106
* 阿光 88260697双莲小区9幢
* 炒粉 88258061巴黎大厦后
* 飞霞 88212130国泰大楼旁
* 月眉 88374365 南浦路494号
* 阿涛包子 88398823 温迪路南巷56号
* 风味 88395708 温迪锦园6幢117号
* 阿洁 88385721 下吕浦一区书声8幢105号
* 集香居 88224118 公园路148号
* 姐妹 88522644 水心住宅区樟8幢108室
* 环南 88812550马鞍池东路5号楼104号
* 国林面馆 88659055 划龙桥路中通A幢104#
* 兴墅点心 88834782 兴墅路45号

店名 电话 地址

* 温州饭摊 0577-86787299 火车站对面安居区鱼鳞浃路
* 阿中饭摊 0577-88650333 划龙桥
* 新浦乐饭摊 0577-88658822 南浦农贸市场旁
* 金城饭摊 0577-88920461 新城大道
* 正正饭摊 0577-88357315 学院中路
* 西角老店--黑人熟食连锁第四分店13173515889 88773084 黄龙住宅区5区映翠16幢112店名 电话 地址
* 大诚饭摊 0577-88340008 洪福巷68号
* 朋友饭摊 0577-88829790 江滨西路深发商住楼A幢
* 黄府饭摊 0577-88854180 江滨西路华綘A幢
* 新村饭摊 0577-88314438 江滨西路灰桥新村东泰大厦
* 巴黎饭摊 0577-88536680 杏花路110号新村大楼
* 林香饭摊 0577-88853545 蒲鞋市新村72幢111室
* 老水心饭摊 0577-88825395 温州市龟湖路45号
* 阿福饭摊 0577-88752160 温州黄龙住宅区

外买电话一览表

* 黎明路您好饭庄总店：温州南站朝阳大楼A幢103 外卖电话88829113
* 军供快餐： 88065827 (黎明西路)
* 王一刀面店 ： 88826510 (黎明西路18弄装饰市场内)
* 永和豆浆： 88813224 (黎明西路25号)
* 大光明 ： 88810340 88845385(东方大厦)
* 新亚饭店 餐饮部 88822534(黎明西路)
* 老三样： 88383111 88835230：（国贸大厦旁边）
* 宝林点心店： 88394884
* 好人家饭摊： 88841968
* 我家便当： 88335774 88202884（西站） 88834033（矮凳桥）
* 楼下小卖部： 88850043 13587674947 （国贸）
* 一鸣奶吧： 88333278(黎明侨村) 88859928(飞霞路)
* 财神记粥店 88991865 （车站大道时代南边中保附近）
* 福建名饺馆 （沙县小吃） 81820593 （南洋新村）
* 福建沙县特色小吃 81570563 （南站天桥边黎明西路）
* 麦饼的 81901501 在东方大厦旁边

小南门

* 阿毛面店的电话是 88505219 (马鞍池西路康乐大厦楼下)
* 大榕树饭摊（小南门）88217272

下吕浦

* 永茂豆浆大王 88380610
* 雪苗猪脏粉 8838987
* 老三样面摊 88383111
* 阿里山竹筒饭吧 88651129
* 台湾泡饭 88654997
* 东门鱼圆 88854795（下吕浦老三样旁）
* 大光明 88354823 (桥儿头分店)
* 财神记粥店 88991865 （车站大道时代南边中保附近）

新城：

* 店名: 永和豆浆 地址: 新城达道康源南楼103室 电话: 88919123 备注: 6:00-凌晨2:00 投诉电话 13566221778
* 店名: 皇上皇面馆 地址: 新城新乐大厦A座 电话: 88923455 备注:
* 店名: 强能鱼圆新城店 地址: 阿吧说不清楚 电话: 88914910 备注:
* 店名: 多多味面馆 地址: 新城新府花园12-103 电话: 88925892 备注:
* 店名: 温州市新城正新 地址: 温州市新府花园11-12幢110号 电话: 0577-88929778 备注:
* 店名: 陈老头拉面馆 地址: 新城 电话: 88928809 备注: 什么都有
* 店名: 精伍鸭头 地址: 新城新府花园 电话: 88917277 备注:
* 店名: 好面子 地址: 温州市新城金星花苑1幢104 电话: 88929977 备注:
* 店名: 精武鸭头 地址: 新城新府花园12幢101 电话: 0577-88917277 备注: 各类泡饭,各类粥都有.还有其他招牌小吃
* 店名: 福建沙县小吃 地址: 新城 电话: 0577-88926779 备注:

将军桥

* 瓯海区府附近的永茂豆浆大王 88536541

马鞍池

* 店名: 阿毛面店 地址: 马鞍池西路康乐大厦 电话: 88505219

西城路

* 店名: 温州市西城正新 地址: 温州市西城路8幢116室 电话: 0577-88708966 备注:
* 店名: 正新 地址: 温州市西城路8幢116室 电话: 88708966 备注:
* 店名: 阿多点心店 地址: 西城路菜场口 电话: 0577-88705550 备注: 这里的面条还不错！

五马街

* 店名: 温州市五马正新2店 地址: 温州市五马街94号 电话: 0577-88285557 备注:
* 店名: 麦当劳 地址: 五马街店 电话: 88264008 备注:

桥儿头:

* 大嘴巴饭庄 外卖电话：88321863

温州各大酒店订餐热线：

* 云天楼国鼎大酒店。。。。88288888
* 新阿外楼大酒店。。。。88826688
* 吉祥阁。。。。。。88299999
* 银都大酒店。。。。86511111
* 南阿外楼大酒店。。。。86768881
* 金田一村大酒店。。。。88599999
* 观松楼大酒店。。。。（解放北路）8817888
* 锦都富豪大酒店。。。。88668888
* 东阿外楼大酒店。。。。88188888 88199999
* 老阿外楼大酒店。。。。88186857
* 诚达大酒店。。。。88566666
* 新南亚大酒店。。。。88077777（转8666）
* 国贸大酒店。。。。88367979
* 温州奥林匹克大酒店。。。。88317979
* 新丁香江滨大酒店。。。。88177777
* 新丁香蝉街大酒店。。。。88267777
* 金旺角大酒店。。。。88197008
* 金瓯海鲜城。。。。88633333（转121、200）
* 忠诚大酒店。。。。（原东方宾馆）88067222
* 新江滨瓯越美食。。。。88825588
* 新溢香厅大酒店。。。。86528808
* 总商会俱乐部。。。。88225555（转288）
* 温州将军大酒店。。。。88618905
* 瑶溪山庄。。。。88098999 88093555
* 半岛公寓酒店半岛食街。。。。88080808
* 南浦大酒店。。。。88666666 88661111
* 顺生大酒店。。。。88088789 88088790
* 海员俱乐部。。。。（农家16碗）88070699
* 瓯昌饭店。。。。88528888
* 中侨宾馆中餐自助餐。。。。88075666
* 温州花园大酒店。。。。88326000-851
* 海上天酒店。。。。88118888 88818888
* 天都大酒店。。。。88501888 88526688
* 凯豪大酒店。。。。86889999 86869999
* 罗马城大酒店。。。。88255555 88268777
* 五马美食林鸿华大酒店。。。。88238888
* 五马美食林名豪大酒店。。。。88257777
* 瓯海宾馆。。。。88538888（转2851、2888）
* 文华大酒店。。。。88256789 88288306
* 得尔乐大酒店。。。。88212188
* 华尔顿大酒店。。。。88093339
* 双屿大酒店。。。。88780909
* 金豪大酒店。。。。（人民路kfc旁）88251098
* 珍宝舫大酒店。。。。88186666
* 小南美乐。。。。88250111
* 江宾美乐。。。。88171100

永嘉部分酒店:

* 店名 电话 地址
* 王龙彩酒店 0577-67282193 永嘉县瓯北镇千石村
* 永嘉阳光大酒店 0577-67355518 瓯北镇双塔路1211号
* 永嘉大酒店 0577-67221868 永嘉县上塘镇永建路231号
* 一村酒店 0577-67367355 永嘉县瓯北镇双塔路1429-1433号
* 进顺酒店 0577-67391277 永嘉县乌牛镇新大街45号
* 永嘉县王府大酒店 0577-67369788/67369789 瓯北镇阳光大道
* 永嘉县王府大酒店 0577-67369788/67369789 瓯北镇阳光大道
* 永嘉县东蒙大酒店 0577-67393788 乌牛镇工业区
* 永嘉县阳光大酒店 0577-13706783675 瓯北镇双塔路邮政大楼
* 永嘉大东方酒店 0577-67323888 永嘉瓯北双塔西路
* 永嘉县金三角大酒店 0577-13335772778 瓯北镇双塔路

## 附件

* [川味凉菜185例.pdf](<美食/assets/美食/川味凉菜185例.pdf>)
* [川味火锅85款.pdf](<美食/assets/美食/川味火锅85款.pdf>)
* [川味热菜150例.pdf](<美食/assets/美食/川味热菜150例.pdf>)
* [川菜烹饪秘诀.pdf](<美食/assets/美食/川菜烹饪秘诀.pdf>)
* [川菜烹饪经典-民俗风味菜.pdf](<美食/assets/美食/川菜烹饪经典-民俗风味菜.pdf>)
* [川菜选料与制作.pdf](<美食/assets/美食/川菜选料与制作.pdf>)
* [时尚川菜.pdf](<美食/assets/美食/时尚川菜.pdf>)
