---
title: "计算机科学导论"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回旧版首页](首页.qmd)

**计算机科学导论**是电气信息类相关专业的重要专业基础课程。计算机科学不但是一个基础学科，更重要的是一门面向应用的技术与工程的学科。因此，在兼顾其理论的核心基础同时，考虑计算机科学技术应用驱动的发展特征。

课程内容涉及计算机科学的方方面面，但着重讲解的是基本概念而不是数学模型和技术细节，采用广度优先的教学理念。

课程的重点在于叙述计算机科学体系的框架，传播计算机科学的基础知识，为今后深入学习各专业课程做好铺垫；通过教学，使学生了解计算机系统的基本构造，掌握计算机技术的相关理论和技术的基本概念，了解计算机技术的广泛性及其应用特点。

[习题库](<计算机科学导论/计算机导论习题库.qmd>)、[参考书](<计算机科学导论/计算机导论参考书.qmd>)、[教学大纲](<计算机科学导论/计算机导论理论教学大纲.qmd>)、[计算机导论教学运行表](<计算机科学导论/assets/计算机科学导论/Progress.jpg>)、[实验大纲](<计算机科学导论/计算机导论实验大纲.qmd>)、[计算机导论实验运行表](<计算机科学导论/计算机导论实验运行表.qmd>)、[参考实验平台](http://cchuang.vicp.net/intro/index.htm)、[实验手册](<计算机科学导论/assets/计算机科学导论/cintroexp.pdf>)、[实验报告模板](<计算机科学导论/assets/计算机科学导论/report.doc>)

## 硬件基础

本章主要介绍计算机的硬件有关的技术和计算机历史。

1. [模拟电子技术](<计算机科学导论/模拟电子技术.qmd>)
1. [数字电子技术大纲](http://yjsb.ysu.edu.cn/postinfo/fudg/36sd.htm)
1. [计算机发展简史](<计算机科学导论/计算机发展简史.qmd>)
1. [计算机发展历史](http://it.icxo.com/htmlnews/2006/09/26/950083_0.htm)
1. [PC简史](<计算机科学导论/PC简史.qmd>)

## 数学基础

* [计算机数学基础](<计算机科学导论/计算机数学基础.qmd>)(注：这篇文章的公式需要用latex重写)

## 数据存储

认识计算机，掌握数据的机器内表示：如数值表示和数制、定点数和浮点数系统、有符号数的表示方法和基本运算方法、非数值数据的表示（如字符代码和图像数据）等；十进制、二进制、八进制、十六进制相互之间的转换。二进制和逻辑代数及基本逻辑门的初步认识。

1. [计算机中二进制](http://baike.baidu.com/view/18536.htm)
1. [十六进制](http://www.gonet8.com/computer/rj/200609/computer_3530.html)
1. [原码、补码和反码](http://ks.cn.yahoo.com/question/1407031701498.html)
1. [逻辑运算](<计算机科学导论/逻辑运算.qmd>)
1. [字符的编码](http://blog.csdn.net/primer_programer/archive/2007/12/26/1968027.aspx)
1. [数字的编码](<计算机科学导论/数字的编码.qmd>)

## 数据操作

认识计算机的体系构造，指令的作用和程序的构造。认识CPU和内存等核心部件的角色和作用。

1. [计算机的结构](<计算机科学导论/计算机的结构.qmd>)
1. [64位CPU](http://www.duba.net/c/2005/05/17/184970.shtml)
1. [计算机CPU演义](http://www.yesky.com/382/2382.shtml)
1. [机器语言](http://baike.baidu.com/view/111847.htm)
1. [指令](<计算机科学导论/指令.qmd>)和[程序](http://www.itisedu.com/phrase/200602281649395.html)
1. [PC](<计算机科学导论/PC.qmd>)

## 操作系统

了解操作系统的发展历史及其特点，认识操作系统的大致构造及其作用。能够帮助了解日常使用的Windows操作系统。

1. [操作系统历史](http://baike.baidu.com/view/880.htm#4)
1. [操作系统的体系结构](<计算机科学导论/操作系统的体系结构.qmd>)
1. [进程的概念](http://baike.baidu.com/view/19746.html)
1. [常见操作系统](http://tech.163.com/06/0918/09/2R9TE2J000091JUR.html)

## 网络技术

认识网络的基础构造以及以Internet为代表的主流应用，了解网络技术中核心的协议概念。认识Web的基本格式HTML的意义。

1. [网络基础](<计算机科学导论/网络基础.qmd>)
1. [Internet](<计算机科学导论/Internet.qmd>)
1. [万维网](http://wiki.ccw.com.cn/%E4%B8%87%E7%BB%B4%E7%BD%91)/[HTML](http://baike.baidu.com/view/692.htm)
1. [网络协议](<计算机科学导论/网络协议.qmd>)
1. [网络数据处理专题](<计算机科学导论/网络数据处理专题.qmd>)

## 算法

了解算法的内容和算法设计，认识算法在程序中的重要地位。了解原语以及伪代码在算法设计的表达上重要性；进一步认识算法和程序设计的相互关系。

1. [算法的概念](<计算机科学导论/算法的概念.qmd>)
1. [算法的设计和表达](<计算机科学导论/算法的设计和表达.qmd>)
1. [常用的程序结构](<计算机科学导论/常用的程序结构.qmd>)
1. [算法示例](<计算机科学导论/算法示例.qmd>)

## 程序语言

了解程序设计的思路和常用的程序设计语言，认识软件工程的内容及其作用。

1. [历史](http://blog.csdn.net/zcs001/archive/2003/10/24/21674.aspx)
1. [分类](<计算机科学导论/语言分类.qmd>)
1. [流行](<计算机科学导论/流行的语言.qmd>)
1. [发展](<计算机科学导论/语言的发展.qmd>)
1. [有关语言的评论](http://news.csdn.net/n/20071017/109652.html)

## 软件工程

1. [概念](<计算机科学导论/概念.qmd>)
1. [方法](<计算机科学导论/方法.qmd>)
1. [原型](<计算机科学导论/原型.qmd>)
1. [面向过程](<计算机科学导论/面向过程.qmd>)
1. [面向对象](<计算机科学导论/面向对象.qmd>)
1. [版权](<计算机科学导论/版权.qmd>)
1. [开源技术](<计算机科学导论/开源技术.qmd>)
1. [软件历史](<计算机科学导论/软件历史.qmd>)

## 数据抽象

1. [数据结构基础](<计算机科学导论/数据结构基础.qmd>)
1. [数据结构的实现](<计算机科学导论/数据结构的实现.qmd>)

## 数据库系统

了解数据模型、数据库管理系统以及数据库应用分类等。

1. [数据库基本概念](<计算机科学导论/数据库基本概念.qmd>)
1. [数据库系统](<计算机科学导论/数据库系统.qmd>)
1. [关系模型](<计算机科学导论/关系模型.qmd>)
1. [数据库的应用](<计算机科学导论/数据库的应用.qmd>)
1. [数据库的社会影响](<计算机科学导论/数据库的社会影响.qmd>)
1. [数据库DBA](http://www.mmmca.com/blog_dblog/p/68320.html)
1. [流行的数据库产品](http://cio.ccw.com.cn/research/info/htm2006/20060620_192192.asp)
1. [常见的数据库产品](<计算机科学导论/常见的数据库产品.qmd>)

## 高级话题

通过人工智能领域的简单介绍，让学生了解计算机的前端技术发展，引发学生对计算机技术发展的探索。

1. [人工智能](http://www.itisedu.com/phrase/200603011759495.html)
1. [机器的智能问题](http://soft.nenu.edu.cn/bcly/web/art/artshow.asp?art_id=136)
1. [推理](<计算机科学导论/推理.qmd>)
1. [人工智能一些主流技术](<计算机科学导论/人工智能一些主流技术.qmd>)
1. [Wimax](http://network.51cto.com/art/200604/25863.htm)
