---
title: "面向对象程序设计课程"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回旧版首页](首页.qmd)

## 学习资料

* [C++](<C++.html>)

## 理论课程

* [面向对象程序设计课程说明](<面向对象程序设计课程/面向对象程序设计课程说明.qmd>)
* [面向对象程序设计理论教学大纲](<面向对象程序设计课程/面向对象程序设计理论教学大纲.qmd>) （36学时）
* [面向对象程序设计理论教学大纲B](<面向对象程序设计课程/面向对象程序设计理论教学大纲B.qmd>)（54学时）
* [面向对象程序设计理论教学进度表](<面向对象程序设计课程/面向对象程序设计理论教学进度表.qmd>)
* [面向对象程序设计教材](<面向对象程序设计课程/面向对象程序设计教材.qmd>)
* [面向对象程序设计教案](<面向对象程序设计课程/面向对象程序设计教案.qmd>)（36学时）（每位老师交2章，多名老师开课，要求交不同章的教案）
* [面向对象程序设计教案B](<面向对象程序设计课程/面向对象程序设计教案B.qmd>)（54学时）（每位老师交2章，多名老师开课，要求交不同章的教案）
* [面向对象程序设计多媒体课件](<C++.html>)（每位老师交2章，多名老师开课，要求交不同章的课件）
* [面向对象程序设计作业](<面向对象程序设计课程/面向对象程序设计作业.qmd>)（1名老师上课的课程，交6份，2名老师（含）以上的，交10份，要求尽可能包含所有作业）
* [面向对象程序设计点名记录](<面向对象程序设计课程/面向对象程序设计点名记录.qmd>)（每班级）
* [面向对象程序设计试卷库](<面向对象程序设计课程/面向对象程序设计试卷库.qmd>)（至少4份）
* [面向对象程序设计期末试卷分析](<面向对象程序设计课程/面向对象程序设计期末试卷分析.qmd>)（每班级）
* [面向对象程序设计期末课程成绩](<面向对象程序设计课程/面向对象程序设计期末课程成绩.qmd>)（每班级）
* [面向对象程序设计教学研究与教学获奖](<面向对象程序设计课程/面向对象程序设计教学研究与教学获奖.qmd>)
* [面向对象程序设计课程网站](<C++.html>)
* [面向对象程序设计教学体会](<面向对象程序设计课程/面向对象程序设计教学体会.qmd>)

## 实验课程

* [面向对象程序设计实验教学大纲](<面向对象程序设计课程/面向对象程序设计实验教学大纲.qmd>) （36学时）
* [面向对象程序设计实验教学大纲B](<面向对象程序设计课程/面向对象程序设计实验教学大纲B.qmd>)（18学时）
* [面向对象程序设计实验项目运行表](<面向对象程序设计课程/面向对象程序设计实验项目运行表.qmd>)
* [面向对象程序设计实验教案](<面向对象程序设计课程/面向对象程序设计实验教案.qmd>) （36学时）（每位老师交2份，多名老师开课，要求交不同实验的教案）
* [面向对象程序设计实验教案B](<面向对象程序设计课程/面向对象程序设计实验教案B.qmd>) （18学时）
* [面向对象程序设计实验指导书](<面向对象程序设计课程/面向对象程序设计实验指导书.qmd>)
* [面向对象程序设计实验报告](<面向对象程序设计课程/面向对象程序设计实验报告.qmd>)（1名老师上课的课程，交6份，2名老师（含）以上的，交10份，要求尽可能包含所有项目）
* [面向对象程序设计实验成绩记录](<面向对象程序设计课程/面向对象程序设计实验成绩记录.qmd>)（每班级）

## 课程设计

* [面向对象程序设计课程设计教学大纲](<面向对象程序设计课程/面向对象程序设计课程设计教学大纲.qmd>)36课时
* [面向对象程序设计课程设计教学大纲20课时](<面向对象程序设计课程/面向对象程序设计课程设计教学大纲20课时.qmd>)
* [面向对象程序设计课程设计实验教案](<面向对象程序设计课程/面向对象程序设计课程设计实验教案.qmd>)36课时
* [面向对象程序设计课程设计实验教案20课时](<面向对象程序设计课程/面向对象程序设计课程设计实验教案20课时.qmd>)
* [面向对象程序设计课程设计项目运行表](<面向对象程序设计课程/面向对象程序设计课程设计项目运行表.qmd>)
* [面向对象程序设计课程设计指导书](<面向对象程序设计课程/面向对象程序设计课程设计指导书.qmd>)
* [面向对象程序设计课程设计成绩记录](<面向对象程序设计课程/面向对象程序设计课程设计成绩记录.qmd>)
* [面向对象程序设计课程设计报告](<面向对象程序设计课程/面向对象程序设计课程设计报告.qmd>)
* [面向对象程序设计课程设计点名记录](<面向对象程序设计课程/面向对象程序设计课程设计点名记录.qmd>)
* [面向对象程序设计课程设计网站](<面向对象程序设计课程/面向对象程序设计课程设计网站.qmd>)
* [面向对象程序设计课程设计教学体会](<面向对象程序设计课程/面向对象程序设计课程设计教学体会.qmd>)

## 其它

* [面向对象课程老课件](<面向对象程序设计课程/面向对象课程老课件.qmd>)

* 课程论坛 http://groups.google.com/group/study-cs

## 课程练习

* [C++实验](<C++实验.html>)
* [C++作业](<C++作业.html>)
* [C++课程设计](<C++课程设计.html>)
* [C++练习](<C++练习.html>)

## 附件

* [计算机科学与工程学院课程建设材料.doc](<面向对象程序设计课程/assets/面向对象程序设计课程/计算机科学与工程学院课程建设材料.doc>)
