---
title: "Internet"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

Internet（因特网），指的是全球公有、使用TCP/IP这套通讯协议的一个计算机系统，这个系统所提供的信息与服务，以及系统的用户。

因特网是Internet的译名，“Inter”音译为“因特”，“Net”意译为“网”。为了避免与英特尔（Intel）公司混淆，通常不译作英特网。在大陆地区常用的互联网和在港台等地多被译作-{網際網路}-，甚至被简称为网和-{網路}-（Net）都是指世界上最大的互联网络——Internet。

因特网广义上即是“联接网络的网络”。这种将计算机网络互相联接在一起的方法称为网络互联。

## 因特网的诞生

因特网始于1960年美国国防部国防前沿研究项目署（ARPA）建立的ARPANET网。1983年1月1日，ARPANET将其网络核心协议由NCP改变为当时还很新的TCP/IP协议，标志着我们今天所知道的因特网的开端。

1986年，美国国家科学基金会（National Science Foundation）建立了大学之间互联的骨干网络NSFnet，这是因特网历史上重要的一步。因特网中成功接入的比较重要的其他网络包括Usenet、Fidonet、Bitnet。

整个1990年代，因特网成功地容纳了原有的计算机网络中的大多数。这一快速发展要归功于因特网没有中央控制，以及因特网协议非私有的特质，前者造成了因特网有机的生长，而后者则鼓励了厂家之间的兼容，并防止了某一个公司在因特网上称霸。

在1994年，NSFNET转为商业运营，成为今天全世界人所共知的因特网的前身。

1987年9月20日，钱天白教授从北京向德国卡尔斯鲁厄大学发出第一封电子邮件开始，因特网正式在中国大陆地区运行。

## 今日的因特网

因特网计划的初衷便是为了使人们在更广范围内共享信息。

经过多年的发展，因特网已经在社会的各个层面为全人类提供便利。电子邮件，即时消息，网上购物等等内容已经成为越来越多人的一种生活方式；而基于B2B，B2C等平台的电子商务，跨越洲际的商务会谈以及电子政务等等为商业与政府办公创造了更加安全，更加便捷的手段

[网络数据处理专题](<网络数据处理专题.qmd>)
