---
title: "交换机"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 局域网交换机的定义

　　以太网、快速以太网、FDDI和令牌环网常被称为传统局域网，它们都是共享介质、共享带宽的共享式局域网。为了提高带宽，往往采用路由器进行网络分割，将一个网络分为多个网段，每个网段有不同的子网地址，不同的广播域，以减少网络上的冲突，提高网络带宽。微化网段已不能适应局域网扩展和新的网络应用对高带宽的需求，有人说“传统局域网已走到尽头”。

　　此后，业界推出了交换式局域网技术，能够解决共享式局域网所带来的网络效率低、不能提供足够的网络带宽和网络不易扩展等一系列问题。它从根本上改变了共享式局域网的结构，解决了带宽瓶颈问题。目前已有交换以太网、交换令牌环、交换FDDI和ATM等交换局域网，其中交换以太网应用最为广泛。交换局域网已成为当今局域网技术的主流。

　　交换机提供了桥接能力以及在现存网络上增加带宽的功能。

　　用于LAN上的交换机与网桥相似，因为它们都运作在数据链路层(第2层)的MAC子层上，都检验着所有进入的网络流量的设备地址。与网桥还有一点相似，交换机保持一张有关地址的信息表，并用该信息来决定如何过滤并转发LAN流量。

　　与网桥不同，交换机采用交换技术来增加数据的输入输出总和和安装介质的带宽。一般交换机转发延迟很小，能经济地将网络分成小的冲突网域，为每个工作站提供更高的带宽。

## 交换机类型

交换机的分类标准多种多样，常见的有以下几种：

### 根据网络覆盖范围分

局域网交换机和广域网交换机。

### 根据传输介质和传输速度划分

以太网交换机、快速以太网交换机、千兆以太网交换机、10千兆以太网交换机、ATM交换机、FDDI交换机和令牌环交换机。

### 根据交换机应用网络层次划分

企业级交换机、校园网交换机、部门级交换机和工作组交换机、桌机型交换机。

### 根据交换机端口结构划分

固定端口交换机和模块化交换机。

### 根据工作协议层划分

第二层交换机、第三层交换机和第四层交换机。

### 根据是否支持网管功能划分

网管型交换机和非网管理型交换机。
