---
title: "冯·诺依曼"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 计算机之父：冯·诺依曼

冯·诺依曼(John Von Neuman)凭他的天才和敏锐，在电脑初创期，高屋建瓴地提出了现代计算机的理论基础，从而规范和决定了电脑的发展方向。时至今日，我们所有的电脑又都叫“冯·诺依曼机器”，就是对这位数学天才最好的评价。

对于冯·诺依曼来说，人类第一台电脑造了一半时才参与开发，多少有些遗憾。但是，他刚好在那大机器程序存储问题无法解决的关键时刻出现，这使得冯·诺依曼的天才得到淋漓尽致的发挥。他明确指出：一定要彻底实现程序由外存储向内存储的转化，原有的设计必须作修改，经费不够再追加。在冯·诺依曼的影响下，整个研制工作取得了突破性的进展。冯·诺依曼提出了新的改进方案：一是用二进制代替十进制，进一步提高电子元件的运算速度；二是存储程序(Stored Program)，即把程序放在计算机内部的存储器中，换言之，把能进行数据处理的程序放在数据处理系统内部，程序和该程序处理的数据用同样的方式储存，即把程序本身当作数据来对待。冯·诺依曼的改进方案被称为“爱达法克”(EDVAC)，即离散变量自动电子计算机(Electronic Diserete Variable Computer)的简称。

1945年6月，他写了一篇题为《关于离散变量自动电子计算机的草案》的论文，第一次提出了在数字计算机内部的存储器中存放程序的概念(Stored Program Concept)，这是所有现代电子计算机的范式，被称为“冯·诺依曼结构”。按这一结构建造的电脑称为存储程序计算机(Stored Program Computer)，又称为通用计算机。时至今日，所有的电脑都逃脱不了冯·诺依曼的掌心，我们所有的电脑，都有一个共同的名字，叫“冯·诺依曼机器”，它超越了品牌、国界、速度和岁月。

### 保留观点：谁的发明？

将某项发明的荣誉授予个人常常受到争议。人们将白炽灯的发明归于爱迪生，其他研究人员也曾研制了类似的灯泡，从某种意义上说，他只是比较幸运地获得专利。这样的事情不胜枚举，对于这些发明，自然被人定的发明人是有权被授予荣誉的。可是也有一些情形，历史所给予的荣誉是不恰当的，如存储程序的概念。无疑，约翰.冯诺依曼(John von Neumann)是一位非常卓越的科学家，但是，历史将存储程序的概念荣誉归结于他，就这个思想而言，最早提出的应该是宾夕法尼亚大学摩尔电子工程学院的J.P.Eckert小组研究人员提出来的。John von Neumann不过是第一个在著作中转述这一思想的人，由此，计算机界选择他作为发明人。
