---
title: "数据库系统"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 什么是数据库系统？

是一个实际可运行的存储、维护和应用系统提供数据的软件系统，是存储介质、处理对象和管理系统的集合体。它通常由数据库、数据库管理系统(软件)和数据管理员组成。其软件主要包括操作系统、各种宿主语言，实用程序以及数据库管理系统。

* **数据库是依照某种数据模型组织起来并存放辅助存储器中的数据集合。**这些数据为多个应用服务，独立于具体的应用程序。
* 数据库由数据库管理系统统一管理，数据的插入、修改和检索均要通过数据库管理系统进行。
* 数据库管理系统是一种系统软件，它的主要功能是维护数据库并有效地访问数据库中任意部分数据。对数据库的维护包括保持数据的完整性、一致性和安全性。
* 数据管理员负责创建、监控和维护整个数据库，使数据能被任何有权使用的人有效使用。数据库管理员一般是由业务水平较高、资历较深的人员担任。

数据库系统的个体含义是指一个具体的数据库管理系统软件和用它建立起来的数据库；它的学科含义是指研究、开发、建立、维护和应用数据库系统所涉及的理论、方法、技术所构成的学科。在这一含义下，数据库系统是软件研究领域的一个重要分支，常称为数据库领域。

* [数据库研究](<../数据库研究.html>)跨越于计算机应用、系统软件和理论三个领域，其中应用促进新系统的研制开发，新系统带来新的理论研究，而理论研究又对前两个领域起着指导作用。数据库系统的出现是计算机应用的一个里程碑，它使得计算机应用从以科学计算为主转向以数据处理为主，并从而使计算机得以在各行各业乃至家庭普遍使用。在它之前的文件系统虽然也能处理持久数据，但是文件系统不提供对任意部分数据的快速访问，而这对数据量不断增大的应用来说是至关重要的。为了实现对任意部分数据的快速访问，就要研究许多优化技术。这些优化技术往往很复杂，是普通用户难以实现的，所以就由系统软件（数据库管理系统）来完成，而提供给用户的是简单易用的数据库语言。由于对数据库的操作都由数据库管理系统完成，所以数据库就可以独立于具体的应用程序而存在，从而数据库又可以为多个用户所共享。

因此，数据的独立性和共享性是数据库系统的重要特征。数据共享节省了大量人力物力，为数据库系统的广泛应用奠定了基础。数据库系统的出现使得普通用户能够方便地将日常数据存入计算机并在需要的时候快速访问它们，从而使的计算机走出科研机构进入各行各业、进入家庭。

## 数据库系统的产生和发展

众所周知，数据库系统并不是在计算机产生的同时就出现的，而是随着计算机技术的不断发展，在特定的历史时期、特定的需求环境下出现的。人类在1946年发明了世界上的第一台计算机到20世纪60年代这漫长的20年里，计算机操作系统还主要局限于文件的操作，同样，对数据的管理也主要是通过文件系统来实现。进行计算所需要的各种数据存放在各自的文件里面。当要使用这些数据的时候，将文件打开，读取文件中的数据到内存中。当计算完毕后，将计算结果仍旧写入到文件中去。
虽然这种在文件中存放数据的方式目前在很多系统中还在使用，但是，这样的数据存放方式在三四十年前的当时，就已经显示出了非常明显的不足。这些不足主要集中在无法对数据进行有效的统一管理。

### 文件管理的缺点：

* 程序员编写应用程序非常不方便。

应用程序的设计者需要对程序所使用的文件的逻辑结构和物理结构都了解的非常清楚。而计算机操作系统只提供将文件打开、关闭、保存等非常低级的操作，而对数据的修改、查询操作则需要应用程序来解决，如果程序所需要的数据存放在不同的文件里，而且这些文件的存储格式又迥然不同。这样就给应用程序的开发带来了巨大的麻烦，程序员要为程序中所用到的每一个文件都写好相应的接口，而且不同的文件格式相差很大，这样就大大的增加了编程的工作量，从而使得在文件级别上开发应用程序的效率非常低下，严重影响应用软件的发展。

* 结构和程序的依赖

文件结构的每一处修改都将导致应用程序的修改，
从而使得应用程序的维护工作量特别大。编过程序的人都有这种体会，就是每当自己开发完毕的程序需要修改的时候，又不得不将源程序重新修改、编译、链接。其麻烦程度可想而知。因为有人戏称编程人员为“老改”人员，个中滋味，外人恐怕很难体会到的。
计算机操作系统中的文件系统一般不支持对文件的并发访问。而在现代计算机系统中，为了充分发挥计算机系统的资源使用效率，一般都允许多个程序“同时”运行，即并发性。对数据库系统同样有并发性的要求，现在比较大型的数据库都有非常强的并发访问机制，这样可以充分利用数据库服务器的软、硬件资源，避免浪费。

* 管理混乱

由于基于文件系统的数据管理缺乏整体性、统一性，在数据的结构、编码、表示格式等诸多方面不能做到标准化、规范化，不同的操作系统有风格迥异的表示方式，因此在一定程度上造成了数据管理的混乱。另外，基于文件系统的数据管理在数据的安全性和保密性发面难以采取有效的措施，在一些对安全性要求比较高的场合，这种安全上的缺陷是完全不允许的。

针对文件系统的这些重要缺点，人们逐步发展了以统一管理数据和共享数据为主要特征的系统，这就是[数据库系统](<数据库系统.qmd>)。数据库系统就是在这样的背景下发展起来了。1964年，美国通用电气公司开发成功了世界上的第一个数据库系统——IDS(Integrated Data Store)。IDS奠定了网状数据库的基础，并且得到了广泛的发行和应用，成为数据库系统发展史上的一座丰碑。1969年，美国国际商用机器公司（IBM）也推出世界上第一个层次数据库系统IMS（Information Management System），同样在数据库系统发展史上占有重要的地位。

七十年代初，[E.F.Codd](<../E.F.Codd.html>)在总结前面的层次、网状数据库优缺点的基础上，提出了[关系数据模型](<../关系数据模型.html>)的概念。他提出了关系代数和关系演算（直到今天，在E.F.Codd的这些基本理论还在左右这数据库系统的发展，也依然是高校计算机专业课堂上所要讲述的重要内容）。在整个七十年代，关系数据库系统无论从理论上还是实践上都去的了丰硕的成果。在理论上，确立了完整的关系模型理论、数据依赖理论和关系数据库的设计理论（在后面将重点讲述这些关系数据库的基本理论）；在实践上，世界上出现了很多著名的关系数据库系统，比较著名的如System R，INGRES，[Oracle](<../Oracle.html>)等。

和文件系统相比，数据库系统有一系列的特点，具体表现在以下几个方面：

### 数据库管理的优点

* 数据库系统向用户提供高级的接口。

在文件系统中，用户要访问数据，必须了解文件的存储格式、记录的结构等。而在数据库系统中，这一切都不需要了。数据库系统为用户处理了这些具体的细节，向用户提供非过程化的数据库语言（即通常所说的SQL语言），用户只要提出需要什么数据，而不必关心如何获得这些数据。对数据的管理完全由数据库管理系统（DBMS: Database Management System）来实现。

* 查询的处理和优化。

查询通常指用户向数据库系统提交的一些对数据操作的请求。由于数据库系统向用户提供了非过程化的数据操纵语言，因此对于用户的查询请求就由DBMS来完成，查询的优化处理就成了DBMS的重要任务。

* 并发控制。

前面曾经提到，文件系统一般不支持并发操作，这样大大的限制了系统资源的有效利用。在数据库系统中，情况就不一样了。现代的数据库系统都有很强的并发操作机制，多个用户可以同时访问数据库，甚至可以同时访问同一个表中的不同记录。这样极大的提高了计算机系统资源的使用效率。

数据的完整性约束。凡是数据都要遵守一定的约束，最简单的一个例子就是数据类型，例如定义成整型的数据就不能是浮点数。由于数据库中的数据是持久的和共享的，因此对于使用这些数据的单位来说，数据的正确行显得非常重要。在关系数据库系统中，比较重要的完整性约束有实体完整性、域完整性、参照完整性和用户自定义的完整性等，在后面的文章中将有重点讲述。

进入二十世纪八十年代之后，计算机硬件技术有了飞速的提高。计算机技术的提高促使计算机应用不断深入，产生了许多新的应用领域，例如计算机辅助设计、计算机辅助制造、计算机辅助教学、办公自动化、智能信息处理、决策支持等。这些新的领域对数据库系统提出了新的要求。但是由于应用的多元化，不能设计出一个统一的数据模型来表示这些新型的数据及其相互关系，因而出现了百家争鸣的局面，产生了演绎数据库、面向对象数据库、分布式数据库、工程数据库、时态数据库、模糊数据库等新型数据库的研究和应用。
不过到目前为止，在世界范围内得到主流应用的还是经典的关系数据库系统，[比较知名](<../流行的数据库产品.html>)的如[Sybase](<../Sybase.html>)，[Oracle](<../Oracle.html>)，[Informix](<../Informix.html>)，[SQL Server](<../SQL Server.html>)，[DB2](<../DB2.html>)等。
