---
title: "数据库产品发展趋势"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

在最近的一两年间，随着数据库技术的发展,更高性能CPU的问世,用户对数据库的性能的关注度在下降，但对于数据库产品的可靠性、与业务的整合性及采用新产品总体拥有成本（TCO）的要求则日趋增加。换言之，购买者的选择将取决于产品的整体性能、易使用性和价格优势，这才是一个在新的激烈战场中的制高点。

　　数据库技术的发展，也呈现除了一些新的趋势。

## 提供持续的数据可用性

　　构建一个高可用性 IT 基础架构,对所有希望在当今瞬息万变的经济环境中立于不败之地并取得成功的企业而言都至关重要。

　　作为数据库市场的领跑者,Oracle在其最新的10g数据库版本中增强了RAC技术。微软公司在其最新的数据库SQL Server 2005中利用数据库镜像、故障转移群集和改进联机操作等特性,可将故障时间控制到最低，并有助于确保企业系统随时接受访问调用。

　　

## 用低成本实现系统的伸缩性

　　大多数企业的每个主要应用系统都拥有专门的存储器和服务器,这样传统的布署，个别看好像效果不错。但这样做的后果就是必须付出高昂的代价，来满足大量系统的维护，而且因故障节点的增多，系统更容易出现故障。

　　此外，由于单个系统必须有足够的规模以适应高峰容量，但资源却难以从一个系统转移到另一个系统，结果导致企业存储器和 CPU 资源大量闲置。分析家认为，目前企业内部一般的存储器的利用率仅为 50%，而 CPU 利用率则是可怜的15-20%。

　　

## 保证互联网架构下的安全

　　企业将应用架构在互联网平台上，都面临如何保护互联网架构下的数据安全问题。各大数据库厂商嗅到其中的巨大商机，加强了其数据库产品在数据安全上的支持。

　　甲骨文公司在其10g版本中提供的存储数据加密、虚拟私有数据库、Label Security等技术;微软的SQL server 2005通过数据库加密、缺省安全设置、口令策略实施、粒度权限控制和强化安全模型等功能特性为企业数据提供最高层次的安全保障，就是其中的佼佼者。

　　

## 集成商业智能功能

　　大多数企业中，商业智能应用程序的部署是沿着技术线路划分的。不太复杂的报表和即席查询工具的部署通常使用的是数据仓库和基于 SQL 的报表工具，而较复杂的分析和计划应用程序的部署则是使用其他特殊的数据库和工具。

　　各大厂商除了纷纷加强了其联机分析产品，报表工具，ETL工具的功能外，更试图将这些东西集成在一个完整的数据库平台中。使数据库产品不再仅仅是提供一般的数据存贮功能，而能提供从数据存贮到数据分析使用的整体解决方案。

　　

## 简化数据库的管理

　　今天，业务环境的竞争日趋激烈，如何以最低的成本，同时不以降低服务水平为代价，管理信息技术（IT）基础设施是企业目前面临的挑战。

　　越来越多的用户希望数据库产品能自我管理,可以自动地对自身进行监控、适应和调整，从而显著减少了IT管理人员的数量，降低了管理成本整合能力
