---
title: "数据库研究"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

数据库技术，历经三十多年的变迁和发展，其应用领域非常广泛，已经构成信息系统的基础和核心，同时进入了高级发展阶段，目前主要的发展特征：广义的分布式体系、面向对象的数据库技术和各种新型的数据库系统。本质上，数据库技术仍然处于以关系模型为核心的技术阶段，不过在扩展、技术综合和集成等方面不断地得到进化，发展的要素取决于：

* 1)硬件和软件的环境，数据库系统所基于技术的发展，包括操作系统、基本处理能力、存储技术、网络技术等；
* 2)应用需求，从最初的科学计算到当今各种新兴应用领域，如地理信息系统、工程数据库、多媒体数据库，演绎数据库/人工智能知识库等等，都在很大程度上驱使了数据库技术的发展需求。

本研究方向侧重应用需求，主要有三个方面：

## 1) 理论和技术基础的研究

逻辑推理的知识库技术、进行数据分析的联机分析处理、数据仓库的设计技术和[数据挖掘](<数据挖掘.qmd>)技术，包括机器学习、模糊集合、粗糙集合、人工神经网络、演化计算、分布式计算等，以及相关规范和标准的研究。
网格、对等计算等新架构下，XML数据管理和Web服务研究。

## 2)应用基础架构研究

面向数据库系统的集群体系以及网格环境的构建，应用模式分析、服务体系、运行优化、效用评测等。
对等和普适（Pervasive Computing）计算架构的研究，真正代表着internet体系的未来发展。
开源数据库系统软件架构的研究和嵌入式的应用的基础研究。

## 3) 应用模式研究

应用模式研究遵从应用现实，结合了地方及其行业的服务需求。

### a.数字城市的基础架构

以电子政务为龙头的部门数据库建设和数据整合，基于部门和区域合作的分布处理的异构数据架构(包括数据仓库)的集成研究和开发，数据库安全通讯。

### b.行业数据库的构造应用研究

面向轻工发展特色的，如低压电器、汽摩配、轻工机械等行业的工程数据库构造和系统应用；
行业的电子商务发展，基础服务架构和商务的分析和辅助决策系统的设计和开发。

### c. 现代教育信息资源体系

一切数字化教育资源的标准化（如基于XML的IEEE相关标准）和集成，以及基于资源体系的教学平台的应用研究。

### d. 网络数据的采集和应用

网络数据是目前增长最快的数据对象，研究基础采集技术，包括校园网络系统、部门网络系统，采用当代综合的数据挖掘技术(机器学习/数据库技术/统计技术)，应用的主要目的：复杂的系统安全分析、用户的行为分析等；
面向internet的web数据库技术(WWW数据库)，internet是一个复杂的异构的分布式广义数据库，研究的内容包括：搜索引擎基础技术、知识库（语义库）构造、过滤和分类等。

### e.科学研究基础数据

蛋白数据库、基因数据库、地理信息等构建和分析研究。
