---
title: "模拟电子技术"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

模拟电子技术是电气信息类（包括原电气类、电子类）、自控类等专业的学生在电子技术方面必学的入门性质的基础知识。模拟电子技术有以下几方面的特点：

1. 规律性

　　电子电路是由电子器件和电阻、电容等电路元件按照一定的规律组合而成的，各种复杂的电子电路也都是由若干种基本电子电路组合而成，因此学习时要求熟记一些基本电子电路的结构和特性，并掌握它们的组合规律。

1. 非线性

　　由于电子线路具有非线性特性，所以必须采用非线性电路的分析方法来分析电子线路。常用的有图解分析法和模型分析法。

1. 工程性

　　对于电子线路的分析与设计，采用精确的分析计算难度较大，往往不必要。因为电子器件的特性和参数分散性较大，而电路元件的参数也有一定的误差，因此工程上通常是先采用近似计算法对电路进行粗略的估算，然后通过实验调试来达到预定的设计要求。

1. 实践性

　　模拟电子技术是一项实践性很强的技术，这主要是因为影响电子电路工作的因素往往非常复杂，难以用简单的模型加以全面而精确的模拟。

## 电子技术发展的四个阶段

1. 1906年电子管的问世和1948年晶体管的发明，揭开了电子电路的设计阶段；

电子管是电子器件的第一代，在晶体管发明以前的近半个世纪里，电子管几乎是各种电子设备中唯一可用的电子器件。电子技术随后取得的许多成就，如电视、雷达、计算机的发明，都是和电子管分不开的。

但电子管在体积、功耗、寿命等方面存在局限性。1948年，贝尔实验室宣布研制成晶体三极管。初期的晶体管是点触式的，制造比较困难，稳定性较差，但它毕竟是时代的标志。1957年，贝尔实验室的D.斯帕克斯发明面结型晶体管，克服了点触式晶体管的缺点，使得问世不久的晶体管的地位巩固下来。晶体管的发明将电子技术推向了一个新的阶段。电子技术在以后取得的许多成就，如集成电路、微处理器和微型计算机等，都是从晶体管发展而来的。

1. 1958年集成电路（IC）的诞生，跨入了新一代电路的逻辑设计阶段；

1958年，美国得克萨斯仪器公司宣布一种集成的振荡器问世，首次把晶体管和电阻、电容等集成在一块硅片上，构成了一个基本完整的单片式功能电路。 1961年，美国仙童公司宣布制成一种集成的触发器。从此，集成电路获得了飞速的发展。集成电路的发明开创了集电子器件与某些电子元件于一体的新局面，使传统的电子器件概念发生了变化。这种新型的封装好的器件体积和功耗都很小，具有独立的电路功能，甚至具有系统的功能。集成电路的发明使电子技术进入了微电子技术时期，是电子技术发展的一次重大飞跃。

1. 1975年以后超大规模集成电路（VLSI）的推出，将电子技术引向IC的系统设计与相关的软件设计阶段；

1. 面向21世纪的以微电子为基础、以计算机和通信为媒体的新阶段。

## 两个概念与两个定理

1. 信号及其分类

　　信号是信息的载体。由于信号为时间t的函数，故按照t的连续或离散，将信号分为连续信号与离散信号。
　　对于连续信号，当函数值f(t)连续时，称为模拟信号；而当函数值f(t)离散时，称为量化信号。
　　对于离散信号，当函数值f(t)连续时，称为抽样信号；而当函数值f(t)离散时，称为数字信号。

1. 线性电路和非线性电路

　　参数与电压、电流无关的元件称为线性元件（如R、L、C）。
　　由电源和线性元件组合而成的电路，属于线性电路。线性电路的方程是线性代数方程或线性微分（积分）方程。不能用线性方程来描述其特性的电路称为非线性电路，例如大部分含电子器件的电路就属于非线性电路。

1. 叠加定理

　　线性电路中任一支路的电流等于各个源单独作用下所产生的电流之和，称为叠加定理。这里所说的源单独作用，是指对应的其它源应视为零值，即独立电压源短路，独立电流源开路，而全部受控源则必须保留。

　　叠加定理不仅适用于支路电流，也适用于电路任意两点间的电压，因为任意两点间的电压总是可以表示为支路电流的线性组合。

1. 戴维南定理

　　1883年，法国人戴维南提出"任一复杂的集总参数含源线性时不变二端网络可等效为一个简单的二端网络"。由于1853年德国人亥姆霍兹也曾提出过，因而又称亥姆霍兹－戴维南定理。

　　任一线性有源一端口网络，对其余部分而言，可以简化为一个电压源Vs和电阻Ro相串联的电路。Vs的大小等于该一端口网络的开路电压，Ro等于该一端口网络内所有独立源均为零值时从端口视入的电阻。

使用戴维南定理时，有两个问题必须注意：

* 由戴维南定理所得的等效电路，仅对网络的外部电路等效，亦即只适用于计算外部电路的电压和电流，而不适用于计算网络内部的电压和电流。
* 只要一端口网络内部是线性的，外部电路即使是含有非线性元件的非线性电路，戴维南定理同样适用。

　　一个包含独立源而不包含受控源的一端口网络，如果控制和被控制的电压、电流都是一端口网络内部的量，与外部电路没有互控关系，则这个一端口网络可以简化为一个电阻。
　　（叠加定理和戴维南定理是线性电路两个非常重要的定理，一定要熟练掌握。）

## 参考资料

* http://siee.cumt.edu.cn/netcollege/analog/Chap01/Chap1.htm
