---
title: "网络基础"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 网络概念

计算机网络是用通信线路和通信设备将分布在不同地点的多台自治计算机系统互相连接起来，按照共同的网络协议，共享硬件、软件和数据资源的系统。

## 实现网络的四个要素：

* 1、通信线路和通信设备
* 2、有独立功能的计算机
* 3、网络软件软件支持
* 4、实现数据通信与资源共享

## 网络分类

### 根据范围网络分类

1. 局域网(LAN)
1. 广域网(WAN)---MAN(城域网)

### 基于通讯设备的连接方式

即拓扑构造

* 环型Ring
* 总线型Bus
* 星型Star
* 混合(Irregular)

### 根据网络的设计策略

* 专用网(封闭的)—如银行系统、政府系统
* 开放网---现在主要指面向Internet开放的

### 按计算机IP类型不同分类

* 私用网络：私用网络内部的计算机网络，处于私有网络计算机不能直接与公网计算机会话；
* 公共网络 ：也被称为Internet。处于公网的计算机可以进行对话；

ICANN （Internet Corporation For Assigned Names and Numbers）也就是Internet 名称与编号分配组织，这个组织对IP地址实行编号，它规定如下的一些地址做为保留地址，以供私有网络使用，这个私用的网络也可以称为本地网；

为私用网络而保留的IP地址：
```
10.0.0.0 － 10.255.255.255
172.16.0.0 － 172.31.255.255
192.168.0.0 －192.168.255.255
```

私用网络计算机有是根据私用IP地址来确定，这些IP地址所对应的计算机是不能直接与Internet对话的，处于私用网络连接到Internet（公网），要通过NAT来实现。如果您的网络只有一台计算机，可能是通过拔号上网，比如通过Modem 或ADSL拔号等；

如果您的私用网络有很多台计算机，想让这些计算机都能访问公网，那就需要NAT（Network Address Translation）——网络地址转换，通过NAT会把私有网络计算机的IP地址转换成一个公网的IP地址，这样私用网络就可以和公网的计算机通信会话了；

目前电子市场有很多NAT产品，当然我们可以自己做NAT，只是花一点时间而已。在市场上卖的NAT产品，只是需要我们点鼠标来操作，看起来方便一点。

### 按应用方式

* [客户-服务器](<客户-服务器.qmd>)
* [对等模式](<对等模式.qmd>)
* [分布式系统](<分布式系统.qmd>)

## 网络设备

* [网络设备](http://tech.china.com/zh_cn/netschool/net/base/167465/20010326/153247.html)

### 主要的网络连接设备有

* [中继器](<中继器.qmd>)
* [集线器](<集线器.qmd>)
* [交换机](<交换机.qmd>)
* [网桥](<网桥.qmd>)
* [路由器](<路由器.qmd>)
* [网关](<网关.qmd>)

### 其他网络设备(安全、配合)

* [防火墙](http://www.allwiki.com/wiki/%E9%98%B2%E7%81%AB%E5%A2%99)
* [入侵检测系统](http://baike.baidu.com/view/20936.html)
* [网闸](<网闸.qmd>)
* [防毒墙](http://wiki.ccw.com.cn/%E9%98%B2%E6%AF%92%E5%A2%99)

## 补充说明

* [交换机、集线器、路由器区别和使用浅谈](http://publish.it168.com/2004/0518/20040518010001.shtml)
* [网桥与路由器的区别](http://fanqiang.chinaunix.net/a3/b2/20010620/110000601.html)
* [路由和交换概念](http://www.haodf.net/internet/network/route/200609/150676.html)
