---
title: "计算机导论实验大纲"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

**《计算机科学导论》实验教学大纲**

一、课程中文名称(课程英文名称)：计算机科学导论实验（Experiment of Introduction to Computer Science ）

二、课程编码：1421221009

三、课程目标和基本要求：

计算机科学导论课程是计算机专业的入门必修课程，也是了解信息技术的概貌性课程。由于信息技术的应用价值，实践性教学是学生引导了解学科和通过感性认识来培养学生对专业的了解和兴趣的有效方式。

本课程通过上机实验，使学生真正掌握计算机的基本操作方法，具备使用计算机的基本能力。学生通过对各部分实验的具体操作练习，能够熟练使用操作系统，熟练地使用一些常用的应用软件和基本的信息检索和信息交流能力。通过实验，可以对课堂所学的内容得到深刻的理解，为今后在广泛的计算机专业各种课程的学习和应用实践打下必要的基础。

**注：**下述的实验环境有条件时，可以采用开源的技术方案实施，如Linux、OpenOffice、FireFox、Telnet、gedit、vi、KftpGrabber等组合。

四、课程总学时： 48 学时(严格按教学计划时数)[理论： 32 学时；**实验： 16 学时**]

五、课程总学分: 2.5 学分(严格按教学计划学分)

六、适用专业和年级：信息管理与信息系统专业、计算机科学与技术专业，07级学生

七、实验项目汇总表(实际教学中进行必要的组合和筛选)：

| 序号 | 实验编号 | 实验名称 | 时数 | 实验类别 | 实验类型 | 实验要求 | 每组人数 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 实验一 | 142122100901 | 了解个人计算机结构 | 2 | 专业基础 | 演示性 | 必修 | 1 |
| 实验二 | 142122100902 | 操作系统基本应用 | 2 | 专业基础 | 验证型 | 必修 | 1 |
| 实验三 | 142122100903 | 文字编辑与排版 | 2 | 专业基础 | 验证型 | 必修 | 1 |
| 实验四 | 142122100904 | 电子表格的基本应用 | 4 | 专业基础 | 验证型 | 选修 | 1 |
| 实验五 | 142122100905 | 演示文稿的制作 | 2 | 专业基础 | 验证型 | 选修 | 1 |
| 实验六 | 142122100906 | Html语言编写入门 | 2 | 专业基础 | 验证型 | 必修 | 1 |
| 实验七 | 142122100907 | 网络技术基本应用 | 2 | 专业基础 | 验证型 | 选修 | 1 |
| 实验八 | 142122100908 | 数据库基础入门 | 2 | 专业基础 | 验证型 | 必修 | 1 |
| 实验九 | 142122100909 | 搜索引擎的应用 | 2 | 专业基础 | 验证型 | 选修 | 1 |
| 实验十 | 142122100910 | 计算机技术探索专题 | 2 | 专业基础 | 综合型 | 必修 | 6-10 |

说明：计算机导论实验共有十个实验项目，含有6个必须实验项目计12学时，4个选修实验项目，根据实际情况，任课教师需要从4个选修实验项目中指定2个实验项目供学生在实验课中完成，剩余的2个选修项目可让学生在课外完成，以保证本课程实验达到16学时。

**八、大纲内容：**

**实验一 了解个人计算机结构**

**[实验目的和要求]注**

1、熟悉个人计算机的主要构造

2、熟悉个人计算机的主要部件功能和作用

3、了解主板的布局和认识主要器件

**[实验内容]**

1、教师先概要介绍一般个人计算机的组成知识

2、示范拆开一个计算机

3、分批讲解主板布局和主要器件的名称及其作用

4、各个计算机部件的认识说明

**[主要实验仪器与器材]**

1、个人计算机

**实验二 操作系统基本应用**

**[实验目的和要求]**

1、熟练掌握Windows操作系统的启动与退出

2、熟悉Windows操作系统桌面、窗口、菜单及任务栏的组成与基本操作

3、熟练掌握应用程序的启动和退出方法

4、掌握剪贴板的使用方法

5、了解Windows操作系统的联机帮助

**[实验内容]**

1、启动Windows，观察桌面的组成，认识应用程序和图标

2、窗口和菜单的基本操作

3、通过不同方法启动应用程序

4、进行输入法切换和输入练习

5、使用联机帮助系统，查找相关内容

6、退出Windows

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

**实验三　文字编辑与排版**

**[实验目的和要求]**

1、要求熟悉Windows环境的基本操作

2、掌握文字处理软件的基本编辑功能

3、掌握文字处理软件的排版技术

**[实验内容]**

1、Word基本操作，包括启动、退出、文档的建立、文字字符输入、文字编辑、格式设置、查找替换、文件保存等

2、设置分栏，设置打印页面格式，打印预览等

3、Word中表格操作，表格的建立、表格中文字的输入、表格编辑等

4、对象的插入，如插入图片、编辑图片、插入艺术字、输入公式等

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、Microsoft Word(Office)

**实验四 电子表格的基本应用**

**[实验目的和要求]**

1、掌握电子表格软件的基本操作

2、掌握工作表中数据的输入和基本编辑方法

3、学会数据分析的一般方法

4、学会图表的建立和编辑方法

**[实验内容]**

1、Excel的启动、退出；工作簿的建立、打开、保存；工作表中数据的输入与编辑；公式的输入；函数的使用等

2、单元格的操作，包括单元格的插入、删除、移动、复制等；工作表的排版

3、工作表的编辑，包括工作表的插入、删除、移动、复制

4、数据管理与分析，记录的排序、筛选和分类汇总；透视表的建立和使用

5、数据图表建立、编辑

6、页面设置与打印，使用预览查看打印效果

7、Word与Excel资源共享

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、Microsoft Excel(Office)

**实验五 演示文稿的制作**

**[实验目的和要求]**

1、掌握演示文稿的基本操作(启动和退出)

2、掌握演示文稿多媒体的使用和文字编排

3、掌握演示文稿的编辑、效果设置和管理

**[实验内容]**

1、PowerPoint的启动和退出

2、创建、打开和保存演示文稿

3、演示文稿视图的使用，幻灯片的制作、文字编排、图片和图表插入及模板的选用

4、幻灯片的手稿和删除，演示顺序的改变，幻灯片格式的设置，幻灯片放映效果的设置，多媒体对象的插入，演示文稿的打包和打印

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、Microsoft PowerPoint(Office)

**实验六 Html语言编写入门**

**[实验目的和要求]**

1、学习一些基本的html概念；

2、html基本标记、字型控制，表格格式排版处理

3、编写简单的网页；

**[实验内容]**

1、html总体构造设计

2、练习主要标记&lt;html&gt;、&lt;title&gt;、&lt;head&gt;、&lt;body&gt;、&lt;h1&gt;、&lt;table&gt;、&lt;row&gt;、&lt;col&gt;

3、编写及控制表格

4、编写个人情况介绍网页

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、网页编辑工具(记事本、ultraedit、emeditor等)

4、Web游览器(测试和平常应用)

**实验七 网络技术基本应用**

**[实验目的和要求]**

1、熟悉计算机网络的基本原理和类型

2、掌握网络资源的基本共享技术

3、掌握互联网技术的基本应用

**[实验内容]**

1、Windows网络协议的配置和共享资源的设置

2、网络基本工具的运用(如ping、netstat、telnet)

3、用IE或Firefox进行网上信息浏览和检索

4、利用工具(游览器或者Foxmail或Outlook等邮件客户端)收发电子邮件

5、简单服务器的架设和测试

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、网络环境(局域网络、互联网)

**实验八 数据库基础入门**

**[实验目的和要求]**

1、掌握简单数据库产品的功能、运行环境、启动和退出

2、掌握数据库和数据表的创建

3、掌握数据库基本操作

4、掌握数据库基本查询方法

**[实验内容]**

1、Access的启动和退出

2、数据库和数据表的创建、打开、修改和保存

3、查询对象的创建、打开、修改和保存

4、数据库的导入和导出

**[主要实验仪器与器材]**

1、个人计算机

2、Windows操作系统

3、Microsoft Access(Office)

**实验九搜索引擎的应用**

**[实验目的和要求]**

1、理解搜索引擎基本概念

2、了解搜索引擎分类

3、掌握常用搜索引擎平台的使用

**[实验内容]**

1、常用搜索引擎(包括元搜索引擎)

2、搜索技术运用

3、高级检索(时间、类型、多条件组合等)

**[主要实验仪器与器材]**

1、Internet支持环境

2、Web游览器

**实验十 计算机技术探索专题**

**[实验目的和要求]**

1、计算机导论背景知识的运用

2、培养综合的信息搜索能力

3、阅读技术文章和写作的能力

4、计算机基本操作技术的运用

5、培养科学技术研究的分工协作能力

**[实验内容]**

1、自由组合数人成一组，每组选出一位组长

2、根据所学的课本内容自由选定计算机科学方面一个专题

3、利用所学的知识，包括网络搜索技巧研究所选的专题。由组长安排，要求每个成员独立承担一部分研究内容。最后经讨论形成小组共同研究报告

4、每个小组集体制作研究报告的多媒体课件

5、实验课上，每个小组用十分钟作相关专题的报告

**[主要实验仪器与器材]**

1、PC机

2、投影仪

九、主要实验教材（指导书）及参考用书：

教 材：

1、实验教材：《计算机科学导论实验手册》 自编

参考书：

1、《大学计算机文化基础》胡维华主编 浙江科技出版社 2004年

2、《大学计算机基础上机实验指导与测试》第四版 杨振山，龚沛曾主编，高等教育出版社，2004年
