---
title: "计算机导论理论教学大纲"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 《计算机科学导论》理论教学大纲

## 课程概要

\*课程名称：计算机科学导论（Introduction to Computer Science）
\*课程代号：1421221009
\*学分/总学时：2.5/48
\*开课单位：计算机科学与工程学院
\*面向专业：计算机科学与技术

## 一、课程的性质、目的和任务

计算机科学导论是计算机科学与技术及相关专业的重要专业基础课程。计算机科学不但是一个基础学科，更重要的是一门面向应用的技术与工程的学科。因此，在兼顾其理论的核心基础同时，考虑计算机科学技术应用驱动的发展特征。
课程内容涉及计算机科学的方方面面，但着重讲解的是基本概念而不是数学模型和技术细节，采用广度优先的教学理念。课程的重点在于叙述计算机科学体系的框架，传播计算机科学的基础知识，为今后深入学习信息专业各专业理论课程做好铺垫；通过教学，使学生了解计算机系统的基本构造，掌握计算机技术的相关理论和技术的基本概念，了解计算机技术的广泛性及其应用特点。为学生后续的专业课程学习打下重要的基础。

## 二、学习本课程学生应掌握的前设课程知识

计算机使用基础和经验有助于本课程教学效果的发挥。

## 三、学时分配

课程授课时间为48学时，其中讲课32学时，实验16学时

| 章节 | 理论学时 |
| --- | --- |
| 第0章 | 4 |
| 第一章 | 4 |
| 第二章 | 4 |
| 第三章 | 2 |
| 第四章 | 4 |
| 第五章 | 2 |
| 第六-七章 | 4 |
| 第八章 | 4 |
| 第九章 | 2 |
| 第十章 | 2 |
| 合计 | 32 |

## 四、课程内容和基本要求

### 1．导引 ( 4学时)

\*[1]计算机的发展史
\*[2]计算科学的特点
\*[3]社会影响

基本要求：

了解计算机科学的背景	和本课程的大致内容，了解计算机技术和社会伦理的密切关系，初步认识算法在学科中的地位。

### 2．数据存储( 4学时)

\*[1]计算机中二进制
\*[2]原码、补码和反码
\*[3]逻辑运算
\*[4]计算机的编码

基本要求：

认识计算机，掌握数据的机器内表示：如数值表示和数制、定点数和浮点数系统、有符号数的表示方法和基本运算方法、非数值数据的表示（如字符代码和图像数据）等；十进制、二进制、八进制、十六进制相互之间的转换。二进制和逻辑代数及基本逻辑门的初步认识。

### 3．数据操作( 4学时)

\*[1] 计算机的结构
\*[2]机器语言
\*[3] 指令和程序

基本要求：

认识计算机的体系构造，指令的作用和程序的构造。认识CPU和内存等核心部件的角色和作用。

### 4．操作系统( 2学时)

\*[1] 操作系统历史
\*[2] 操作系统的体系结构
\*[3] 进程的概念

基本要求：

了解操作系统的发展历史及其特点，认识操作系统的大致构造及其作用。能够帮助了解日常使用的Windows操作系统。

### 5．网络    4学时

\*[1] 网络基础
\*[2]Internet
\*[3]万维网/HTML
\*[4]网络协议

基本要求：

认识网络的基础构造以及以Internet为代表的主流应用，了解网络技术中核心的协议概念。认识Web的基本格式HTML的意义。

### 6．算法(4 学时)

\*[1]算法的概念
\*[2] 算法的设计和表达
\*[3]常用的程序结构

基本要求：

了解算法的内容和算法设计，认识算法在程序中的重要地位。了解原语以及伪代码在算法设计的表达上重要性；进一步认识算法和程序设计的相互关系。

### 7. 程序设计语言和软件工程(4学时)

\*[1] 程序语言简史
\*[2] 程序设计概念
\*[3]语言的实现
\*[4]软件工程的内容

基本要求：

了解程序设计的思路和常用的程序设计语言，认识软件工程的内容及其作用。

### 8. 数据抽象(2学时)

\*[1] 数据结构基础
\*[2] 数据结构的实现

基本要求：

了解数据结构的基本概念及其技术，认识数据结构对于算法实现和程序设计的地位。

### 9. 数据库系统( 2学时)

\*[1]数据库基本概念
\*[2]关系模型
\*[3]数据库的应用
\*[4] 数据库的社会影响

基本要求：

了解数据模型、数据库管理系统以及数据库应用分类等。

### 10. 高级话题(2学时)

\*[1]机器的智能问题
\*[2]推理
\*[3]人工智能一些主流技术

基本要求：

通过人工智能领域的简单介绍，让学生了解计算机的前端技术发展，引发学生对计算机技术发展的探索。

## 五、教材及学生参考书

教  材：
\*计算机科学概论》(第9版) J.Glenn Brookshear著．人民邮电出版社，2007年出版

参考书：
\*[1]《计算科学导论》 赵致琢编著．科学出版社，2002年出版
\*[2]《计算机科学与技术方法论》 董荣胜 古天龙 著  人民邮电出版社，2002年出版
\*[3]《New Perspective on Computer Concepts》（第5版）  June Jamirich Parsons Dan Oja著．机械工业出版社，2004年出版

## 六、课外学习要求

为了培养学生主动学习能力，通过加强参考书和其他辅助材料的阅读和对信息技术的研讨，逐渐培养专业的兴趣。

## 七、考核方式及成绩评定方法

期末采用闭卷考试形式。

总评成绩：作业、平时考勤及学习态度（含实验）占 35% ；期中考试15%，期末闭卷考试占 50%。

## 八、其它说明（黑体小四）
