---
title: "计算机发展简史"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## Brief History of Computer

## von Neumann

1945 John von Neumann wrote "First Draft of a Report on the EDVAC" in which he outlined the architecture of a stored-program computer. Electronic storage of programming information and data eliminated the need for the more clumsy methods of programming, such as punched paper tape -- a concept that has characterized mainstream computer development since 1945. Hungarian-born von Neumann demonstrated prodigious expertise in hydrodynamics, ballistics, meteorology, game theory, statistics, and the use of mechanical devices for computation. After the war, he concentrated on the development of Princeton's Institute for Advanced Studies computer and its copies around the world.

## ENIAC

1946 In February, the public got its first glimpse of the ENIAC, a machine built by John Mauchly and J. Presper Eckert that improved by 1,000 times on the speed of its contemporaries.

## AVIDAC

1946 An inspiring summer school on computing at the University of Pennsylvania's Moore School of Electrical Engineering stimulated construction of stored-program computers at universities and research institutions. This free, public set of lectures inspired the EDSAC, BINAC, and, later, IAS machine clones like the AVIDAC. Here, Warren Kelleher completes the wiring of the arithmetic unit components of the AVIDAC at Argonne National Laboratory. Robert Dennis installs the inter-unit wiring as James Woody Jr. adjusts the deflection control circuits of the memory unit.

## IBM's SSEC

1948 IBM's Selective Sequence Electronic Calculator computed scientific data in public display near the company's Manhattan headquarters. Before its decommissioning in 1952, the SSEC produced the moon-position tables used for plotting the course of the 1969 Apollo flight to the moon.

## Wilkes with the EDSAC

1949 Maurice Wilkes assembled the EDSAC, the first practical stored-program computer, at Cambridge University. His ideas grew out of the Moore School lectures he had attended three years earlier.
For programming the EDSAC, Wilkes established a library of short programs called subroutines stored on punched paper tapes.

## Manchester Mark I

1949 The Manchester Mark I computer functioned as a complete system using the Williams tube for memory. This University machine became the prototype for Ferranti Corp.'s first computer.

## ERA 1101(drum memory)

1950 Engineering Research Associates of Minneapolis built the ERA 1101, the first commercially produced computer; the company's first customer was the U.S. Navy. It held 1 million bits on its magnetic drum, the earliest magnetic storage devices. Drums registered information as magnetic pulses in tracks around a metal cylinder. Read/write heads both recorded and recovered the data. Drums eventually stored as many as 4,000 words and retrieved any one of them in as little as five-thousandths of a second.

## SEAC

1950 The National Bureau of Standards constructed the SEAC (Standards Eastern Automatic Computer) in Washington as a laboratory for testing components and systems for setting computer standards. The SEAC was the first computer to use all-diode logic, a technology more reliable than vacuum tubes, and the first stored-program computer completed in the United States. Magnetic tape in the external storage units (shown on the right of this photo) stored programming information, coded subroutines, numerical data, and output.

## SWAC

1950 The National Bureau of Standards completed its SWAC (Standards Western Automatic Computer) at the Institute for Numerical Analysis in Los Angeles. Rather than testing components like its companion, the SEAC, the SWAC had an objective of computing using already-developed technology.

## Pilot ACE

1950 Alan Turing's philosophy directed design of Britain's Pilot ACE at the National Physical Laboratory. "We are trying to build a machine to do all kinds of different things simply by programming rather than by the addition of extra apparatus," Turing said at a symposium on large-scale digital calculating machinery in 1947 in Cambridge, Mass.

## MIT Whirlwind

1951 MIT's Whirlwind debuted on Edward R. Murrow's "See It Now" television series. Project director Jay Forrester described the computer as a "reliable operating system," running 35 hours a week at 90-percent utility using an electrostatic tube memory.

## LEO

1951 England's first commercial computer, the Lyons Electronic Office, solved clerical problems. The president of Lyons Tea Co. had the computer, modeled after the EDSAC, built to solve the problem of daily scheduling production and delivery of cakes to the Lyons tea shops. After the success of the first LEO, Lyons went into business manufacturing computers to meet the growing need for data processing systems.

## UNIVAC I

1951 The UNIVAC I delivered to the U.S. Census Bureau was the first commercial computer to attract widespread public attention. Although manufactured by Remington Rand, the machine often was mistakenly referred to as the "IBM UNIVAC." Remington Rand eventually sold 46 machines at more than $1 million each.

## von Neumann's IAS

1952 John von Neumann's IAS computer became operational at the Institute for Advanced Studies in Princeton, N.J. Contract obliged the builders to share their designs with other research institutes. This resulted in a number of clones: the MANIAC at Los Alamos Scientific Laboratory, the ILLIAC at the University of Illinois, the Johnniac at Rand Corp., the SILLIAC in Australia, and others.

## IBM 701

1953 IBM shipped its first electronic computer, the 701. During three years of production, IBM sold 19 machines to research laboratories, aircraft companies, and the federal government.

## IBM 650

1954 The IBM 650 magnetic drum calculator established itself as the first mass-produced computer, with the company selling 450 in one year. Spinning at 12,500 rpm, the 650's magnetic data-storage drum allowed much faster access to stored material than drum memory machines.

## MIT TX0

1956 MIT researchers built the TX-0, the first general-purpose, programmable computer built with transistors. For easy replacement, designers placed each transistor circuit inside a "bottle," similar to a vacuum tube. Constructed at MIT's Lincoln Laboratory, the TX-0 moved to the MIT Research Laboratory of Electronics, where it hosted some early imaginative tests of programming, including a Western movie shown on TV, 3-D tic-tac-toe, and a maze in which mouse found martinis and became increasingly inebriated.

## SAGE operator station

1958 SAGE -- Semi-Automatic Ground Environment -- linked hundreds of radar stations in the United States and Canada in the first large-scale computer communications network. An operator directed actions by touching a light gun to the screen.
The air defense system operated on the AN/FSQ-7 computer (known as Whirlwind II during its development at MIT) as its central computer. Each computer used a full megawatt of power to drive its 55,000 vacuum tubes, 175,000 diodes and 13,000 transistors.

## NEAC 1101

1958 Japan's NEC built the country's first electronic computer, the NEAC 1101.

## IBM STRETCH (in background)

1959 IBM's 7000 series mainframes were the company's first transistorized computers. At the top of the line of computers -- all of which emerged significantly faster and more dependable than vacuum tube machines -- sat the 7030, also known as the "Stretch." Seven of the computers, which featured a 64-bit word and other innovations, were sold to national laboratories and other scientific users. L. R. Johnson first used the term "architecture" in describing the Stretch.

## DEC PDP-1

1960 The precursor to the minicomputer, DEC's PDP-1 sold for $120,000. One of 50 built, the average PDP-1 included with a cathode ray tube graphic display, needed no air conditioning and required only one operator. It's large scope intrigued early hackers at MIT, who wrote the first computerized video game, SpaceWar!, for it. The SpaceWar! creators then used the game as a standard demonstration on all 50 computers.

## IBM 1401

1961 According to Datamation magazine, IBM had an 81.2-percent share of the computer market in 1961, the year in which it introduced the 1400 Series. The 1401 mainframe, the first in the series, replaced the vacuum tube with smaller, more reliable transistors and used a magnetic core memory.
Demand called for more than 12,000 of the 1401 computers, and the machine's success made a strong case for using general-purpose computers rather than specialized systems.

## Clark with LINC-8

1962 The LINC (Laboratory Instrumentation Computer) offered the first real time laboratory data processing. Designed by Wesley Clark at Lincoln Laboratories, Digital Equipment Corp. later commercialized it as the LINC-8.
Research faculty came to a workshop at MIT to build their own machines, most of which they used in biomedical studies. DEC supplied components.

## IBM System/360

1964 IBM announced the System/360, a family of six mutually compatible computers and 40 peripherals that could work together. The initial investment of $5 billion was quickly returned as orders for the system climbed to 1,000 per month within two years. At the time IBM released the System/360, the company was making a transition from discrete transistors to integrated circuits, and its major source of revenue moved from punched-card equipment to electronic computer systems.

## CDC 6600

1964 CDC's 6600 supercomputer, designed by Seymour Cray, performed up to 3 million instructions per second -- a processing speed three times faster than that of its closest competitor, the IBM Stretch. The 6600 retained the distinction of being the fastest computer in the world until surpassed by its successor, the CDC 7600, in 1968. Part of the speed came from the computer's design, which had 10 small computers, known as peripheral processors, funneling data to a large central processing unit.

## DEC PDP-8

1965 Digital Equipment Corp. introduced the PDP-8, the first commercially successful minicomputer. The PDP-8 sold for $18,000, one-fifth the price of a small IBM 360 mainframe. The speed, small size, and reasonable cost enabled the PDP-8 to go into thousands of manufacturing plants, small businesses, and scientific laboratories.

## ILLIAC IV

1966 The Department of Defense Advanced Research Projects Agency contracted with the University of Illinois to build a large parallel processing computer, the ILLIAC IV, which did not operate until 1972 at NASA's Ames Research Center. The first large-scale array computer, the ILLIAC IV achieved a computation speed of 200 million instructions per second, about 300 million operations per second, and 1 billion bits per second of I/O transfer via a unique combination of parallel architecture and the overlapping or "pipe-lining" structure of its 64 processing elements.
This photograph shows one of the ILLIAC's 13 Burroughs disks, the debugging computer, the central unit, and the processing unit cabinet with a processing element.

## HP-2115

1966 Hewlett-Packard entered the general purpose computer business with its HP-2115 for computation, offering a computational power formerly found only in much larger computers. It supported a wide variety of languages, among them BASIC, ALGOL, and FORTRAN.

## Ed deCastro and Nova

1968 Data General Corp., started by a group of engineers that had left Digital Equipment Corp., introduced the Nova, with 32 kilobytes of memory, for $8,000.
In the photograph, Ed deCastro, president and founder of Data General, sits with a Nova minicomputer. The simple architecture of the Nova instruction set inspired Steve Wozniak's Apple I board eight years later.

## Apollo Guidance Computer

1968 The Apollo Guidance Computer made its debut orbiting the Earth on Apollo 7. A year later, it steered Apollo 11 to the lunar surface. Astronauts communicated with the computer by punching two-digit codes and the appropriate syntactic category into the display and keyboard unit.

## Kenbak-1

1971 The Kenbak-1, the first personal computer, advertised for $750 in Scientific American. Designed by John V. Blankenbaker using standard medium-scale and small-scale integrated circuits, the Kenbak-1 relied on switches for input and lights for output from its 256-byte memory. In 1973, after selling only 40 machines, Kenbak Corp. closed its doors.

## HP-35

1972 Hewlett-Packard announced the HP-35 as "a fast, extremely accurate electronic slide rule" with a solid-state memory similar to that of a computer. The HP-35 distinguished itself from its competitors by its ability to perform a broad variety of logarithmic and trigonometric functions, to store more intermediate solutions for later use, and to accept and display entries in a form similar to standard scientific notation.

## TV Typewriter

1973 The TV Typewriter, designed by Don Lancaster, provided the first display of alphanumeric information on an ordinary television set. It used $120 worth of electronics components, as outlined in the September 1973 issue of Radio Electronics. The original design included two memory boards and could generate and store 512 characters as 16 lines of 32 characters. A 90-minute cassette tape provided supplementary storage for about 100 pages of text.

## Micral

1973 The Micral was the earliest commercial, non-kit personal computer based on a micro-processor, the Intel 8008. Thi Truong developed the computer and Philippe Kahn the software. Truong, founder and president of the French company R2E, created the Micral as a replacement for minicomputers in situations that didn't require high performance. Selling for $1,750, the Micral never penetrated the U.S. market. In 1979, Truong sold Micral to Bull.

## Xerox Alto

1974 Researchers at the Xerox Palo Alto Research Center designed the Alto -- the first work station with a built-in mouse for input. The Alto stored several files simultaneously in windows, offered menus and icons, and could link to a local area network. Although Xerox never sold the Alto commercially, it gave a number of them to universities. Engineers later incorporated its features into work stations and personal computers.

## Scelbi 8H

1974 Scelbi advertised its 8H computer, the first commercially advertised U.S. computer based on a microprocessor, Intel's 8008. Scelbi aimed the 8H, available both in kit form and fully assembled, at scientific, electronic, and biological applications. It had 4 kilobytes of internal memory and a cassette tape, with both teletype and oscilloscope interfaces. In 1975, Scelbi introduced the 8B version with 16 kilobytes of memory for the business market. The company sold about 200 machines, losing $500 per unit.

## MITS Altair

1975 The January edition of Popular Electronics featured the Altair 8800 computer kit, based on Intel's 8080 microprocessor, on its cover. Within weeks of the computer's debut, customers inundated the manufacturing company, MITS, with orders. Bill Gates and Paul Allen licensed BASIC as the software language for the Altair. Ed Roberts invented the 8800 -- which sold for $297, or $395 with a case -- and coined the term "personal computer." The machine came with 256 bytes of memory (expandable to 64K) and an open 100-line bus structure that evolved into the S-100 standard. In 1977, MITS sold out to Pertec, which continued producing Altairs through 1978.

## Felsenstein's VDM

1975 The visual display module (VDM) prototype, designed in 1975 by Lee Felsenstein, marked the first implementation of a memory-mapped alphanumeric video display for personal computers. Introduced at the Altair Convention in Albuquerque in March 1976, the visual display module allowed use of personal computers for interactive games.

## Tandem-16

1975 Tandem Computers tailored its Tandem-16, the first fault-tolerant computer, for online transaction processing. The banking industry rushed to adopt the machine, built to run during repair or expansion.

## Apple I

1976 Steve Wozniak designed the Apple I, a single-board computer. With specifications in hand and an order for 100 machines at $500 each from the Byte Shop, he and Steve Jobs got their start in business. In this photograph of the Apple I board, the upper two rows are a video terminal and the lower two rows are the computer. The 6502 microprocessor in the white package sits on the lower right. About 200 of the machines sold before the company announced the Apple II as a complete computer.

## Cray I

1976 The Cray I made its name as the first commercially successful vector processor. The fastest machine of its day, its speed came partly from its shape, a C, which reduced the length of wires and thus the time signals needed to travel across them.

## Commodore PET

1977 The Commodore PET (Personal Electronic Transactor) -- the first of several personal computers released in 1977 -- came fully assembled and was straightforward to operate, with either 4 or 8 kilobytes of memory, two built-in cassette drives, and a membrane "chiclet" keyboard.

## Apple II

1977 The Apple II became an instant success when released in 1977 with it's printed circuit motherboard, switching power supply, keyboard, case assembly, manual, game paddles, A/C powercord, and cassette tape with the computer game "Breakout." When hooked up to a color television set, the Apple II produced brilliant color graphics.

## TRS-80

1977 In the first month after its release, Tandy Radio Shack's first desktop computer -- the TRS-80 -- sold 10,000 units, well more than the company's projected sales of 3,000 units for one year. Priced at $599.95, the machine included a Z80 based microprocessor, a video display, 4 kilobytes of memory, BASIC, cassette storage, and easy-to-understand manuals that assumed no prior knowledge on the part of the consumer.

## VAX 11/780

1978 The VAX 11/780 from Digital Equipment Corp. featured the ability to address up to 4.3 gigabytes of virtual memory, providing hundreds of times the capacity of most minicomputers.

## IBM PC

1981 IBM introduced its PC, igniting a fast growth of the personal computer market. The first PC ran on a 4.77 MHz Intel 8088 microprocessor and used Microsoft's MS-DOS operating system.

## Osborne I

1981 Adam Osborne completed the first portable computer, the Osborne I, which weighed 24 pounds and cost $1,795. The price made the machine especially attractive, as it included software worth about $1,500. The machine featured a 5-inch display, 64 kilobytes of memory, a modem, and two 5 1/4-inch floppy disk drives.
In April 1981, Byte Magazine Editor in Chief Chris Morgan mentioned the Osborne I in an article on "Future Trends in Personal Computing." He wrote: "I recently had an opportunity to see the Osborne I in action. I was impressed with it's compactness: it will fit under an airplane seat. (Adam Osborne is currently seeking approval from the FAA to operate the unit on board a plane.) One quibble: the screen may be too small for some people's taste."

## Apollo DN100

1981 Apollo Computer unveiled the first work station, its DN100, offering more power than some minicomputers at a fraction of the price. Apollo Computer and Sun Microsystems, another early entrant in the work station market, optimized their machines to run the computer-intensive graphics programs common in engineering.

## Cray XMP

1982 The Cray XMP, first produced in this year, almost doubled the operating speed of competing machines with a parallel processing system that ran at 420 million floating-point operations per second, or megaflops. Arranging two Crays to work together on different parts of the same problem achieved the faster speed. Defense and scientific research institutes also heavily used Crays.

## Lisa

1983 Apple introduced its Lisa. The first personal computer with a graphical user interface, its development was central in the move to such systems for personal computers. The Lisa's sloth and high price ($10,000) led to its ultimate failure.
The Lisa ran on a Motorola 68000 microprocessor and came equipped with 1 megabyte of RAM, a 12-inch black-and-white monitor, dual 5 1/4-inch floppy disk drives and a 5 megabyte Profile hard drive. The Xerox Star -- which included a system called Smalltalk that involved a mouse, windows, and pop-up menus -- inspired the Lisa's designers.

## Compaq PC clone

1983 Compaq Computer Corp. introduced first PC clone that used the same software as the IBM PC. With the success of the clone, Compaq recorded first-year sales of $111 million, the most ever by an American business in a single year.
With the introduction of its PC clone, Compaq launched a market for IBM-compatible computers that by 1996 had achieved a 83-percent share of the personal computer market. Designers reverse-engineered the Compaq clone, giving it nearly 100-percent compatibility with the IBM.

## Apple Macintosh

1984 Apple Computer launched the Macintosh, the first successful mouse-driven computer with a graphic user interface, with a single $1.5 million commercial during the 1984 Super Bowl. Based on the Motorola 68000 microprocessor, the Macintosh included many of the Lisa's features at a much more affordable price: $2,500.
Apple's commercial played on the theme of George Orwell's "1984" and featured the destruction of Big Brother with the power of personal computing found in a Macintosh. Applications that came as part of the package included MacPaint, which made use of the mouse, and MacWrite, which demonstrated WYSIWYG (What You See Is What You Get) word processing.

## IBM PC Jr.

1984 IBM released its PC Jr. and PC-AT. The PC Jr. failed, but the PC-AT, several times faster than original PC and based on the Intel 80286 chip, claimed success with its notable increases in performance and storage capacity, all for about $4,000. It also included more RAM and accommodated high-density 1.2-megabyte 5 1/4-inch floppy disks.

## Connection Machine

1986 Daniel Hillis of Thinking Machines Corp. moved artificial intelligence a step forward when he developed the controversial concept of massive parallelism in the Connection Machine. The machine used 16,000 processors and could complete several billion operations per second. Each processor had its own small memory linked with others through a flexible network that users could alter by reprogramming rather than rewiring.<br>
The machine's system of connections and switches let processors broadcast information and requests for help to other processors in a simulation of brainlike associative recall. Using this system, the machine could work faster than any other at the time on a problem that could be parceled out among the many processors.

## Risc workstation

1986 IBM and MIPS released the first RISC-based workstations, the PC/RT and R2000-based systems. Reduced instruction set computers grew out of the observation that the simplest 20 percent of a computer's instruction set does 80 percent of the work, including most base operations such as add, load from memory, and store in memory.
The IBM PC-RT had 1 megabyte of RAM, a 1.2-megabyte floppy disk drive, and a 40-megabyte hard drive. It performed 2 million instructions per second, but other RISC-based computers worked significantly faster.

## IBM PS/2

1987 IBM introduced its PS/2 machines, which made the 3 1/2-inch floppy disk drive and video graphics array standard for IBM computers. The first IBMs to include Intel's 80386 chip, the company had shipped more than 1 million units by the end of the year. IBM released a new operating system, OS/2, at the same time, allowing the use of a mouse with IBMs for the first time.

## NeXT

1988 Apple cofounder Steve Jobs, who left Apple to form his own company, unveiled the NeXT. The computer he created failed but was recognized as an important innovation. At a base price of $6,500, the NeXT ran too slowly to be popular.

## 参见

* [PC简史](<PC简史.qmd>)
* [计算机发展历史](<../计算机发展历史.html>)
