---
title: "计算机发展历史"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 计算机的发展历史

现代电子计算机技术的飞速发展，离不开人类科技知识的积累，离不开许许多多热衷于此并呕心沥血的科学家的探索，正是这一代代的积累才构筑了今天的“信息大厦”。从下面这个按时间顺序展现的计算机发展简史中，我们可以感受到科技发展的艰辛及科学技术的巨大推动力。

## 一、机械计算机的诞生

在西欧，由中世纪进入文艺复兴时期的社会大变革，极大地促进了自然科学技术的发展，人们长期被神权压抑的创造力得到了空前的释放。而在这些思想创意的火花中，制造一台能帮助人进行计算的机器则是最耀眼、最夺目的一朵。从那时起，一个又一个科学家为了实现这一伟大的梦想而不懈努力着。但限于当时的科技水平，多数试验性的创造都以失败而告终，这也就昭示了拓荒者的共同命运: 往往在倒下去之前见不到自己努力的成果。而后人在享用这些甜美成果的时候，往往能够从中品味出汗水与泪水交织的滋味……

1614 年:苏格兰人John Napier(1550 ～1617 年)发表了一篇论文 ，其中提到他发明了一种可以进行四则运算和方根运算的精巧装置。

1623 年:Wilhelm Schickard(1592 ～1635 年)制作了一个能进行6 位数以内加减法运算，并能通过铃声输出答案的“计算钟”。该装置通过转动齿轮来进行操作。

1625 年:William Oughtred(1575 ～1660 年)发明计算尺。

1668 年:英国人Samuel Morl(1625 ～1695 年)制作了一个非十进制的加法装置，适宜计算钱币。

1671 年:德国数学家Gottfried Leibniz 设计了一架可以进行乘法运算，最终答案长度可达16位的计算工具。

1822 年:英国人Charles Babbage(1792 ～1871 年)设计了差分机和分析机 ，其设计理论非常超前，类似于百年后的电子计算机，特别是利用卡片输入程序和数据的设计被后人所采用。

1834 年:Babbage 设想制造一台通用分析机，在只读存储器(穿孔卡片)中存储程序和数据。Babbage在以后的时间里继续他的研究工作，并于1840 年将操作位数提高到了40 位，并基本实现了控制中心(CPU)和存储程序的设想，而且程序可以根据条件进行跳转，能在几秒内做出一般的加法，几分钟内做出乘、除法。

1848 年:英国数学家George Boole 创立二进制代数学，提前近一个世纪为现代二进制计算机的发展铺平了道路。

1890 年:美国人口普查部门希望能得到一台机器帮助提高普查效率。Herman Hollerith (后来他的公司发展成了IBM 公司)借鉴Babbage 的发明，用穿孔卡片存储数据，并设计了机器。结果仅用6 周就得出了准确的人口统计数据(如果用人工方法，大概要花10 年时间)。

1896 年:Herman Hollerith 创办了IBM 公司的前身。

## 二、电子计算机问世

在以机械方式运行的计算器诞生百年之后，随着电子技术的突飞猛进，计算机开始了真正意义上的由机械向电子时代的过渡，电子器件逐渐演变成为计算机的主体，而机械部件则渐渐处于从属位置。二者地位发生转化的时候，计算机也正式开始了由量到质的转变，由此导致电子计算机正式问世。下面就是这一过渡时期的主要事件:

1906 年:美国人Lee De Forest 发明电子管，为电子计算机的发展奠定了基础。

1924 年2 月:IBM 公司成立，从此一个具有划时代意义的公司诞生。

1935 年:IBM 推出IBM 601 机。这是一台能在一秒钟内算出乘法的穿孔卡片计算机 。这台机器无论在自然科学还是在商业应用上都具有重要的地位，大约制造了1500 台。

1937 年:英国剑桥大学的Alan M.Turing(1912 ～1954 年)出版了他的论文 ，并提出了被后人称之为“图灵机”的数学模型。

1937 年:Bell 试验室的George Stibitz 展示了用继电器表示二进制的装置。尽管仅仅是个展示品，但却是第一台二进制电子计算机。

1940 年1 月:Bell 实验室的Samuel Williams 和Stibitz 制造成功了一个能进行复杂运算的计算机。该机器大量使用了继电器，并借鉴了一些电话技术，采用了先进的编码技术。

1941 年夏季:Atanasoff 和学生Berry 完成了能解线性代数方程的计算机，取名叫“ABC ”(Atanasoff-Berry Computer)，用电容作存储器 ，用穿孔卡片作辅助存储器，那些孔实际上是“烧”上去的，时钟频率是60Hz，完成一次加法运算用时一秒。

1943 年1 月:Mark I 自动顺序控制计算机在美国研制成功。整个机器有51 英尺长 、5 吨重、75万个零部件。该机使用了3304 个继电器 ，60 个开关作为机械只读存储器 。程序存储在纸带上 ，数据可以来自纸带或卡片阅读器。Mark I 被用来为美国海军计算弹道火力表。

1943 年9 月:Williams 和Stibitz 完成了“Relay Interpolator ”，后来命名为“ModelⅡ Re-lay Calculator ”的计算机。这是一台可编程计算机，同样使用纸带输入程序和数据。它运行更可靠，每个数用7 个继电器表示，可进行浮点运算。

1946 年:ENIAC(Electronic Numerical Integrator And Computer)诞生，这是第一台真正意义上的数字电子计算机。开始研制于1943 年，完成于1946 年，负责人是John W.Mauchly 和J.Presper Eckert，重30 吨，用了18000 个电子管，功率25 千瓦，主要用于计算弹道和氢弹的研制。

## 三、晶体管计算机的发展

真空管时代的计算机尽管已经步入了现代计算机的范畴，但因其体积大、能耗高、故障多、价格贵，从而制约了它的普及和应用。直到晶体管被发明出来，电子计算机才找到了腾飞的起点。

1947 年:Bell 实验室的William B.Shockley 、 John Bardeen 和Walter H.Brattain 发明了晶体管，开辟了电子时代新纪元。

1949 年:剑桥大学的Wilkes 和他的小组制成了一台可以存储程序的计算机，输入输出设备仍是纸带。

1949 年:EDVAC(Electronic Discrete Variable Automatic Computer——电子离散变量自动计算机)——第一台使用磁带的计算机。这是一个突破，可以多次在磁带上存储程序。这台机器是John von Neumann 提议建造的。

1950 年:日本东京帝国大学的Yoshiro Nakamats 发明了软磁盘 ，其销售权由IBM公司获得 。由此开创了存储时代的新纪元。
