---
title: "集成搜索引擎"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

搜索引擎是开启网络知识殿堂的钥匙，获取知识信息的工具。随着网络技术的飞速发展，搜索技术的日臻完善，中外搜索引擎已广为人们熟知和使用。任何搜索引擎的设计，均有其特定的数据库索引范围、独特的功能和使用方法，以及预期的用户群指向。一种搜索引擎不可能满足所有人或一个人所有的检索需求。在某些情况下，如文献普查、专题查询、新闻调查与溯源、软件及MP3下载地址搜索等等，人们往往需要使用多种搜索引擎，对搜索结果进行比较、筛选和相互印证。为解决逐一登陆各搜索引擎，并在各搜索引擎中分别多次输入同一检索请求（检索字串）等烦琐操作，集成搜索引擎和元搜索引擎应运而生。

## 一、集成搜索引擎

集成搜索引擎（ All－in－One Search Page），亦称为“多引擎同步检索系统 ”（如我来搜http://www.wolaisou.com） 是在一个WWW页面上链接若干种独立的搜索引擎，检索时需点选或指定搜索引擎，一次检索输入，多引擎同时搜索，用起来相当方便.
集成搜索引擎无自建数据库，不需研发支持技术，当然也不能控制和优化检索结果。但集成搜索引擎制作与维护技术简单，可随时对所链接的搜索引擎进行增删调整和及时更新，尤其大规模专业（如FLASH、MP3等）搜索引擎集成链接，深受特定用户群欢迎。

## 二、元搜索引擎

元搜索引擎（Metasearch Engine），是一种调用其它独立搜索引擎的引擎,亦称“搜索引擎之母（The mother of searce engines)”。在这里，“元”（Meta）为“总的”、“超越”之意，元搜索引擎就是对多个独立搜索引擎的整合、调用、控制和优化利用。相对元搜索引擎，可被利用的独立搜索引擎称为“源搜索引擎”（source Engine），或“搜索资源”（searcing resources），整合、调用、控制和优化利用源搜索引擎的技术，称为“元搜索技术”（Meta-searching technique），元搜索技术是元搜索引擎的核心。

元搜索引擎分为并行处理式和串行处理式两大类。并行处理式元搜索引擎将用户的查询请求同时转送给它调用链接的多个独立型搜索引擎进行查询处理，串行处理式元搜索引擎将用户的查询请求依次转送给它调用链接的每一个独立型搜索引擎进行查询处理。

## 《搜索引擎观察》2006年最佳集成搜索引擎

* 1、我来搜（http://www.wolaisou.com/）

调用多种搜索引擎，分类合理,界面友好，简单易用。

* 2.我要聚合 (http://www.51juhe.com)

调用多种搜索引擎, 分类全理.但界面有待进一改善.。　　

## 常用元搜索引擎

* 1、Dogpile http://www.dogpile.com/）
* 2、Webcrawler http://www.webcrawler.com/）
* 3、Search.com http://www.search.com/）
* 4、1Blink http://www.1blink.com/）
* 5、第九门 http://www.9om.com)

综上所述.集成搜索引擎与无搜索引擎,在搜索引擎领域及对我们搜索质量的提高有很大的帮助.如果喜欢搜索东西的话,还是经常用这些引擎比较好些.
