---
title: "集线器"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“计算机科学导论”](../计算机科学导论.qmd)

## 概念

集线器（HUB）属于数据通信系统中的基础设备，它和双绞线等传输介质一样，是一种不需任何软件支持或只需很少管理软件管理的硬件设备。它被广泛应用到各种场合。

集线器工作在局域网(LAN)环境，像网卡一样，应用于OSI参考模型第一层，因此又被称为物理层设备。集线器内部采用了电器互联，当维护LAN的环境是逻辑总线或环型结构时，完全可以用集线器建立一个物理上的星型或树型网络结构。在这方面，集线器所起的作用相当于多端口的中继器。其实，集线器实际上就是中继器的一种，其区别仅在于集线器能够提供更多的端口服务，所以集线器又叫多口中继器。

集线器在OSI模型中属于数据链路层。价格便宜是它最大的优势，但由于集线器属于共享型设备，导致了在繁重的网络中，效率变得十分低下，所以我们在中、大型的网络中看不到集线器的身影。如今的集线器普遍采用全双工模式，市场上常见的集线器传输速率普遍都为100Mbps。

集线器属于纯硬件网络底层设备，基本上不具有类似于交换机的"智能记忆"能力和"学习"能力。它也不具备交换机所具有的MAC地址表，所以它发送数据时都是没有针对性的，而是采用广播方式发送。也就是说当它要向某节点发送数据时，不是直接把数据发送到目的节点，而是把数据包发送到与集线器相连的所有节点。

普通集线器外部板面结构非常简单。比如D-Link最简单的10BASE~T EthernetHub集线器是个长方体，背面有交流电源插座和开关、一个AUI接口和一个BNC接口，正面的大部分位置分布有一行17个RJ-45接口。在正面的右边还有与每个RJ--45接口对应的LED接口指示灯和LED状态指示灯。高档集线器从外表上看，与现代路由器或交换式路由器没有多大区别。尤其是现代双速自适应以太网集线器，由于普遍内置有可以实现内部10Mb／s和100Mb／s网段间相互通信的交换模块，使得这类集线器完全可以在以该集线器为节点的网段中，实现各节点之间的通信交换，有时大家也将此类交换式集线器简单地称之为交换机，这些都使得初次使用集线器的用户很难正确地辨别它们。但根据背板接口类型来判别集线器，是一种比较简单的方法。

## 集线器分类

### 按结构和功能分类

按结构和功能分类，集线器可分为未管理的集线器、堆叠式集线器和底盘集线器三类

1. 未管理的集线器:最简单的集线器通过以太网总线提供中央网络连接，以星形的形式连接起来。这称之为未管理的集线器，只用于很小型的至多 12个节点的网络中(在少数情况下，可以更多一些)。未管理的集线器没有管理软件或协议来提供网络管理功能，这种集线器可以是无源的，也可以是有源的，有源集线器使用得更多。
2. 堆叠式集线器:是稍微复杂一些的集线器。堆叠式集线器最显著的特征是8个转发器可以直接彼此相连。这样只需简单地添加集线器并将其连接到已经安装的集线器上就可以扩展网络，这种方法不仅成本低，而且简单易行。
3. 底盘集线器:是一种模块化的设备，在其底板电路板上可以插入多种类型的模块。有些集线器带有冗余的底板和电源。同时，有些模块允许用户不必关闭整个集线器便可替换那些失效的模块。集线器的底板给插入模块准备了多条总线，这些插入模块可以适应不同的段，如以太网、快速以太网、光纤分布式数据接口(Fiber Distributed Data Interface，FDDl)和异步传输模式(Asynchronous Transfer Mode，ATM)中。有些集线器还包含有网桥、路由器或交换模块。有源的底盘集线器还可能会有重定时的模块，用来与放大的数据信号关联。

### 按局域网的类型分类

从局域网角度来区分，集线器可分为五种不同类型:

1. 单中继网段集线器:最简单的集线器，是一类用于最简单的中继式LAN网段的集线器，与堆叠式以太网集线器或令牌环网多站访问部件(MAU)等类似。
2. 多网段集线器:从单中继网段集线器直接派生而来，采用集线器背板，这种集线器带有多个中继网段。其主要优点是可以将用户分布于多个中继网段上，以减少每个网段的信息流量负载，网段之间的信息流量一般要求独立的网桥或路由器。
3. 端口交换式集线器:该集成器是在多网段集线器基础上，将用户端口和多个背板网段之间的连接过程自动化，并通过增加端口交换矩阵 (PSM)来实现的集线器。PSM可提供一种自动工具，用于将任何外来用户端口连接到集线器背板上的任何中继网段上。端口交换式集线器的主要优点是，可实现移动、增加和修改的自动化特点。
4. 网络互联集线器:端口交换式集线器注重端口交换，而网络互联集线器在背板的多个网段之间可提供一些类型的集成连接，该功能通过一台综合网桥、路由器或LAN交换机来完成。目前，这类集线器通常都采用机箱形式。
5. 交换式集线器:目前，集线器和交换机之间的界限已变得模糊。交换式集线器有一个核心交换式背板，采用一个纯粹的交换系统代替传统的共享介质中继网段。此类产品已经上市，并且混合的(中继／交换)集线器很可能在以后几年控制这一市场。应该指出，这类集线器和交换机之间的特性几乎没有区别。

## 集线器选择

随着技术的发展，在局域网尤其是—些大中型局域网中，集线器已逐渐退出应用，而被交换机代替。目前，集线器主要应用于一些中小型网络或大中型网络的边缘部分。下面以中小型局域网的应用为特点，介绍其选择方法。

### 以速度为标准

集线器速度的选择，主要决定于以下3个因素。

1. 上联设备带宽:如果上联设备允许跑100Mbit／s，自然可购买lOOMbit／s集线器；否则lOMbit／s集线器应是理想选择，由于是对于网络连接设备数较少，而且通信流量不是很大的网络来说，lOMbit／s集线器就可以满足应用需要。
2. 提供的连接端口数:由于连接在集线器上的所有站点均争用同一个上行总线，所以连接的端口数目越多，就越容易造成冲突。同时，发往集线器任一端口的数据将被发送至与集线器相连的所有端口上，端口数过多将降低设备有效利用率。依据实践经验，一个lOMbit／s集线器所管理的计算机数不宜超过15个，lOOMbit／s的不宜超过25个。如果超过，应使用交换机来代替集线器。
3. 应用需求:传输的内容不涉及语音、图像，传输量相对较小时，选择10Mbit／s即可。如果传输量较大，且有可能涉及多媒体应用 (注意集线器不适于用来传输时间敏感性信号，如语音信号)时，应当选择100Mbit／s或10／100Mbit／s自适应集线器。10／100Mbit／s自适应集线器的价格一般要比100Mbit／s的高。

### 以能否满足拓展为标准

当一个集线器提供的端口不够时，一般有以下两种拓展用户数目的方法:

1. 堆叠:堆叠是解决单个集线器端口不足时的一种方法，但是因为堆叠在一起的多个集线器还是工作在同一个环境下，所以堆叠的层数也不能太多。然而，市面上许多集线器以其堆叠层数比其他品牌的多而作为卖点，如果遇到这种情况，要区别对待：一方面可堆叠层数越多，一般说明集线器的稳定性越高；另一方面可堆叠层数越多，每个用户实际可享有的带宽则越小。
2. 级连:级连是在网络中增加用户数的另一种方法，但是此项功能的使用—般是有条件的，即Hub必须提供可级连的端口，此端口上常标为 “Uplink”或“MDI”的字样，用此端口与其他的Hub进行级连。如果没有提供专门的端口而必须要进行级连时，连接两个集线器的双绞线在制作时必须要进行错线。

### 以是否提供网管功能为标准

早期的Hub属于一种低端的产品，且不可管理。近年来，随着技术的发展，部分集线器在技术上引进了交换机的功能，可通过增加网管模块实现对集线器的简单管理(SNMP)，以方便使用。但需要指出的是，尽管同是对SNMP提供支持，不同厂商的模块是不能混用的，同时同一厂商的不同产品的模块也不同。目前提供SNMP功能的Hub其售价较高，如D-Link公司的DEl824非智能型24口10Base-T的售价比加装网管模块后的DEl8241要便宜 1000元左右。

### 以外形尺寸为参考

如果网络系统比较简单，没有楼宇之间的综合布线，而且网络内的用户比较少，如一个家庭、一个或几个相邻的办公室，则没有必要再考虑Hub的外形尺寸。但是有的时候情况并非如此，例如为了便于对多个Hub进行集中管理，在购买Hub之前已经购置了机柜，这时在选购Hub时必须要考虑它的外形尺寸，否则Hub无法安装在机架上。现在市面上的机柜在设计时一般都遵循19英寸的工业规范，它可安装大部分的5口、8口、16口和24口的Hub。不过，为了防止意外，在选购时一定注意它是否符合19英寸工作规范，以便在机柜中安全、集中地进行管理。

### 适当考虑品牌和价格

像网卡一样，目前市面上的Hub基本由美国品牌和中国台湾品牌占据，近来大陆几家公司也相继推出了集线器产品。

* 其中高档Hub主要还是由美国品牌占领，如3COM、Intel、Bay等，它们在设计上比较独特，一般几个甚至是每个端口配置一个处理器，当然，价格也较高。
* 我国台湾地区的D-Link和Accton占有了中低端Hub的主要份额。
* 大陆的联想、实达、TP-Link等公司分别以雄厚的实力向市场上推出了自己的产品。

这些中低档产品均采用单处理器技术，其外围电路的设计思想大同小异，实现这些思想的焊接工艺手段也基本相同，价格相差不多，大陆产品相对略便宜些，正日益占据更大的市场份额。近来，随交换机产品价格的日益下降，集线器市场日益痿缩，不过，在特定的场合，集线器以其低延迟的特点可以用更低的投入带来更高的效率。交换机不可能完全代替集线器。
