---
title: "面向对象程序设计实验教学大纲"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“面向对象程序设计课程”](../面向对象程序设计课程.qmd)

## 《面向对象程序设计(C++)》实验大纲

1. 课程名称：面向对象程序设计(C++)实验
1. 学分/总学时：1/36
1. 开课单位：计算机科学与工程学院

## 课程的性质、目的和任务

《面向对象程序设计（C++）实验》是面向对象程序设计的实践性配套课程，以Microsoft的Visual C++ 6.0做为集成开发环境。通过本课程的实验使得学生更牢固地掌握面向对象程序设计的语法、思想和编程技术。
通过本实验课程的学习，要求学生达到：

1. 掌握C++的主要语法，能读懂C++编制的程序，能编写简单的C++程序；在掌握C++语言的同时，能够对现实世界中较简单的问题及其解决方法用计算机语言进行描述。深刻理解面向对象程序设计思想和Windows应用程序机制，彻底从面向过程的C程序设计中脱胎换骨；
1. 对MFC库，常用的会使用，一般的在借助于工具书和其它文档时会使用；掌握4种应用程序体系结构：CWinApp/CWnd、基于对话框、SDI、MDI；
1. 了解一些DLL、数据库、网络等编程技术。

## 学习本课程学生应掌握的前设课程知识

本课程的先行课程有：《C语言程序设计》、《计算机原理》。

## 学时分配

实验课程授课时间为36学时

| 实验名称 | 学时数 | 备注 |
| --- | --- | --- |
| 实验一 | 2 |
| 实验二 | 4 |
| 实验三 | 4 |
| 实验四 | 4 |
| 实验五 | 6 |
| 实验六 | 6 |
| 实验七 | 4 |
| 实验八 | 6 |
| 合计 | 36 |

## 实验内容和基本要求

1. 实验一  VC的安装、启用和设置（2学时）
    1. 安装VC 6.0
    1. VC的启用
    1. 创建一个简单控制台应用程序（Console Application）
    1. 工程的保存和VC退出
    1. VC的使用环境设置

  基本要求：
    了解VC的安装过程，熟练掌握VC的启动、工程创建、工程保存、退出，熟悉VC的使用环境设置。

1. 实验二  C++新增语法（4学时）
    1. 通过控制台应用程序使用符号常量的正确使用
    1. 使用带默认形参值的函数
    1. 使用重载函数
    1. 使用cin, cout
    1. 使用new, delete

  基本要求：
    熟练掌握符号常量、带默认形参值的函数、重载函数、新的输入输出、新的内存分配等C++新增的面向过程方面的语法成分，能辩别正确的用法和错误的用法。

1. 实验三  对象和类的使用（4学时）
    1. 类的声明
    1. 类的实现
    1. 类的功能测试
    1. 构造函数

  基本要求：
    能分别在3个文件中书写某个类的声明、实现和功能测试。并在类的设计中加入构造函数，深刻掌握构造函数的机制。掌握VC工程的多文件连接。

1. 实验四  友元和静态成员（4学时）
    1. 静态数据成员的声明和初始化
    1. 静态函数
    1. 友元函数
    1. 友元类

  基本要求：
    掌握静态数据成员和静态函数成员的使用，以及静态与非静态成员之间的访问关系。掌握友元函数的声明和访问能力。

1. 实验五  子类和虚函数（6学时）
    1. 类的派生和继承
    1. 虚函数和纯虚函数
    1. 抽象类
    1. 虚函数的访问

  基本要求：
    掌握类的派生和继承。掌握抽象类的定义、纯虚函数的定义方法。深刻理解虚函数的访问机制、动态联编的效果和多态性概念。

1. 实验六  模板和运算符重载（6学时）
    1. 函数模板
    1. 类模板
    1. 作为成员函数的运算符重载
    1. 作为友元的运算符重载

  基本要求：
    掌握C++模板的使用，理解参数多态的概念。掌握运算符重载的方法、实质和约束。

1. 实验七  简单Windows应用程序设计（4学时）
    1. 创建Windows窗口
    1. 窗口对简单事件的响应
    1. 窗口的最大化、最小化
    1. 窗口的标题、背景色等设置

  基本要求：
    掌握Windows窗口和消息循环的机制，掌握窗口的基本特征和参数设置，能利用MFC的窗口类设计各种风格的窗口、控制窗口的变化。

1. 实验八  综合Windows应用程序设计（6学时）
    1. 基于对话框的应用程序设计
    1. 单文档/视图的应用程序设计
    1. 菜单、对话框和控件的使用
    1. 对话框的级联

  基本要求：
    掌握基于对话框的应用程序和单文档/视图的应用程序框架设计。掌握Windows的菜单、对话框及各种控件的使用，为将来开发实际的应用软件铺平道路。

## 教材及学生参考书

教材：

1. 《C++语言程序设计》 郑莉 董渊编著 清华大学出版社 2001

参考书和网站：

1. 《面向对象程序设计》 刘振安主编 经济科学出版社
1. 《Visual C++ 6.0实例教程》 门槛创作室 电子工业出版社
1. 《Visual C++简明教程》 邓力编著 海洋出版社
1. 《Visual C++ 6.0编程实例·技巧》 李国徽等编著 华中理工大学出版社
1. 《深入浅出MFC》 侯俊杰著 电子版
1. http://www.ccw.com.cn ── E海航标
1. http://www.vcfan.com ── 程序家园
1. http://msdn.microsoft.com ── MSDN在线帮助

## 课外学习要求

查MSDN网站，看MFC参考书。

## 考核方式及成绩评定方法

1. 考核办法：平时成绩与期终考核成绩相结合，考核可采取笔试、答辩、操作等多种形式。
1. 成绩评定：其成绩由考核和平时成绩（包括预习、实验报告、实验态度）两部分组成，其中实验考核成绩占50%，实验预习占10%、实验报告占30%、实验态度占10%。期末采用考查形式。
1. 实验总评成绩将以20%的比例计入该门课程的总成绩中。

## 其它说明

学生课前应认真阅读实验教材或实验指导书，了解实验内容，明确实验目的，弄懂实验原理。教师对实验预习情况进行检查。未预习的学生不准做实验。未做实验或未交实验报告者该实验的成绩记0分；一学期累计达两次0分者，或平时成绩不及格者学期实验总评成绩为不及格；擅自缺课累计超过实验的总学时的1/3及以上者，不能参加该实验课程的考核，需要重修实验课；因病或因事未做实验者须凭有效的请假证明在学期实验结束前补做完；学期实验总评成绩不及格者必须到教务处办理重读手续。
