---
title: "面向对象程序设计实验教案"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“面向对象程序设计课程”](../面向对象程序设计课程.qmd)

## 温州大学课程教案

* 学院：计算机科学与学院
* 课程名称：面向对象程序设计实验
* 学时：36
* 教材：C++面向对象程序设计
* 授课教师：陈忠克
* 授课对象：计算机本科

## 第一课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第二课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第三课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第四课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第五课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第六课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第七课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第八课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第九课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十一课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十二课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十三课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十四课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十五课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十六课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十七课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

让学生掌握程序设计的基本方法

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在判题网站上选一题
1. 使用C++开发环境编程解决该问题，并在本机上调试通过
1. 在判题网站上提交通过。判题不通过重复前一步

## 第十八课

## 授课时间：

2课时

## 授课类型：

实验课

## 授课题目：

## 本授课单元教学目标：

实验考试

## 本授课单元教学重点和难点：

重点：掌握语法、熟悉开发环境、掌握调试
难点：程序设计的思维

## 本授课单元教学过程设计：

1. 在规定时间内，在判题网站上完成规定的题目
