---
title: "面向对象程序设计课程设计教学大纲20课时"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“面向对象程序设计课程”](../面向对象程序设计课程.qmd)

## 《面向对象程序设计(C++)课程设计》大纲20课时版

1. 课程名称：面向对象程序设计(C++)课程设计
1. 学分/总学时：1/20
1. 开课单位：计算机科学与工程学院

### 课程的性质、目的和任务

《面向对象程序设计（C++）课程设计》是面向对象程序设计的实践性配套课程。通过本课程的实践使得学生更牢固地掌握面向对象程序设计的语法、思想和编程技术。
通过本课程的学习，要求学生达到：

1. 掌握C++的主要语法，能读懂C++编制的程序，能编写简单的C++程序
1. 在掌握C++语言的同时，能够对现实世界中较简单的问题及其解决方法用计算机语言进行描述。深刻理解面向对象程序设计思想，从面向过程的C程序设计中脱胎换骨；

### 学习本课程学生应掌握的前设课程知识

本课程的先行课程有：《高级语言程序设计》、《面向对象程序设计(C++)》、《数据结构》。

### 学时分配

课程授课时间为20学时

| 课程设计项目的名称 | 学时数 | 备注 |
| --- | --- | --- |
| 课程设计一 | 8 |
| 课程设计二 | 12 |
| 合计 | 20 |

### 实验内容和基本要求

1. 实验一  类的设计和使用（8学时）
    a. 熟悉开发环境
    a. 类的基本用法

    基本要求：
    使用开发环境编写出简单的C++程序，使用类、成员函数等基本的C++语法

2. 实验二  面向对象的设计（12学时）
    a. 继承的用法
    a. 多态的用法

    基本要求：
    使用C++设计出有一定功能的程序，使用类、继承、多态等C++最核心的语法

### 教材及学生参考书

教材：

1. 《C++语言程序设计》 郑莉 董渊编著 清华大学出版社 2001

参考书和网站：

1. 《面向对象程序设计》 刘振安主编 经济科学出版社
1. 《Visual C++ 6.0实例教程》 门槛创作室 电子工业出版社
1. 《Visual C++简明教程》 邓力编著 海洋出版社
1. 《Visual C++ 6.0编程实例·技巧》 李国徽等编著 华中理工大学出版社
1. 《深入浅出MFC》 侯俊杰著 电子版
1. http://www.ccw.com.cn ── E海航标
1. http://www.vcfan.com ── 程序家园
1. http://msdn.microsoft.com ── MSDN在线帮助

### 课外学习要求

 查MSDN网站，看MFC参考书。

### 考核方式及成绩评定方法

1. 成绩评定：以两项课程设计的分数作为最终成绩。
