---
title: "游戏设计基础课程"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“Python游戏开发基础”目录](<../Python游戏开发基础.qmd>)

- [游戏设计基础课程说明](游戏设计基础课程说明.qmd)

- [游戏设计基础理论教学大纲](游戏设计基础理论教学大纲.qmd)
- [游戏设计基础实验教学大纲](游戏设计基础实验教学大纲.qmd)

- [游戏软件开发基础教学大纲](游戏软件开发基础教学大纲.qmd)
- [游戏软件系列及开发教学大纲](游戏软件系列及开发教学大纲.qmd)
- [计算机游戏程序设计基础教学大纲](计算机游戏程序设计基础教学大纲.qmd)

- [游戏设计基础理论教学进度表](游戏设计基础理论教学进度表.qmd)

- [游戏设计基础实验项目运行表](游戏设计基础实验项目运行表.qmd)

- [游戏设计基础教材](游戏设计基础教材.qmd)
- [游戏设计基础实验指导书](游戏设计基础实验指导书.qmd)

- [游戏设计基础教案](游戏设计基础教案.qmd)（每位老师交2章，多名老师开课，要求交不同章的教案）

- 游戏设计基础多媒体课件（原链接已失效；每位老师交2章，多名老师开课，要求交不同章的课件）

- [游戏设计基础实验教案](游戏设计基础实验教案.qmd) （每位老师交2份，多名老师开课，要求交不同实验的教案）

- [游戏设计基础实验报告](游戏设计基础实验报告.qmd)（1名老师上课的课程，交6份，2名老师（含）以上的，交10份，要求尽可能包含所有项目）

- [游戏设计基础作业](游戏设计基础作业.qmd)（1名老师上课的课程，交6份，2名老师（含）以上的，交10份，要求尽可能包含所有作业）

- [游戏设计基础点名记录](游戏设计基础点名记录.qmd)（每班级）

- [游戏设计基础实验成绩记录](游戏设计基础实验成绩记录.qmd)（每班级）

- [游戏设计基础试卷库](游戏设计基础试卷库.qmd)（至少4份）

- [游戏设计基础期末试卷分析](游戏设计基础期末试卷分析.qmd)（每班级）

- [游戏设计基础期末课程成绩](游戏设计基础期末课程成绩.qmd)（每班级）

- [游戏设计基础教学研究与教学获奖](游戏设计基础教学研究与教学获奖.qmd)

- [游戏设计基础课程网站](<../Python游戏开发基础.qmd>)

- [游戏设计基础教学体会](游戏设计基础教学体会.qmd)
