---
title: "游戏设计基础教案"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“Python游戏开发基础”目录](<../Python游戏开发基础.qmd>)

## 温州大学课程教案

- 学院：计算机科学与学院
- 课程名称：游戏设计基础
- 学时：22
- 教材：学习Python
- 授课教师：陈忠克
- 授课对象：计算机本科

## 第一课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python语言起步

### 本授课单元教学目标：

让学生了解Python程序设计语言，了解Python在游戏开发中应用的情况。掌握Python语言运行环境的安装使用方法，掌握Python程序的基本写法。

### 本授课单元教学重点和难点：

重点：Python语言的特点

### 本授课单元教学过程设计：

  1. Python介绍
        1. 解释型的
        1. 强大的
        1. 通用的
        1. 开放的
        1. 简单易学的
        1. 程序员的话
  1. Python与游戏开发
        1. 用Python作脚本
        1. 用Python开发主程序
  1. Python安装运行
        1. 在Windows上安装运行Python
        1. 在Linux/Unix上安装Python
        1. pygame安装
  1. 编写第一个Python程序
        1. 在交互式环境下执行
        1. 挑选一个编辑器
        1. 使用源代码执行
        1. 获取帮助

## 第二课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python语言的基本概念和基本数据类型

### 本授课单元教学目标：

让学生了解程序设计的基本概念，掌握Python的各种数据类型

### 本授课单元教学重点和难点：

重点：Python语言的高级数据类型

### 本授课单元教学过程设计：

1. 解释基本概念
  1. 字面常量Literal Constants
  1. 数值Numbers
  1. 字符串Strings
  1. 变量Variants
  1. 标识符的命名
  1. 数据类型
  1. 对象Objects
  1. 语句与行
  1. 缩进
  1. 运算符Operators
  1. 表达式Expressions
1. 基本数据类型
  1. 布尔类型
  1. 数值类型
  1. 字符串类型
  1. unicode字符串
1. 高级数据结构
  1. 列表Lists
  1. 元组Tuples
  1. 字符串替换
  1. 字典Dictionaries
  1. 序列
  1. 引用
  1. 列表推导式 List Comprehensions
  1. 类型转换
  1. 文件Files
1. 运算符
  1. 运算符表
  1. 运算符优先级

## 第三课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python语言的控制流

### 本授课单元教学目标：

让学生掌握Python的分支和循环语句，掌握Python的函数用法

### 本授课单元教学重点和难点：

重点：Python语言的函数

### 本授课单元教学过程设计：

1. 控制流
  1. 顺序结构
  1. 分支结构
  1. 循环结构
1. 函数
  1. 函数形参
  1. 局部变量
  1. global语句
  1. 默认参数值
  1. 关键字参数
  1. 变长参数列表
  1. return语句
  1. 文档字符串
  1. lambda
  1. 函数式编程
  1. 内置函数

## 第四课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python语言的类和对象

### 本授课单元教学目标：

让学生掌握Python类的定义，掌握对象的定义

### 本授课单元教学重点和难点：

重点：Python类的动态特性

### 本授课单元教学过程设计：

1. 类class
  1. 简介
  1. 创建类
  1. 类与对象的变量
  1. 对象的方法
  1. __init__方法
  1. 类与对象
  1. 继承
  1. 私有变量 Private Variables
  1. 类的特殊方法和运算符重载

## 第五课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python语言包和模块

### 本授课单元教学目标：

让学生了解Python模块和包的组织方法，掌握常用的包和模块的使用

### 本授课单元教学重点和难点：

重点：Python常用的包

### 本授课单元教学过程设计：

1. 模块
  1. 字节编译的.pyc文件
  1. from..import语句
  1. 制造你自己的模块
  1. 模块的__name__
  1. dir()函数
1. 包 Packages
  1. 创建包
  1. 导入包中的模块
1. 标准库
  1. sys模块
  1. 操作系统
  1. 文件通配符 File Wildcards
  1. 字符串正则匹配 String Pattern Matching
  1. 数学 Mathematics
  1. 互联网访问 Internet Access
  1. 日期和时间 Dates and Times
  1. 数据压缩 Data Compression
  1. 性能度量
  1. 质量控制
  1. Batteries Included

## 第六课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Pygame起步

### 本授课单元教学目标：

让学生了解Pygame的基本特点，Pygame的基本使用方法

### 本授课单元教学重点和难点：

重点：Pygame的基本结构和使用方法

### 本授课单元教学过程设计：

  1. 概述
        1. 介绍
        1. 安装
        1. 文档
        1. 参考资料
  1. 起步
        1. 初始化
        1. surface和屏幕
        1. 画图
        1. 定时事件
        1. 结合在一起
        1. sprite
        1. 背景

## 第七课

### 授课时间：

4课时

### 授课类型：

理论课

### 授课题目：

Pygame图形接口基础

### 本授课单元教学目标：

让学生了解Pygame中图形绘制的方法，Pygame中文字绘制的方法，图像的处理方法

### 本授课单元教学重点和难点：

重点：Pygame图形和文字的绘制

### 本授课单元教学过程设计：

  1. 图像处理
        1. 读取和保存
        1. 变换
  1. 对surface的控制
        1. 像素格式
        1. 块复制
        1. 透明
        1. 剪切区域
        1. 锁定
  1. 绘图
        1. 画矩形
        1. 画多边形
        1. 画圆
        1. 画椭圆
        1. 画弧线
        1. 画连续的线段
        1. 抗锯齿的线段
        1. 点操作
        1. 填充区域
  1. 写字
        1. 选择字体
        1. 创建文字Surface

## 第八课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Pygame多媒体

### 本授课单元教学目标：

让学生掌握Pygame音乐、声效、视频、CD的使用方法

### 本授课单元教学重点和难点：

重点：Python的音乐和音效

### 本授课单元教学过程设计：

1. Pygame的多媒体
  1. 音乐
  1. 音效
  1. 视频
  1. CD

## 第九课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Pygame事件与用户交互

### 本授课单元教学目标：

让学生掌握在Pygame中控制键盘、鼠标和游戏摇杆的方法

### 本授课单元教学重点和难点：

重点：键盘和鼠标的控制

### 本授课单元教学过程设计：

  1. 事件系统
  1. 键盘
  1. 鼠标
  1. 摇杆
  1. 定时

## 第十课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Python网络编程

### 本授课单元教学目标：

让学生掌握Python Socket编程的基本方法

### 本授课单元教学重点和难点：

重点：Python的socket模块使用方法

### 本授课单元教学过程设计：

1. python Socket编程
  1. Python socket 模块
        1. 基本的 Python socket 模块
        1. socket 模块
        1. SocketServer 模块
  1. Python 中的 socket 编程
        1. 前提条件
        1. 创建和销毁 socket
        1. Socket 地址
        1. 服务器 socket
        1. 客户机 socket
        1. 流 socket I/O
        1. 数据报 socket I/O
        1. socket 选项
        1. 异步 I/O
  1. 构建一个 Python 聊天服务器
        1. 一个简单的聊天服务器
        1. ChatServer 类
        1. run 方法
        1. 辅助方法
        1. 实例化一个新的 ChatServer
        1. 展示 ChatServer
  1. 高级网络类
        1. 网络模块
        1. httplib （HTTP 客户机）
        1. smptlib（SMTP 客户机）
        1. poplib（POP3 客户机）

## 第十一课

### 授课时间：

2课时

### 授课类型：

理论课

### 授课题目：

Pygame的Sprite

### 本授课单元教学目标：

让学生掌握Pygame的Sprite动画方法

### 本授课单元教学重点和难点：

重点：Pygame的Sprite类和Group类的用法

### 本授课单元教学过程设计：

1. Sprite模块介绍
  1. 历史知识
  1. 类
  1. Sprite类
  1. Group类
  1. 把它们结合起来
  1. 众多的Group类型
  1. 绘图Groups
  1. 碰撞检测
  1. 常见问题
  1. 扩展你自己的类（高级）
