---
title: "计算机游戏程序设计基础教学大纲"
lang: zh
toc: true
format:
  html:
    code-copy: true
    html-math-method: mathjax
---

[返回“Python游戏开发基础”目录](<../Python游戏开发基础.qmd>)

1. 课程名称：计算机游戏程序设计基础（Fundamentals of Game Programming）
1. 课程代码：1421217009
1. 学分/总学时：2.5/54
1. 开课单位：计算机科学与工程学院
1. 面向专业：计算机科学与技术专业及相关专业

## 课程的性质、目的和任务

随着家用计算机的普及及Internet连接到千家万户，越来越多的人利用计算机游戏娱乐、接受教育，因此计算机游戏已成为朝阳产业，国家也正在加大力度扶持游戏产业。游戏业是一种朝阳产业，早已是IT界人士的共识。而目前游戏产业从业人员的短缺使得“游戏”人才大为抢手，为游戏业培养人才的游戏教育正逐渐成为一种朝阳产业。本课程就是针对上述情况特为计算机系本专科学生开设的。

《计算机游戏程序设计基础》是游戏系列课程中最重要的一门基础理论课程。它主要介绍游戏开发的基本原理和基本思想。通过学习本课程，学生掌握了游戏软件的设计技术，同时提高学生的编程能力和创造能力。

## 学习本课程学生应掌握的前设课程知识

本课程的先行课程有：高级语言程序设、面向对象程序设计、数据结构

## 学时分配

课程授课时间为36学时，实验课时为18课时
| 章节 | 理论学时 | 实验学时 | 合计学时 |
| --- | --- | --- | --- |
| 第1章 | 2 | 2 | 4 |
| 第2章 | 14 | 8 | 22 |
| 第3章 | 8 | 8 | 16 |
| 第4章 | 8 | 0 | 8 |
| 第5章 | 4 | 0 | 4 |
| 合计 | 36 | 18 | 54 |

## 课程内容和基本要求

第一章 Python概论（2学时+2学时）
主要内容：
 1. Python的介绍与发展历史
 1. Python的安装与运行环境
 1. python游戏开发介绍
基本要求：
要求了解Python发展的历史，掌握Python的安装和运行，了解游戏开发基本过程以及Python在游戏开发中的作用。
实验内容：
 1. Python运行环境的安装
 1. 交互式运行Python
 1. Python编辑器安装
 1. 编辑、运行Python程序
实验要求：
掌握Python开发环境的基本使用

第二章 Python基本语法（14学时+8学时）
主要内容：
 1. Python的基本数据类型
 1. Python的控制流
 1. python的函数
 1. python的类和对象
 1. python的模块和包
基本要求：
要求掌握Python的常用语法，包括基本数据类型、控制流、函数、类、模块等，能够编写简单的Python脚本程序。
实验内容
 1. 掌握Python中基本数据类型和高级数据结构的使用
 1. 掌握分支、循环结构的实现
 1. 掌握函数的用法
 1. 掌握Python类和对象的基本用法
实验要求：
掌握Python基本数据类型的使用，掌握Python的控制流，掌握Python的函数，掌握对象的使用。

第三章 Pygame游戏开发框架（8学时+8学时）
主要内容：
 1. Pygame框架的基本概念和原理
 1. Pygame的基本流程
 1. Pygame动画
 1. Pygame的音乐音效
基本要求：
要求掌握Python的游戏开发框架Pygame的原理，掌握Pygame游戏设计方法，掌握游戏动画的基本原理，掌握游戏音乐和音效的实现方法
实验内容：
 1. 了解Pygame运行环境的安装运行
 1. 掌握Pygame图形接口的使用
 1. 掌握简单的Pygame游戏的编写
 1. 掌握Pygame多媒体接口的使用
 1. 掌握对窗口的控制
基本要求：
 1. 使用Pygame写出简单的程序。

第四章 游戏开发辅助模块（8学时）
主要内容：
 1. OpenGL三维图形
 1. socket网络编程
基本要求：
要求了解Python中OpenGL的使用方法，了解Python中socket的实现方法，能够实现简单的联机游戏。

第五章 游戏开发综合（4学时）
主要内容：
 1. 游戏开发的基本流程
 1. 游戏策划基础
 1. 游戏开发的成功案例
基本要求：
要求了解游戏开发的基本过程（策划、程序、音乐和美术等），掌握游戏设计的基本原理，了解成功的游戏设计案例。

## 教材及学生参考书

教材：
1. 《Learning Python》　 Mark Lutz, David Ascher著 O'Reilly出版社 ISBN 0-596-00281-5
参考书和网站：
1. 《用Python学编程》　Alan Gauld著 清华大学出版社 ISBN 0-201-70938-4
1. 《网络游戏开发》　姚晓光 恽爽 王鑫 译．机械工业出版社．ISBN 7-111-14391-4

## 作业及课外学习要求

为了培养学生主动学习能力和激发学生的创造潜力，要求学生课外在网上多多参阅有关游戏设计的理论、思想和方法。要多动手设计游戏程序。

## 课程考核方式及成绩评定方法

课程的成绩由平时成绩(50%)和游戏设计实物成绩(50%)组成。平时成绩由平时考勤、学习态度、实验成绩组成。课程设计实物成绩由2个的游戏设计实物的成绩组成。

## 其它说明
